export const BUSINESS_TYPE_OPTIONS = [
  'kiosk',
  'grocery',
  'dairy',
  'vegetable',
  'cafe',
  'boutique',
  'electronics',
  'wholesale',
  'stationery',
  'pharmacy',
  'butcher',
  'service',
  'other',
];

export const ITEM_TEMPLATES = {
  dairy: [
    { name: 'ወተት', kind: 'item' },
    { name: 'ዳሪ', kind: 'item' },
    { name: 'ቅቤ', kind: 'item' },
    { name: 'ፎርማጆ', kind: 'item' },
    { name: 'ወተት + ዳቦ', kind: 'item' },
    { name: 'ስኒል', kind: 'item' },
  ],
  vegetable: [
    { name: 'ቲማቲም', kind: 'item' },
    { name: 'ሽንኩርት', kind: 'item' },
    { name: 'ድንች', kind: 'item' },
    { name: 'ሽምብራ', kind: 'item' },
    { name: 'ፍራፍሬ', kind: 'item' },
    { name: 'ጁስ', kind: 'item' },
    { name: 'አቮካዶ', kind: 'item' },
    { name: 'ሙዝ', kind: 'item' },
  ],
  grocery: [
    { name: 'ዳቦ', kind: 'item' },
    { name: 'ዘይት', kind: 'item' },
    { name: 'ስኳር', kind: 'item' },
    { name: 'ሳሙና', kind: 'item' },
    { name: 'ቡና', kind: 'item' },
    { name: 'ሻይ', kind: 'item' },
    { name: 'ጨው', kind: 'item' },
    { name: 'ዱቄት', kind: 'item' },
    { name: 'ማካሮኒ', kind: 'item' },
    { name: 'ብርቱካን ጁስ', kind: 'item' },
  ],
  kiosk: [
    { name: 'ውሃ', kind: 'item' },
    { name: 'ስፒሪት', kind: 'item' },
    { name: 'ቻርጅ', kind: 'item' },
    { name: 'ሳሙና', kind: 'item' },
    { name: 'ዳቦ', kind: 'item' },
    { name: 'ቡና', kind: 'item' },
    { name: 'ስኳር', kind: 'item' },
  ],
  cafe: [
    { name: 'ቡና', kind: 'item' },
    { name: 'ማኪያቶ', kind: 'item' },
    { name: 'ሻይ', kind: 'item' },
    { name: 'ዳቦ', kind: 'item' },
    { name: 'ኬክ', kind: 'item' },
    { name: 'ጁስ', kind: 'item' },
    { name: 'ስፔሻል', kind: 'item' },
  ],
  boutique: [
    { name: 'ሽርት', kind: 'item' },
    { name: 'ጫማ', kind: 'item' },
    { name: 'ቀሚስ', kind: 'item' },
    { name: 'ፓንታሎን', kind: 'item' },
    { name: 'ጃኬት', kind: 'item' },
  ],
  electronics: [
    { name: 'ቻርጅር', kind: 'item' },
    { name: 'ኬብል', kind: 'item' },
    { name: 'ሂድ ፎን', kind: 'item' },
    { name: 'ባትሪ', kind: 'item' },
    { name: 'ስክሪን ፕሮቴክተር', kind: 'item' },
  ],
  wholesale: [
    { name: 'ወተት (box)', kind: 'item' },
    { name: 'ዘይት (carton)', kind: 'item' },
    { name: 'ስኳር (quintal)', kind: 'item' },
    { name: 'ዱቄት (quintal)', kind: 'item' },
  ],
  stationery: [
    { name: 'ደብተር', kind: 'item' },
    { name: 'ብርዕ', kind: 'item' },
    { name: 'ፔን', kind: 'item' },
    { name: 'ፔንሲል', kind: 'item' },
    { name: 'ራባር', kind: 'item' },
    { name: 'ሩለር', kind: 'item' },
  ],
  pharmacy: [
    { name: 'ፓናዶል', kind: 'item' },
    { name: 'ቪታሚን', kind: 'item' },
    { name: 'አስፕሪን', kind: 'item' },
    { name: 'ማስክ', kind: 'item' },
    { name: 'ሳኒታይዘር', kind: 'item' },
  ],
  butcher: [
    { name: 'ስጋ', kind: 'item' },
    { name: 'በግ', kind: 'item' },
    { name: 'ዶሮ', kind: 'item' },
    { name: 'ኪሊላ', kind: 'item' },
    { name: 'ሳንባ', kind: 'item' },
  ],
  service: [],
  other: [],
};

export function getTemplatesForType(businessType) {
  if (!businessType || !ITEM_TEMPLATES[businessType]) return [];
  return ITEM_TEMPLATES[businessType];
}
