// Zod schemas for the Shop Sync v1 identity endpoints.
//
// Reference: spec section M.
//
// These schemas are written by hand (not generated by orval) because
// they are part of the same source tree as the implementation. When
// the OpenAPI yaml is updated to include the same paths, orval will
// regenerate the lib/api-zod/src/generated/* files; the hand-written
// schemas in this file are the canonical contract that the route
// handlers depend on, and they are tested directly by unit tests.

import { z } from "zod";

// ---- shared primitives ----

const E164Like = z
  .string()
  .trim()
  .min(9)
  .max(20)
  .refine((v) => v.length > 0, "phone is empty");

const DisplayName = z
  .string()
  .trim()
  .min(1, "display_name required")
  .max(40, "display_name too long");

const DeviceLabel = z
  .string()
  .trim()
  .min(1, "device_label required")
  .max(60, "device_label too long");

const JoinCode = z
  .string()
  .trim()
  .min(8)
  .max(20)
  .refine((v) => /^[A-Za-z0-9 \-]{8,20}$/.test(v), "invalid join code format");

// ---- POST /api/shops ----

export const CreateShopBody = z.object({
  display_name: DisplayName,
  phone: z.union([z.string(), z.null()]).optional(),
  business_type: z.string().trim().max(40).optional(),
  // v1: defaults to false; the owner can flip these later in Settings.
  phone_required: z.boolean().optional(),
  approval_required: z.boolean().optional(),
});

export type CreateShopBodyT = z.infer<typeof CreateShopBody>;

export const CreateShopResponse = z.object({
  shop_id: z.string().uuid(),
  shop_name: z.string(),
  join_code: z.string(),
  join_url: z.string(),
  staff_id: z.string().uuid(),
  device_id: z.string().uuid(),
  display_name: z.string(),
  role: z.literal("owner"),
  permissions: z.record(z.string(), z.boolean()),
  device_token: z.string().min(16),
  device_status: z.literal("active"),
  phone_required: z.boolean(),
  approval_required: z.boolean(),
});

// ---- POST /api/shops/join ----

export const JoinShopBody = z.object({
  join_code: JoinCode,
  display_name: DisplayName,
  phone: z.union([z.string(), z.null()]).optional(),
  device_label: DeviceLabel.optional(),
  device_id: z.string().uuid().optional(),
});

export type JoinShopBodyT = z.infer<typeof JoinShopBody>;

export const JoinShopResponse = z.object({
  shop_id: z.string().uuid(),
  shop_name: z.string(),
  role: z.string(),
  permissions: z.record(z.string(), z.boolean()),
  device_token: z.string().min(16),
  device_status: z.enum(["pending", "active"]),
  rejoined: z.boolean(),
  previous_devices: z.number().int().nonnegative().optional(),
});

// ---- GET /api/me ----

export const MeResponse = z.object({
  user_id: z.string().uuid(),
  staff_id: z.string().uuid(),
  shop_id: z.string().uuid(),
  role: z.string(),
  display_name: z.string(),
  phone: z.string().nullable(),
  device_id: z.string().uuid(),
  device_status: z.enum(["pending", "active", "revoked"]),
  permissions: z.record(z.string(), z.boolean()),
});

// ---- GET /api/shops/:shop_id/staff ----

export const ListStaffResponse = z.object({
  staff: z.array(
    z.object({
      staff_id: z.string().uuid(),
      display_name: z.string(),
      phone_snapshot: z.string().nullable(),
      role: z.string(),
      staff_status: z.enum(["active", "inactive"]),
      permissions: z.record(z.string(), z.boolean()),
      joined_at: z.string(),
      last_seen_at: z.string().nullable(),
      deactivated_at: z.string().nullable(),
      devices: z.array(
        z.object({
          device_id: z.string().uuid(),
          device_label: z.string(),
          device_status: z.enum(["pending", "active", "revoked"]),
          last_seen_at: z.string().nullable(),
          created_at: z.string(),
        })
      ),
    })
  ),
});

// ---- POST /api/shops/:shop_id/rotate-code ----

export const RotateJoinCodeResponse = z.object({
  join_code: z.string(),
  join_url: z.string(),
});

// ---- POST /api/shops/:shop_id/settings ----

export const UpdateShopSettingsBody = z.object({
  phone_required: z.boolean().optional(),
  approval_required: z.boolean().optional(),
});

export type UpdateShopSettingsBodyT = z.infer<typeof UpdateShopSettingsBody>;

export const UpdateShopSettingsResponse = z.object({
  phone_required: z.boolean(),
  approval_required: z.boolean(),
});

// ---- POST /api/staff/:staff_id/permissions ----

export const UpdateStaffPermissionsBody = z.object({
  can_create_customer_credit: z.boolean(),
});

export type UpdateStaffPermissionsBodyT = z.infer<typeof UpdateStaffPermissionsBody>;

export const UpdateStaffPermissionsResponse = z.object({
  staff_id: z.string().uuid(),
  permissions: z.record(z.string(), z.boolean()),
});

// ---- POST /api/staff/:staff_id/deactivate ----

export const DeactivateStaffResponse = z.object({
  deactivated: z.literal(true),
  devices_revoked: z.number().int().nonnegative(),
});

// ---- POST /api/devices/:device_id/approve ----

export const ApproveDeviceResponse = z.object({
  device_id: z.string().uuid(),
  device_status: z.literal("active"),
});

// ---- POST /api/devices/:device_id/reject ----

export const RejectDeviceBody = z.object({
  reason: z.string().trim().max(200).optional(),
});

// ---- POST /api/devices/:device_id/revoke ----

export const RevokeDeviceBody = z.object({
  reason: z.enum(["staff_deactivated", "owner_revoke", "replaced"]),
});

export const RevokeDeviceResponse = z.object({
  device_id: z.string().uuid(),
  device_status: z.literal("revoked"),
});
