import { createContext, useContext, useState } from 'react';

import { useEffect } from 'react';

// WARNING: NATIVE-SPEAKER VERIFICATION REQUIRED
// All Amharic (AM) strings below were machine-translated and have NOT been
// reviewed by a native Amharic speaker. Before public launch, every string in
// the AM object must be verified and corrected by a native speaker - especially
// financial/business terminology, verb forms, and formal/informal register.
// Do NOT ship to production without completing this review.

const EN = {
  installSectionTitle: 'Install App',
  installBannerTitle: 'Install Gebya on this phone',
  installBannerBody: 'Add Gebya to your home screen so you can open it like an app.',
  installNow: 'Install Now',
  installHowTo: 'Install',
  installGuideButton: 'How to install',
  installGuideTitle: 'Install Gebya on your phone',
  installGuideHint: 'Do this once, then open Gebya from your phone home screen.',
  installGuideDeviceTitle: 'Phone install steps',
  installAlreadyInstalled: 'Already installed',
  installStatusInstalled: 'Installed on your home screen',
  installStatusBrowser: 'Running in browser mode',
  installStatusOnline: 'Online now',
  installStatusOffline: 'Offline now',
  installChecklistOffline: 'Offline-ready notebook',
  installChecklistHomeScreen: 'Home screen install',
  installChecklistData: 'Data location',
  installChecklistReady: 'Ready',
  installChecklistInstalled: 'Installed',
  installChecklistPending: 'Not yet',
  installChecklistOnPhone: 'This phone',
  installIosStep1: 'Open Gebya in Safari.',
  installIosStep2: 'Tap Share, then tap "Add to Home Screen."',
  installIosStep3: 'Tap "Add", then open Gebya from your home screen.',
  installAndroidStep1: 'Open Gebya in Chrome.',
  installAndroidStep2: 'Open the browser menu and tap "Install app" or "Add to Home screen."',
  installAndroidStep3: 'Confirm, then open Gebya from your home screen.',
  installGenericStep1: 'Open Gebya in your phone browser.',
  installGenericStep2: 'Open the browser menu and look for "Install app" or "Add to Home Screen."',
  installGenericStep3: 'Save it, then open Gebya from your home screen.',
  updateReadyTitle: 'Fresh version ready',
  updateReadyBody: 'A newer app version is available. Refresh once to use the latest installable build.',
  refreshApp: 'Refresh App',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even when your connection is weak, and your saved notebook stays on this phone.',
  offlineNowTitle: 'You are offline',
  offlineNowBody: 'Your saved notebook on this phone still works. Features that need internet may wait until you reconnect.',
  notNow: 'Not now',
  telegramNotifyConnectFirst: 'Connect Telegram first, then turn this on.',
  telegramConnectFirstToast: 'Connect Telegram first to send updates.',
  appName: 'áŒˆá‰ á‹«',
  loading: 'Loading your notebook...',
  today: 'Today',
  todayLabel: 'á‹›áˆ¬',
  credit: 'Dubie',
  creditLabel: 'á‹±á‰¤',
  report: 'Report',
  settings: 'Settings',
  sales: 'Sales',
  spent: 'Spent',
  iSold: 'I Sold',
  iSoldLabel: 'áˆ¸áŒ áˆ',
  iSpent: 'I Spent',
  iSpentLabel: 'á‹ˆáŒª',
  creditBtn: 'Dubie',
  creditBtnLabel: 'á‹±á‰¤',
  calc: 'Calc',
  todaysEntries: "Today's Entries",
  noEntries: 'No entries yet. Use the buttons above to start!',
  profit: 'profit',
  edited: 'edited',
  editEntry: 'Edit entry',
  deleteEntryLabel: 'Delete entry',
  calculator: 'Profit Calculator',
  calcCost: 'Cost Price',
  calcSell: 'Selling Price',
  calcProfit: 'Profit',
  calcMargin: 'Margin',
  calcPlaceholder: 'Enter amount...',
  topProducts: 'Top Sold Today',
  weekTrend: '7-Day Trend',
  shareReport: 'Share Report',
  shareReportBtn: 'Share Today',
  shareTitle: 'Share Daily Report',
  shareDailyReport: 'Daily Report',
  shareTopItems: 'Top Items Sold',
  shareSentVia: 'Sent via Gebya',
  shareViaDevice: 'Share via Device',
  openTelegram: 'Open in Telegram',
  copyText: 'Copy Text',
  usageInsights: 'Usage Insights',
  dayStreak: 'day streak',
  best: 'best',
  daysActive: 'days active',
  since: 'since',
  totalEntries: 'entries',
  sessions: 'sessions opened',
  shareMyStats: 'Share My Stats',
  copiedToClipboard: 'Copied to clipboard!',
  shopProfile: 'Profile',
  userName: 'Name',
  phoneNumber: 'Phone Number',
  phoneRequired: 'Phone number is required',
  phoneInvalid: '9 digits starting with 7 or 9',
  telegramLabel: 'Telegram / Contact',
  telegramPlaceholder: '@username, t.me/... or https://t.me/...',
  connectTelegram: 'Connect Telegram',
  manageTelegram: 'Manage Telegram',
  telegramConnection: 'Telegram connection',
  telegramConnectHint: 'Link Telegram once, then turn on balance updates when you want.',
  telegramConnectedHint: 'This customer can receive Telegram balance updates.',
  notifyOnTelegram: 'Notify on Telegram',
  notifyOnTelegramHint: 'Open Telegram automatically after saving Dubie or payment.',
  telegramNotifyEnabledState: 'Automatic Telegram opening is on for this customer.',
  telegramNotifyDisabledState: 'Telegram stays optional and will not open automatically.',
  telegramNeedContactHint: 'Add a Telegram username or link first, then turn notifications on.',
  telegramFormatHint: 'Use only @username, t.me/... or https://t.me/...',
  telegramAutoUpdatesTitle: 'Automatic balance updates',
  telegramAutoUpdatesBody: 'Once linked, this customer can receive Telegram updates whenever their balance changes.',
  qrPrimaryMethod: 'QR code',
  telegramQrHint: 'Let the customer scan this QR code to open the Telegram connection link.',
  shareInviteLink: 'Share invite link',
  shareInviteLinkHint: 'Copy this link and send it through any channel you already use.',
  copyLink: 'Copy link',
  inviteLinkCopied: 'Invite link copied',
  copyFailed: 'Could not copy link',
  manualTelegramFallback: 'Manual fallback',
  manualTelegramFallbackHint: 'If needed, enter the customer Telegram username or t.me link manually.',
  confirmConnection: 'Confirm Connection',
  skipForNow: 'Skip for Now',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  privacy: 'Privacy',
  hideAmounts: 'Hide amounts',
  totalsHidden: 'Totals are hidden - tap to show',
  totalsVisible: 'Totals are visible - tap to hide',
  paymentMethods: 'Payment Methods',
  banks: 'Banks',
  mobileWallets: 'Mobile Wallets',
  onlyEnabled: 'Only enabled methods appear as options in the form',
  recurringExpenses: 'Recurring Expenses',
  recurringHint: 'Quick-fill shortcuts for expenses you enter often',
  addRecurring: 'Add recurring expense',
  demoCardSectionLabel: 'Quick-fill (examples)',
  addRecurringPopupGuide: 'Save this as a recurring expense to reuse it anytime',
  addAndUse: 'Add & Use',
  addRecurringHint: 'You can add more recurring expenses in Settings',
  frequency: 'Frequency',
  cancel: 'Cancel',
  add: 'Add',
  yourData: 'Your Data',
  storedOnDevice: 'Stored on this device',
  exportCSV: 'Export to CSV',
  exportHint: 'Download a spreadsheet backup',
  clearAll: 'Clear all data',
  clearHint: 'Permanently deletes everything - export first!',
  about: 'About',
  privacyNote: 'Your data never leaves this device. No account needed.',
  worksOffline: 'Works offline - data stays on your phone - free',
  achievementBadges: 'Achievement Badges',
  badgesEarned: 'earned',
  noBadges: 'Complete milestones to earn badges!',
  clearConfirm: 'Clear all data?',
  clearConfirmMsg: 'This will permanently delete all {count} entries and {credits} Dubie records. This cannot be undone.',
  yesDelete: 'Yes, delete everything',
  dataCleared: 'Data cleared',
  reloading: 'Reloading...',
  deleteEntry: 'Delete this entry?',
  delete: 'Delete',
  newBestDay: 'New best day!',
  birr: 'birr',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  expenseName: 'Expense name (e.g. Rent)',
  amount: 'Amount',
  sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',

  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'á‹¨áˆ±á‰… áˆ›áˆµá‰³á‹ˆáˆ» á‹°á‰¥á‰°áˆ­',
  onboardDesc: 'Enter your name and start using Gebya right away.',
  onboardNamePlaceholder: 'e.g. Tigist',
  onboardPhoneOptional: '(optional)',
  onboardPhoneHelper: 'You can add your phone later in Settings.',
  onboardPromiseSimple: 'Simple notebook for sales, spending, and Dubie',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'Your records stay on this phone',
  onboardGetStarted: 'Start using Gebya',
  onboardSettingUp: 'Setting up…',
  onboardFooter: 'All data stays on your phone · No account needed · Free',

  iSoldSomething: 'I Sold Something',
  iSpentSomething: 'I Spent Something',
  recordCredit: 'Record Dubie',
  addCredit: 'Add Dubie',
  addCustomer: 'Add Customer',
  saveCustomer: 'Save customer',
  customerSaved: 'Customer saved',
  customerSaveFailed: 'Could not save customer. Please try again.',
  customerHelperText: 'Use any label you will recognize later.',
  customerIdentifier: 'Customer identifier',
  customerIdentifierPlaceholder: 'Name, nickname, relation, place, or vehicle clue',
  customerNotePlaceholder: 'Anything that helps you recognize this customer',
  customerPhoneOptional: 'Phone (optional)',
  customerPhonePlaceholder: 'Phone number',
  customerTelegramOptional: 'Telegram (optional)',
  customerTelegramPlaceholder: '@username, t.me/... or https://t.me/...',
  customerTotalBalance: 'Total Balance',
  customerBalance: 'Balance',
  searchCustomerPlaceholder: 'Search customer or note...',
  customerSearchHint: 'Search by name, note, phone, or Telegram.',
  customerSearchResults: 'Showing {shown} of {total} customers',
  noCustomersFound: 'No customers found',
  noCustomersYet: 'No customers yet',
  noCustomerSearchResults: 'No customers match this search',
  backToCustomers: 'Back to customers',
  customerTransactionHistory: 'Transaction History',
  paymentRecordedLabel: 'Payment',
  creditAddedLabel: 'Dubie added',
  noTransactionsYet: 'No transactions yet',
  noTransactionsHint: 'Use Add Dubie or Record Payment to start this history.',
  currentBalance: 'Current Balance',
  previousBalance: 'Previous balance',
  updatedBalance: 'Updated balance',
  currentBalanceHint: 'This is the balance after saving the new Dubie.',
  remainingBalanceHint: 'This is the remaining balance after saving the payment.',
  paymentNoteOptional: 'Payment note (optional)',
  itemNoteOptional: 'Item note (optional)',
  paymentNotePlaceholder: 'Any note about this payment',
  creditItemPlaceholder: 'What they took',
  dueDateOptional: 'Due date (optional)',
  ethiopianDisplay: 'Ethiopian display',
  pickDateWithEthiopianHint: 'Choose any date below and we will also show it in Ethiopian calendar.',
  moreOptional: 'More (optional)',
  noteLabel: 'Note',
  savePayment: 'Save payment',
  customerNotFound: 'Customer not found',
  validAmountRequired: 'Enter a valid amount',
  paymentMoreThanBalance: 'Payment is more than the current balance',
  noBalanceToRecordPayment: 'No balance to collect yet',
  balanceAfterEntry: 'Balance after this entry',
  dueLabelShort: 'Due',
  whatDidYouSell: 'What did you sell?',
  sellPlaceholder: 'e.g. bread, sugar...',
  whatDidYouSpendOn: 'What did you spend on?',
  spendPlaceholder: 'e.g. transport, rent...',
  creditNameLabel: 'Name',
  creditNamePlaceholder: 'e.g. Abebe...',
  howMuchTotal: 'How much total?',
  saveSale: 'Save Sale',
  saveExpense: 'Save Expense',
  saveCredit: 'Save Dubie',
  addAnotherSale: 'Add another sale',
  addAnotherExpense: 'Add another expense',
  done: 'Done',
  birrSaved: 'birr saved',
  howMany: 'How many?',
  direction: 'Direction',
  theyOweMe: 'They owe me',
  iOweThem: 'I owe them',
  owesMe: 'á‹«á‰ á‹°áˆ­áŠ©á‰µ',
  iOweLabel: 'á‹¨á‰°á‰ á‹°áˆ­áŠ©á‰µ',
  quickFill: 'Quick-fill',
  phoneOptional: 'Phone number',
  phoneOptionalHint: '(optional)',
  phonePlaceholder: 'e.g. 0912345678',
  whenDue: 'When is it due?',
  pickDate: 'Pick a date',
  selectDueDate: 'Please select a due date',
  advancedOptional: 'Advanced (optional)',
  whatDidYouPay: 'What did you pay for this?',
  perUnit: '(per unit)',
  helpsSeeProfit: 'Optional - helps you see your true profit',
  sellingBelowCost: 'You are selling below cost. You may lose money on this sale.',
  profitOnSale: 'Profit on this sale:',
  paymentType: 'Payment type',
  cash: 'Cash',
  bank: 'Bank',
  wallet: 'Wallet',

  editSale: 'Edit Sale',
  editExpense: 'Edit Expense',
  editCredit: 'Edit Dubie',
  editEntryLabel: 'Edit Entry',
  editedAt: 'Edited',
  item: 'Item',
  quantity: 'Quantity',
  dueDate: 'Due date',
  costPriceLabel: 'Cost price',
  sellingBelowCostShort: 'Selling below cost.',
  profitLabel: 'Profit:',
  saving: 'Saving...',

  todaysProfit: "Today's Profit",
  estimatedProfit: "Estimated Profit",
  partialCostDisclaimer: "Some items are missing a cost price - this estimate may be lower than your actual profit",
  partialCostTip: "Add cost prices to your items for an accurate profit figure",
  todaysSales: "Today's Sales",
  salesLabel: 'Sales',
  expenses: 'Expenses',
  costOfGoods: 'Cost of goods',
  netProfit: 'Net Profit',
  advancedHint: 'Tap "Advanced" when recording a sale to see true profit',

  tapToReveal: 'Tap to reveal',
  tapToRevealAria: 'Tap to reveal amount',
  hideAmountAria: 'Hide amount',

  byDay: 'By Day',
  byWeek: 'By Week',
  groupBy: 'Group:',
  searchPlaceholder: 'Search by item or customer...',
  noSearchResults: 'No results for',
  noRecords: 'No records yet',
  startRecording: 'Record your first sale or expense to start',
  entries: 'entries',
  revenue: 'revenue',
  thisWeek: 'This Week',

  noCreditRecords: 'No Dubie records',
  addCreditHint: 'Tap "á‹±á‰¤" on the Today tab to add one',
  owedToMe: 'Owed to me',
  iOweAmount: 'I owe',
  active: 'active',
  paid: 'paid',
  activeTab: 'Active',
  paidTab: 'Paid',
  noPaidRecords: 'No paid records yet',
  allCaughtUp: 'All caught up!',
  paidInFull: 'Paid in full',
  paidLabel: 'PAID',
  due: 'Due',
  owesMeLabel: 'Owes me',
  iOweTag: 'I owe',

  backToCredit: 'Back to á‹±á‰¤',
  originalDebt: 'Original debt',
  amountPaid: 'Amount paid',
  stillOwes: 'Still owes',
  progress: 'Progress',
  percentPaid: '% paid',
  paidSome: 'Paid Some',
  allPaid: 'All Paid',
  call: 'Call',
  recordPartialPayment: 'Record Partial Payment',
  recordPayment: 'Record Payment',
  markFullyPaid: 'Mark Fully Paid',
  paymentHistory: 'Payment history',
  borrowed: 'Borrowed',
  paidBack: 'Paid back',
  remaining: 'Remaining',
  payMethodCash: 'Cash',
  payMethodBank: 'Bank Transfer',
  payMethodMobile: 'Mobile Money',
  paymentExceedsOwed: 'Amount cannot exceed what is owed',

  voiceNotSupported: 'Voice not supported - use keyboard',
  voiceInput: 'Voice input',
  tryAgain: 'Try again',
  voiceMicBlocked: 'Microphone is blocked. Check browser settings.',

  close: 'Close',

  todaysBreakdown: "Today's Breakdown",
  payingVia: 'Paying via',
  creditPhoneHint: '9 digits starting with 7 or 9',
  addCustomBank: 'Add bank...',
  addCustomWallet: 'Add wallet...',
  customProviderName: 'Provider name',
  providerEnabled: 'Enabled',
  providerDisabled: 'Disabled',

  introSlide1Title: 'Your Business Notebook',
  introSlide1Body: 'Track sales, expenses, and Dubie - all on your phone. No account needed.',
  introSlide2Title: 'See Your Money at a Glance',
  introSlide2Body: "Today's profit always shows at the top. Know where you stand in seconds.",
  introSlide3Title: 'Three Buttons. That\'s It.',
  introSlide3Body: 'Tap Type Sale to sell, I Spent to record spending, and Dubie to track credit. Done in 10 seconds.',
  introLetsStart: "Let's start",
  introNext: 'Next ->',
  introSkip: 'Skip intro',

  noEntriesPrompt: 'Tap Type Sale above to record your first sale',

  saleSaved: 'Sale saved - keep going',
  expenseSaved: 'Expense recorded',
  creditSaved: 'Dubie recorded',
  paymentSaved: 'Payment recorded',
  trustCardTitle: 'Your notebook stays on this phone',
  trustCardBody: 'Save your sales, close the app, and open again later. Your records stay here on this phone.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Close and reopen anytime - your records stay here.',
  undone: 'Undone',

  statusOverdue: 'OVERDUE',
  statusDueSoon: 'DUE SOON',
  statusOk: 'OK',

  periodDay: 'Day',
  periodWeek: 'Week',
  periodMonth: 'Month',
  totalSales: 'Total Sales',
  totalExpenses: 'Total Expenses',
  topProductsWeek: 'Top Products This Week',
  topProductsMonth: 'Top Products This Month',
  topProductsDay: 'Top Products Today',
  byQuantity: 'by qty',
  byRevenue: 'by revenue',
  weekBreakdown: 'Day-by-Day',
  monthBreakdown: 'Week-by-Week',
  weekOf: 'Week of',
  noSalesThisPeriod: 'No sales this period',
  week: 'Wk',

  recordByVoice: 'Speak to Record Sale',
  recordByVoiceSubLabel: 'Fastest way to save a sale',
  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',
  voiceRecordingTitle: 'Recording...',
  voiceRecordingHint: 'Speak your sale amount',
  voiceStop: 'Stop',
  voiceTypeInstead: 'Type instead',
  voiceNoInternet: 'No internet connection',
  voiceNoInternetHint: 'Voice transcription requires internet. You can still type your sale.',
  voiceTypeSaleInstead: 'Type Sale Instead',
  voiceRetry: 'Retry',
  voiceSlowNetwork: 'The connection is slow. You can retry or type the sale instead.',
  voiceTryFinishSoon: 'Try to finish soon',
  voiceResultTitle: 'Voice Result',
  voiceTranscript: 'What you said',
  voiceDetectedTotal: 'Detected total',
  voiceNoAmount: 'No amount detected',
  voiceNeedsReview: 'Check this draft before saving.',
  voiceParsedItems: 'Parsed items',
  voiceCustomerName: 'Customer',
  voiceCustomerPlaceholder: 'Customer name if mentioned',
  voiceIntent: 'Intent',
  voiceIntentSale: 'Sale',
  voiceIntentCredit: 'Dubie',
  voiceIntentPayment: 'Payment',
  voiceQuantity: 'Qty',
  voiceUnitPrice: 'Unit price',
  voiceAutoCalculatedTotal: 'Total auto-calculated from line items.',
  voiceItemNamePlaceholder: 'Item name',
  voiceSave: 'Save Sale',
  voiceFix: 'Fix & Edit',
  voiceReRecord: 'Re-record',
  voiceFixTitle: 'Fix Voice Sale',
  voiceTotalLabel: 'Total amount',
  voiceNoteLabel: 'Note (optional)',
  voiceNotePlaceholder: 'e.g. bread, sugar...',
  voiceSaleSaved: 'Voice sale saved',
  voiceAddAnotherItem: 'Add another item',
  voiceRunningTotal: 'Running Total',
  voiceItemsRecorded: 'items recorded',
};

// Install-related Amharic strings below require human review before public beta:
// installSectionTitle, installBannerTitle, installBannerBody, installNow, installHowTo,
// installGuideButton, installGuideTitle, installGuideHint, installGuideDeviceTitle,
// installAlreadyInstalled, installStatusInstalled, installStatusBrowser,
// installStatusOnline, installStatusOffline, installChecklistOffline,
// installChecklistHomeScreen, installChecklistData, installChecklistReady,
// installChecklistInstalled, installChecklistPending, installChecklistOnPhone,
// installIosStep1, installIosStep2, installIosStep3, installAndroidStep1,
// installAndroidStep2, installAndroidStep3, installGenericStep1,
// installGenericStep2, installGenericStep3.
const AM = {
  installSectionTitle: 'áˆ˜á‰°áŒá‰ áˆªá‹« áŒ«áŠ•',
  installBannerTitle: 'áŒˆá‰ á‹«áŠ• á‰ á‹šáˆ… áˆµáˆáŠ­ áˆ‹á‹­ áŒ«áŠ•',
  installBannerBody: 'áŒˆá‰ á‹«áŠ• á‹ˆá‹° áˆ˜áŠáˆ» áŒˆáŒ½ á‹«áˆµá‰€áˆáŒ¡á‰µ áŠ¥áŠ“ áŠ¥áŠ•á‹° áˆžá‰£á‹­áˆ áˆ˜á‰°áŒá‰ áˆªá‹« á‹­áŠ­áˆá‰±á‰µá¢',
  installNow: 'áŠ áˆáŠ• áŒ«áŠ•',
  installHowTo: 'áŒ«áŠ•',
  installGuideButton: 'áŠ¥áŠ•á‹´á‰µ áŠ¥áŠ•á‹°áˆšáŒ«áŠ•',
  installGuideTitle: 'áŒˆá‰ á‹«áŠ• á‰ áˆµáˆáŠ­á‹Ž áˆ‹á‹­ áŒ«áŠ•',
  installGuideHint: 'áŠ áŠ•á‹µ áŒŠá‹œ áŒ«áŠ• áŠ«á‹°áˆ¨áŒ‰ á‰ áŠ‹áˆ‹ áŒˆá‰ á‹« áŠ¥áŠ•á‹° áˆžá‰£á‹­áˆ áˆ˜á‰°áŒá‰ áˆªá‹« á‹­áˆ°áˆ›áˆá¢',
  installGuideDeviceTitle: 'á‹¨áˆµáˆáŠ­ áŒ«áŠ• áŠ¥áˆ­áˆáŒƒá‹Žá‰½',
  installAlreadyInstalled: 'áŠ áˆµá‰€á‹µáˆž á‰°áŒ­áŠ—áˆ',
  installStatusInstalled: 'á‰ áˆ˜áŠáˆ» áŒˆáŒ½ áˆ‹á‹­ á‰°áŒ­áŠ—áˆ',
  installStatusBrowser: 'á‰ á‰¥áˆ«á‹á‹˜áˆ­ á‹áˆµáŒ¥ áŠ¥á‹¨áˆ°áˆ« áŠá‹',
  installStatusOnline: 'áŠ áˆáŠ• áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ áŠ áˆˆ',
  installStatusOffline: 'áŠ áˆáŠ• áŠ¨áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹áŒª áŠá‹',
  installChecklistOffline: 'áŠ¨áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹áŒª á‹¨áˆšáˆ°áˆ« áˆ›áˆµá‰³á‹ˆáˆ»',
  installChecklistHomeScreen: 'á‹¨áˆ˜áŠáˆ» áŒˆáŒ½ áŒ«áŠ•',
  installChecklistData: 'á‹¨á‹áˆ‚á‰¥ á‰¦á‰³',
  installChecklistReady: 'á‹áŒáŒ',
  installChecklistInstalled: 'á‰°áŒ­áŠ—áˆ',
  installChecklistPending: 'áŒˆáŠ“ áŠ á‹­á‹°áˆˆáˆ',
  installChecklistOnPhone: 'á‰ á‹šáˆ… áˆµáˆáŠ­',
  installIosStep1: 'áŒˆá‰ á‹«áŠ• á‰  iPhone Safari á‹áˆµáŒ¥ á‹­áŠ­áˆá‰±á‰µá¢',
  installIosStep2: 'á‹¨áˆ›áŒ‹áˆ«á‰µ á‰áˆá‰áŠ• á‹­áŒ«áŠ‘áŠ“ "Add to Home Screen" á‹­áˆáˆ¨áŒ¡á¢',
  installIosStep3: '"Add" á‹­áŒ«áŠ‘ áŠ¥áŠ“ áŒˆá‰ á‹«áŠ• áŠ¨áˆ˜áŠáˆ» áŒˆáŒ½ á‹­áŠ­áˆá‰±á‰µá¢',
  installAndroidStep1: 'áŒˆá‰ á‹«áŠ• á‰  Android Chrome á‹áˆµáŒ¥ á‹­áŠ­áˆá‰±á‰µá¢',
  installAndroidStep2: 'á‹¨á‰¥áˆ«á‹á‹˜áˆ­ áˆáŠ“áˆŒ á‹­áŒ«áŠ‘áŠ“ "Install app" á‹ˆá‹­áˆ "Add to Home screen" á‹­áˆáˆ¨áŒ¡á¢',
  installAndroidStep3: 'áŒ«áŠ‘áŠ• á‹«áˆ¨áŒ‹áŒáŒ¡áŠ“ áŒˆá‰ á‹«áŠ• áŠ¨áˆ˜áŠáˆ» áŒˆáŒ½ á‹­áŠ­áˆá‰±á‰µá¢',
  installGenericStep1: 'áŒˆá‰ á‹«áŠ• á‰ áˆµáˆáŠ­á‹Ž á‰¥áˆ«á‹á‹˜áˆ­ á‹áˆµáŒ¥ á‹­áŠ­áˆá‰±á‰µá¢',
  installGenericStep2: 'á‰ á‰¥áˆ«á‹á‹˜áˆ­ áˆáŠ“áˆŒ "Install app" á‹ˆá‹­áˆ "Add to Home Screen" á‹­áˆáˆáŒ‰á¢',
  installGenericStep3: 'á‹«áˆµá‰€áˆáŒ¡á‰µáŠ“ áŒˆá‰ á‹«áŠ• áŠ¨áˆ˜áŠáˆ» áŒˆáŒ½ á‹­áŠ­áˆá‰±á‰µá¢',
  updateReadyTitle: 'áŠ á‹²áˆµ áŠ¥á‰µáˆ á‹áŒáŒ áŠá‹',
  updateReadyBody: 'áŠ á‹²áˆµ á‹¨áˆ˜á‰°áŒá‰ áˆªá‹« áŠ¥á‰µáˆ áŠ áˆˆá¢ áŠ áŠ•á‹µ áŒŠá‹œ á‹«á‹µáˆ±á¢',
  refreshApp: 'áˆ˜á‰°áŒá‰ áˆªá‹«á‹áŠ• áŠ á‹µáˆµ',
  offlineReadyTitle: 'áŠ¨áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹áŒª áˆáŠ”á‰³ á‹áŒáŒ áŠá‹',
  offlineReadyBody: 'áŒˆá‰ á‹« áŒáŠ•áŠ™áŠá‰µ á‹°áŠ«áˆ› á‰¢áˆ†áŠ•áˆ áŠ¥áŠ•á‹°áŒˆáŠ“ áˆŠáŠ¨áˆá‰µ á‹­á‰½áˆ‹áˆá£ á‹¨á‰°á‰€áˆ˜áŒ á‹áˆ áˆ›áˆµá‰³á‹ˆáˆ» á‰ á‹šáˆ… áˆµáˆáŠ­ áˆ‹á‹­ á‹­á‰†á‹«áˆá¢',
  offlineNowTitle: 'áŠ áˆáŠ• áŠ¨áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹áŒª áŠá‹',
  offlineNowBody: 'á‰ á‹šáˆ… áˆµáˆáŠ­ áˆ‹á‹­ á‹¨á‰°á‰€áˆ˜áŒ á‹ áˆ›áˆµá‰³á‹ˆáˆ» áŠ¥áŠ•á‹°áˆšáˆ°áˆ« á‹­á‰€áŒ¥áˆ‹áˆá¢ áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹¨áˆšáˆáˆáŒ‰ á‰£áˆ…áˆªá‹«á‰µ áŒáŠ• áŠ¥áˆµáŠ¨áˆšáˆ˜áˆˆáˆ± á‹µáˆ¨áˆµ áˆŠáŒ á‰¥á‰ á‹­á‰½áˆ‹áˆ‰á¢',
  notNow: 'áŠ áˆáŠ• áŠ á‹­á‹°áˆˆáˆ',
  telegramNotifyConnectFirst: 'á‰´áˆŒáŒáˆ«áˆáŠ• á‰ áˆ˜áŒ€áˆ˜áˆªá‹« á‹«áŒˆáŠ“áŠ™á£ áŠ¨á‹šá‹« á‹­áˆ…áŠ• á‹«á‰¥áˆ©á¢',
  telegramConnectFirstToast: 'á‹áˆ˜áŠ“ áˆˆáˆ˜áˆ‹áŠ­ á‰´áˆŒáŒáˆ«áˆáŠ• á‰ áˆ˜áŒ€áˆ˜áˆªá‹« á‹«áŒˆáŠ“áŠ™á¢',
  appName: 'áŒˆá‰ á‹«',
  loading: 'áˆ›áˆµá‰³á‹ˆáˆ» áŠ¥á‹¨áŒ«áŠâ€¦',
  today: 'á‹›áˆ¬',
  todayLabel: 'á‹›áˆ¬',
  credit: 'á‹±á‰¤',
  creditLabel: 'á‹±á‰¤',
  report: 'áˆªá–áˆ­á‰µ',
  settings: 'á‰…áŠ•á‰¥áˆ®á‰½',
  sales: 'áˆ½á‹«áŒ­',
  spent: 'á‹ˆáŒª',
  iSold: 'áˆ¸áŒ áˆ',
  iSoldLabel: 'áˆ¸áŒ áˆ',
  iSpent: 'á‹ˆáŒª',
  iSpentLabel: 'á‹ˆáŒª',
  creditBtn: 'á‹±á‰¤',
  creditBtnLabel: 'á‹±á‰¤',
  calc: 'áˆ’áˆ³á‰¥',
  todaysEntries: 'á‹¨á‹›áˆ¬ áŒá‰¤á‰¶á‰½',
  noEntries: 'áŠ¥áˆµáŠ«áˆáŠ• áˆáŠ•áˆ áŒá‰¤á‰µ á‹¨áˆˆáˆá¢ áˆˆáˆ˜áŒ€áˆ˜áˆ­ áŠ¨áˆ‹á‹­ á‹«áˆ‰á‰µáŠ• á‰áˆáŽá‰½ á‹­áŒ á‰€áˆ™!',
  profit: 'á‰µáˆ­á',
  edited: 'á‰°áˆµá‰°áŠ«áŠ­áˆáˆ',
  editEntry: 'áŒá‰¤á‰µ áŠ áˆµá‰°áŠ«áŠ­áˆ',
  deleteEntryLabel: 'áŒá‰¤á‰µ áˆ°áˆ­á‹',
  calculator: 'á‹¨á‰µáˆ­á áŠ«áˆáŠ©áˆŒá‰°áˆ­',
  calcCost: 'á‹¨á‹‹áŒ‹ á‰…áŠ“áˆ½',
  calcSell: 'á‹¨áˆ½á‹«áŒ­ á‹‹áŒ‹',
  calcProfit: 'á‰µáˆ­á',
  calcMargin: 'á‰µáˆ­á (%)',
  calcPlaceholder: 'áˆ˜áŒ áŠ• á‹«áˆµáŒˆá‰¡â€¦',
  topProducts: 'á‹›áˆ¬ áˆáˆ­áŒ¥ áˆ½á‹«áŒ­',
  weekTrend: 'á‹¨7 á‰€áŠ• áŠ á‹áˆ›áˆšá‹«',
  shareReport: 'áˆªá–áˆ­á‰µ áŠ áŒ‹áˆ«',
  shareReportBtn: 'á‹›áˆ¬áŠ• áŠ áŒ‹áˆ«',
  shareTitle: 'á‹•áˆˆá‰³á‹Š áˆªá–áˆ­á‰µ áŠ áŒ‹áˆ«',
  shareDailyReport: 'á‹•áˆˆá‰³á‹Š áˆªá–áˆ­á‰µ',
  shareTopItems: 'áˆáˆ­áŒ¥ áˆ½á‹«áŒ­',
  shareSentVia: 'á‰  áŒˆá‰ á‹« (Gebya) á‰°áˆáŠ³áˆ',
  shareViaDevice: 'á‰ áˆµáˆáŠ­ áŠ áŒ‹áˆ«',
  openTelegram: 'á‰´áˆŒáŒáˆ«áˆ áŠ­áˆá‰µ',
  copyText: 'áŒ½áˆ‘á á‰…á‹³',
  usageInsights: 'á‹¨áŠ áŒ á‰ƒá‰€áˆ á‹áˆ­á‹áˆ­',
  dayStreak: 'á‰€áŠ• á‰°áŠ¨á‰³á‰³á‹­',
  best: 'áˆáˆ­áŒ¥',
  daysActive: 'áŠ•á‰ á‰€áŠ“á‰µ',
  since: 'áŒ€áˆáˆ®',
  totalEntries: 'áŒá‰¤á‰¶á‰½',
  sessions: 'áŠ­ááˆˆ áŒŠá‹œ',
  shareMyStats: 'áˆµá‰³á‰²áˆµá‰²áŠ­áˆ´áŠ• áŠ áŒ‹áˆ« ðŸ“¤',
  copiedToClipboard: 'á‰°á‰€á‹µá‰·áˆ!',
  shopProfile: 'áˆ˜áŒˆáˆˆáŒ«',
  userName: 'áˆµáˆ',
  phoneNumber: 'áˆµáˆáŠ­ á‰áŒ¥áˆ­',
  phoneRequired: 'áˆµáˆáŠ­ á‰áŒ¥áˆ­ á‹«áˆµáˆáˆáŒ‹áˆ',
  phoneInvalid: '9 áŠ áˆƒá‹žá‰½ á‰ 7 á‹ˆá‹­áˆ 9 á‹¨áˆšáŒ€áˆáˆ©',
  telegramLabel: 'á‰´áˆŒáŒáˆ«áˆ / áŒáŠ•áŠ™áŠá‰µ',
  telegramPlaceholder: '@username, t.me/... á‹ˆá‹­áˆ https://t.me/...',
  connectTelegram: 'á‰´áˆŒáŒáˆ«áˆ áŠ áŒˆáŠ“áŠ',
  manageTelegram: 'á‰´áˆŒáŒáˆ«áˆ áŠ áˆµá‰°á‹³á‹µáˆ­',
  telegramConnection: 'á‹¨á‰´áˆŒáŒáˆ«áˆ áŒáŠ•áŠ™áŠá‰µ',
  telegramConnectHint: 'áŠ áŠ•á‹µ áŒŠá‹œ á‰´áˆŒáŒáˆ«áˆ á‹«áŒˆáŠ“áŠ™á£ áŠ¨á‹šá‹« áˆ²áˆáˆáŒ‰ á‹¨á‰€áˆª áˆ‚áˆ³á‰¥ áˆ›áˆ³á‹ˆá‰‚á‹« á‹«á‰¥áˆ©á¢',
  telegramConnectedHint: 'á‹­áˆ… á‹°áŠ•á‰ áŠ› á‰ á‰´áˆŒáŒáˆ«áˆ á‹¨á‰€áˆª áˆ‚áˆ³á‰¥ áˆ˜áˆáŠ¥áŠ­á‰µ áˆŠá‹°áˆ­áˆ°á‹ á‹­á‰½áˆ‹áˆá¢',
  notifyOnTelegram: 'á‰ á‰´áˆŒáŒáˆ«áˆ áŠ áˆ³á‹á‰…',
  notifyOnTelegramHint: 'á‹±á‰¤ á‹ˆá‹­áˆ áŠ­áá‹« áŠ¨á‰°áˆ˜á‹˜áŒˆá‰  á‰ áŠ‹áˆ‹ á‰´áˆŒáŒáˆ«áˆ áˆ«áˆ±áŠ• á‹­áŠ¨áá‰³áˆá¢',
  telegramNotifyEnabledState: 'áˆˆá‹šáˆ… á‹°áŠ•á‰ áŠ› áˆ«áˆµ-áˆ°áˆ­ á‹¨á‰´áˆŒáŒáˆ«áˆ áˆ˜áŠ­áˆá‰µ áŠá‰…á‰·áˆá¢',
  telegramNotifyDisabledState: 'á‰´áˆŒáŒáˆ«áˆ áŠ áˆ›áˆ«áŒ­ á‰¥á‰» áŠá‹á£ áˆ«áˆ±áŠ• áŠ á‹­áŠ¨áá‰µáˆá¢',
  telegramNeedContactHint: 'áˆ˜áŒ€áˆ˜áˆªá‹« á‹¨á‰´áˆŒáŒáˆ«áˆ áˆµáˆ á‹ˆá‹­áˆ áˆŠáŠ•áŠ­ á‹«áˆµáŒˆá‰¡á£ áŠ¨á‹šá‹« áˆ›áˆ³á‹ˆá‰‚á‹«á‹áŠ• á‹«á‰¥áˆ©á¢',
  telegramFormatHint: '@username, t.me/... á‹ˆá‹­áˆ https://t.me/... á‰¥á‰» á‹­áŒ á‰€áˆ™á¢',
  telegramAutoUpdatesTitle: 'áˆ«áˆµ-áˆ°áˆ­ á‹¨á‰€áˆª áˆ‚áˆ³á‰¥ áˆ›áˆ³á‹ˆá‰‚á‹«',
  telegramAutoUpdatesBody: 'áŠ¨á‰°áŒˆáŠ“áŠ˜ á‰ áŠ‹áˆ‹ á‹¨á‹šáˆ… á‹°áŠ•á‰ áŠ› á‰€áˆª áˆ‚áˆ³á‰¥ áˆ²á‰€á‹¨áˆ­ á‰ á‰´áˆŒáŒáˆ«áˆ áˆ˜áˆáŠ¥áŠ­á‰µ áˆŠá‹°áˆ­áˆµáˆˆá‰µ á‹­á‰½áˆ‹áˆá¢',
  qrPrimaryMethod: 'QR áŠ®á‹µ',
  telegramQrHint: 'á‹­áˆ…áŠ• QR áŠ®á‹µ áŠ¥áŠ•á‹²áˆµáŠ«áŠ• áŠ á‹µáˆ­áŒ‰á‰µ áŠ¥áŠ“ á‹¨á‰´áˆŒáŒáˆ«áˆ áŒáŠ•áŠ™áŠá‰µ áˆŠáŠ•áŠ©áŠ• á‹­áŠ­áˆá‰µá¢',
  shareInviteLink: 'á‹¨áŒá‰¥á‹£ áˆŠáŠ•áŠ­ áŠ áŒ‹áˆ«',
  shareInviteLinkHint: 'á‹­áˆ…áŠ• áˆŠáŠ•áŠ­ á‰…á‹³ áŠ¥áŠ“ á‰ áˆšáŒ á‰€áˆ™á‰ á‰µ áˆ›áŠ•áŠ›á‹áˆ áˆ˜áŠ•áŒˆá‹µ áˆ‹áŠ­á¢',
  copyLink: 'áˆŠáŠ•áŠ­ á‰…á‹³',
  inviteLinkCopied: 'á‹¨áŒá‰¥á‹£ áˆŠáŠ•áŠ­ á‰°á‰€á‹µá‰·áˆ',
  copyFailed: 'áˆŠáŠ•áŠ©áŠ• áˆ˜á‰…á‹³á‰µ áŠ áˆá‰°á‰»áˆˆáˆ',
  manualTelegramFallback: 'á‰ áŠ¥áŒ… áˆ›áˆµáŒˆá‰£á‰µ',
  manualTelegramFallbackHint: 'áŠ«áˆµáˆáˆˆáŒˆ á‹¨á‹°áŠ•á‰ áŠ›á‹áŠ• @username á‹ˆá‹­áˆ t.me áˆŠáŠ•áŠ­ á‰ áŠ¥áŒ… á‹«áˆµáŒˆá‰¡á¢',
  confirmConnection: 'áŒáŠ•áŠ™áŠá‰±áŠ• áŠ áˆ¨áŒ‹áŒáŒ¥',
  skipForNow: 'áˆˆáŠ áˆáŠ• á‹áˆˆáˆ',
  saveChanges: 'áˆˆá‹áŒ¦á‰½áŠ• áŠ áˆµá‰€áˆáŒ¥',
  saved: 'á‰°á‰€áˆáŒ§áˆ!',
  privacy: 'áŒáˆ‹á‹ŠáŠá‰µ',
  hideAmounts: 'á‰áŒ¥áˆ®á‰½áŠ• á‹°á‰¥á‰…',
  totalsHidden: 'áŒ á‰…áˆ‹áˆ‹á‹Žá‰¹ á‰°á‹°á‰¥á‰€á‹‹áˆ â€” áˆˆáˆ›áˆ³á‹¨á‰µ á‰°áŒ­áŠ‘',
  totalsVisible: 'áŒ á‰…áˆ‹áˆ‹á‹Žá‰¹ á‹­á‰³á‹«áˆ‰ â€” áˆˆáˆ˜á‹°á‰ á‰… á‰°áŒ­áŠ‘',
  paymentMethods: 'á‹¨áŠ­áá‹« á‹˜á‹´á‹Žá‰½',
  banks: 'á‰£áŠ•áŠ®á‰½',
  mobileWallets: 'áˆžá‰£á‹­áˆ á‹‹áˆŒá‰µ',
  onlyEnabled: 'á‹¨áŠá‰ á‹˜á‹´á‹Žá‰½ á‰¥á‰» á‰ á‰…áŒ¹ á‹áˆµáŒ¥ á‹­á‰³á‹«áˆ‰',
  recurringExpenses: 'á‰°á‹°áŒ‹áŒ‹áˆš á‹ˆáŒªá‹Žá‰½',
  recurringHint: 'á‰¥á‹™ áŒŠá‹œ áˆˆáˆšá‹«áˆµáŒˆá‰¡á‹‹á‰¸á‹ á‹ˆáŒªá‹Žá‰½ áˆáŒ£áŠ• á‰…áŒ½',
  addRecurring: 'á‰°á‹°áŒ‹áŒ‹áˆš á‹ˆáŒª áŠ áŠ­áˆ',
  demoCardSectionLabel: 'áˆáŒ£áŠ• áˆ™áˆ‹ (áˆáˆ³áˆŒá‹Žá‰½)',
  addRecurringPopupGuide: 'á‹­áˆ…áŠ• á‹ˆáŒª áˆˆáˆšá‰€áŒ¥áˆ‰ áŒŠá‹œá‹«á‰µ áŠ áˆµá‰€áˆáŒ¥',
  addAndUse: 'áŠ áˆµá‰€áˆáŒ¥ & á‰°áŒ á‰€áˆ',
  addRecurringHint: 'áˆŒáˆŽá‰½ á‰°á‹°áŒ‹áŒ‹áˆš á‹ˆáŒªá‹Žá‰½áŠ• á‰ á‰…áŠ•á‰¥áˆ®á‰½ á‹áˆµáŒ¥ áˆ›áŠ¨áˆ á‹­á‰½áˆ‹áˆ‰',
  frequency: 'á‹µáŒáŒáˆžáˆ½',
  cancel: 'áˆ°áˆ­á‹',
  add: 'áŠ áŠ­áˆ',
  yourData: 'á‹«áŠ•á‹Ž á‹áˆ‚á‰¥',
  storedOnDevice: 'á‰ á‹šáˆ… áˆµáˆáŠ­ áˆ‹á‹­ á‰°á‰€áˆáŒ§áˆ',
  exportCSV: 'CSV á‹ˆá‹° á‹áŒ­ áˆ‹áŠ­',
  exportHint: 'áˆ°áŠá‹µ áˆá‰µáŠ¬ á‹«á‹áˆ­á‹±',
  clearAll: 'áˆáˆ‰áŠ•áˆ á‹áˆ‚á‰¥ áŠ áŒ¥á‹',
  clearHint: 'áˆáˆ‰áˆ áŠáŒˆáˆ­ áˆ™áˆ‰ á‰ áˆ™áˆ‰ á‹­áˆ°áˆ¨á‹›áˆ â€” áˆ˜áŒ€áˆ˜áˆªá‹« á‹­áˆáŠ©!',
  about: 'áˆµáˆˆ á•áˆ®áŒáˆ«áˆ™',
  privacyNote: 'á‹áˆ‚á‰¡ áŠ¨á‹šáˆ… áˆµáˆáŠ­ áŠ á‹­á‹ˆáŒ£áˆá¢ áˆá‹áŒˆá‰£ áŠ á‹«áˆµáˆáˆáŒáˆá¢',
  worksOffline: 'á‹«áˆˆ áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹­áˆ°áˆ«áˆ Â· á‹áˆ‚á‰¡ á‰ áˆµáˆáŠ­á‹Ž áˆ‹á‹­ á‹­á‰†á‹«áˆ Â· áŠáƒ',
  achievementBadges: 'á‹¨áˆµáŠ¬á‰µ á‰£áŒ†á‰½',
  badgesEarned: 'á‰°áŒˆáŠá‰·áˆ',
  noBadges: 'á‰£áŒ†á‰½ áˆˆáˆ›áŒáŠ˜á‰µ áŠ¢áˆ‹áˆ›á‹Žá‰¹áŠ• á‹«áˆŸáˆ‰!',
  clearConfirm: 'áˆáˆ‰áŠ•áˆ á‹áˆ‚á‰¥ áŠ áŒ¥á‹?',
  clearConfirmMsg: 'á‹­áˆ… áˆáˆ‰áŠ• {count} áŒá‰¤á‰¶á‰½áŠ“ {credits} á‹¨á‹±á‰¤ áˆ˜á‹áŒˆá‰¦á‰½áŠ• áˆ™áˆ‰ á‰ áˆ™áˆ‰ á‹­áˆ°áˆ­á‹›áˆá¢ áˆŠá‰€áˆˆá‰ áˆµ áŠ á‹­á‰½áˆáˆá¢',
  yesDelete: 'áŠ á‹Žá£ áˆáˆ‰áŠ•áˆ áˆ°áˆ­á‹',
  dataCleared: 'á‹áˆ‚á‰¡ á‰°áˆ°áˆ­á‹Ÿáˆ',
  reloading: 'áŠ¥áŠ•á‹°áŒˆáŠ“ áŠ¥á‹¨áŒ«áŠâ€¦',
  deleteEntry: 'á‹­áˆ…áŠ• áŒá‰¤á‰µ á‰µáˆ°áˆ­á‹›áˆˆáˆ…?',
  delete: 'áˆ°áˆ­á‹',
  newBestDay: 'ðŸ† áŠ á‹²áˆµ áˆáˆ­áŒ¥ á‰€áŠ•!',
  birr: 'á‰¥áˆ­',
  daily: 'á‹•áˆˆá‰³á‹Š',
  weekly: 'áˆ³áˆáŠ•á‰³á‹Š',
  monthly: 'á‹ˆáˆ­áˆƒá‹Š',
  expenseName: 'á‹¨á‹ˆáŒª áˆµáˆ (áˆˆáˆáˆ³áˆŒ áŠªáˆ«á‹­)',
  amount: 'áˆ˜áŒ áŠ•',
  sun: 'áŠ¥áˆá‹µ', mon: 'áˆ°áŠž', tue: 'áˆ›áŠ­áˆ°', wed: 'áˆ¨á‰¡á‹•', thu: 'áˆáˆ™áˆµ', fri: 'áŠ áˆ­á‰¥', sat: 'á‰…á‹³áˆœ',

  onboardWelcome: 'ማስታወሻዎን ጀምር',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'ስምዎን ያስገቡና ገበያን ወዲያው ይጀምሩ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(አማራጭ)',
  onboardPhoneHelper: 'ስልክዎን በቅንብሮች ውስጥ በኋላ ማከል ይችላሉ።',
  onboardPromiseSimple: 'ለሽያጭ፣ ወጪ እና ዱቤ ቀላል ማስታወሻ',
  onboardPromiseFast: 'በስምዎ ብቻ ይጀምሩ',
  onboardPromisePrivate: 'መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ',
  onboardGetStarted: 'ገበያን ጀምር',
  onboardSettingUp: 'በማዘጋጀት ላይ…',
  onboardFooter: 'ውሂቡ በስልክዎ ላይ ይቆያል · ምዝገባ አያስፈልግም · ነፃ',

  iSoldSomething: 'áˆ¸áŒ áˆ',
  iSpentSomething: 'á‹ˆáŒª',
  recordCredit: 'á‹±á‰¤ áˆ˜á‹áŒá‰¥',
  addCredit: 'á‹±á‰¤ áŒ¨áˆáˆ­',
  addCustomer: 'á‹°áŠ•á‰ áŠ› áŒ¨áˆáˆ­',
  saveCustomer: 'á‹°áŠ•á‰ áŠ› áŠ áˆµá‰€áˆáŒ¥',
  customerSaved: 'á‹°áŠ•á‰ áŠ› á‰°á‰€áˆáŒ§áˆ',
  customerSaveFailed: 'á‹°áŠ•á‰ áŠ›á‹áŠ• áˆ›áˆµá‰€áˆ˜áŒ¥ áŠ áˆá‰°á‰»áˆˆáˆá¢ áŠ¥á‰£áŠ­á‹Ž á‹°áŒáˆ˜á‹ á‹­áˆžáŠ­áˆ©á¢',
  customerHelperText: 'á‰ áŠ‹áˆ‹ á‹¨áˆšá‹«áˆµá‰³á‹áˆ±á‰µáŠ• áˆ›áŠ•áŠ›á‹áŠ•áˆ áˆ˜áˆˆá‹« á‹­áŒ á‰€áˆ™á¢',
  customerIdentifier: 'á‹¨á‹°áŠ•á‰ áŠ› áˆ˜áˆˆá‹«',
  customerIdentifierPlaceholder: 'áˆµáˆá£ á‰…áŒ½áˆá£ á‹áˆá‹µáŠ“á£ á‰¦á‰³ á‹ˆá‹­áˆ á‹¨áˆ˜áŠªáŠ“ áˆáˆáŠ­á‰µ',
  customerNotePlaceholder: 'á‹­áˆ…áŠ• á‹°áŠ•á‰ áŠ› áˆˆáˆ›áˆµá‰³á‹ˆáˆµ á‹¨áˆšáˆ¨á‹³ áˆ›áŠ•áŠ›á‹áˆ áˆ›áˆµá‰³á‹ˆáˆ»',
  customerPhoneOptional: 'áˆµáˆáŠ­ (áŠ áˆ›áˆ«áŒ­)',
  customerPhonePlaceholder: 'áˆµáˆáŠ­ á‰áŒ¥áˆ­',
  customerTelegramOptional: 'á‰´áˆŒáŒáˆ«áˆ (áŠ áˆ›áˆ«áŒ­)',
  customerTelegramPlaceholder: '@username, t.me/... á‹ˆá‹­áˆ https://t.me/...',
  customerTotalBalance: 'áŒ á‰…áˆ‹áˆ‹ á‰€áˆª áˆ‚áˆ³á‰¥',
  customerBalance: 'á‰€áˆª áˆ‚áˆ³á‰¥',
  searchCustomerPlaceholder: 'á‹°áŠ•á‰ áŠ› á‹ˆá‹­áˆ áˆ›áˆµá‰³á‹ˆáˆ» áˆáˆáŒ...',
  customerSearchHint: 'á‰ áˆµáˆá£ á‰ áˆ›áˆµá‰³á‹ˆáˆ»á£ á‰ áˆµáˆáŠ­ á‹ˆá‹­áˆ á‰ á‰´áˆŒáŒáˆ«áˆ áˆáˆáŒ‰á¢',
  customerSearchResults: 'áŠ¨ {total} á‹°áŠ•á‰ áŠžá‰½ {shown} á‰³á‹­á‰°á‹‹áˆ',
  noCustomersFound: 'áˆáŠ•áˆ á‹°áŠ•á‰ áŠžá‰½ áŠ áˆá‰°áŒˆáŠ™áˆ',
  noCustomersYet: 'áŒˆáŠ“ áˆáŠ•áˆ á‹°áŠ•á‰ áŠžá‰½ á‹¨áˆ‰áˆ',
  noCustomerSearchResults: 'áŠ¨á‹šáˆ… ááˆˆáŒ‹ áŒ‹áˆ­ á‹¨áˆšá‹›áˆ˜á‹± á‹°áŠ•á‰ áŠžá‰½ áŠ áˆá‰°áŒˆáŠ™áˆ',
  backToCustomers: 'á‹ˆá‹° á‹°áŠ•á‰ áŠžá‰½ á‰°áˆ˜áˆˆáˆµ',
  customerTransactionHistory: 'á‹¨áŒá‰¥á‹­á‰µ á‰³áˆªáŠ­',
  paymentRecordedLabel: 'áŠ­áá‹«',
  creditAddedLabel: 'á‹±á‰¤ á‰°áŒ¨áˆáˆ¯áˆ',
  noTransactionsYet: 'áŠ¥áˆµáŠ«áˆáŠ• áˆáŠ•áˆ áŒá‰¥á‹­á‰µ á‹¨áˆˆáˆ',
  noTransactionsHint: 'á‹­áˆ…áŠ• á‰³áˆªáŠ­ áˆˆáˆ˜áŒ€áˆ˜áˆ­ á‹±á‰¤ áŒ¨áˆáˆ­ á‹ˆá‹­áˆ áŠ­áá‹« áˆ˜á‹áŒá‰¥ á‹­áŒ á‰€áˆ™á¢',
  currentBalance: 'áŠ áˆáŠ• á‹«áˆˆ á‰€áˆª áˆ‚áˆ³á‰¥',
  previousBalance: 'á‹«áˆˆáˆá‹ á‰€áˆª áˆ‚áˆ³á‰¥',
  updatedBalance: 'á‹¨á‰°áˆ»áˆ»áˆˆ á‰€áˆª áˆ‚áˆ³á‰¥',
  currentBalanceHint: 'á‹­áˆ… áŠ á‹²áˆ±áŠ• á‹±á‰¤ áŠ«áˆµá‰€áˆ˜áŒ¡ á‰ áŠ‹áˆ‹ á‹¨áˆšá‰³á‹¨á‹ á‰€áˆª áˆ‚áˆ³á‰¥ áŠá‹á¢',
  remainingBalanceHint: 'á‹­áˆ… áŠ­áá‹«á‹áŠ• áŠ«áˆµá‰€áˆ˜áŒ¡ á‰ áŠ‹áˆ‹ á‹¨áˆšá‰€áˆ¨á‹ á‰€áˆª áˆ‚áˆ³á‰¥ áŠá‹á¢',
  paymentNoteOptional: 'á‹¨áŠ­áá‹« áˆ›áˆµá‰³á‹ˆáˆ» (áŠ áˆ›áˆ«áŒ­)',
  itemNoteOptional: 'á‹¨á‰°á‹ˆáˆ°á‹°á‹ áˆ›áˆµá‰³á‹ˆáˆ» (áŠ áˆ›áˆ«áŒ­)',
  paymentNotePlaceholder: 'áˆµáˆˆá‹šáˆ… áŠ­áá‹« áˆ›áŠ•áŠ›á‹áˆ áˆ›áˆµá‰³á‹ˆáˆ»',
  creditItemPlaceholder: 'á‹¨á‹ˆáˆ°á‹±á‰µ áˆáŠ•á‹µáŠ• áŠá‹',
  dueDateOptional: 'á‹¨áˆ˜áŠ­áˆá‹« á‰€áŠ• (áŠ áˆ›áˆ«áŒ­)',
  ethiopianDisplay: 'á‰ áŠ¢á‰µá‹®áŒµá‹« á‰€áŠ• áˆ˜á‰áŒ áˆªá‹«',
  pickDateWithEthiopianHint: 'á‰€áŠ• á‹­áˆáˆ¨áŒ¡á£ áŠ¥áŠ›áˆ á‰ áŠ¢á‰µá‹®áŒµá‹« á‰€áŠ• áˆ˜á‰áŒ áˆªá‹« áŠ¥áŠ“áˆ³á‹«áˆˆáŠ•á¢',
  moreOptional: 'á‰°áŒ¨áˆ›áˆª (áŠ áˆ›áˆ«áŒ­)',
  noteLabel: 'áˆ›áˆµá‰³á‹ˆáˆ»',
  savePayment: 'áŠ­áá‹« áŠ áˆµá‰€áˆáŒ¥',
  customerNotFound: 'á‹°áŠ•á‰ áŠ›á‹ áŠ áˆá‰°áŒˆáŠ˜áˆ',
  validAmountRequired: 'á‰µáŠ­áŠ­áˆˆáŠ› áˆ˜áŒ áŠ• á‹«áˆµáŒˆá‰¡',
  paymentMoreThanBalance: 'áŠ­áá‹«á‹ áŠ¨áŠ áˆáŠ‘ á‰€áˆª áˆ‚áˆ³á‰¥ á‹­á‰ áˆáŒ£áˆ',
  noBalanceToRecordPayment: 'áŒˆáŠ“ á‹¨áˆšáˆ°á‰ áˆ°á‰¥ á‰€áˆª áˆ‚áˆ³á‰¥ á‹¨áˆˆáˆ',
  balanceAfterEntry: 'áŠ¨á‹šáˆ… áŒá‰¤á‰µ á‰ áŠ‹áˆ‹ á‹«áˆˆ á‰€áˆª áˆ‚áˆ³á‰¥',
  dueLabelShort: 'áˆ˜áŠ­áˆá‹«',
  whatDidYouSell: 'áˆáŠ• áˆ¸áŒ¡?',
  sellPlaceholder: 'áˆˆáˆáˆ³áˆŒ á‹³á‰¦á£ áˆµáŠ³áˆ­â€¦',
  whatDidYouSpendOn: 'áˆáŠ• áˆ‹á‹­ á‹ˆáŒª?',
  spendPlaceholder: 'áˆˆáˆáˆ³áˆŒ á‰µáˆ«áŠ•áˆµá–áˆ­á‰µá£ áŠªáˆ«á‹­â€¦',
  creditNameLabel: 'áˆµáˆ',
  creditNamePlaceholder: 'áˆˆáˆáˆ³áˆŒ áŠ á‰ á‰ â€¦',
  howMuchTotal: 'áŒ á‰…áˆ‹áˆ‹ áˆµáŠ•á‰µ?',
  saveSale: 'áˆ½á‹«áŒ­ áŠ áˆµá‰€áˆáŒ¥',
  saveExpense: 'á‹ˆáŒª áŠ áˆµá‰€áˆáŒ¥',
  saveCredit: 'á‹±á‰¤ áŠ áˆµá‰€áˆáŒ¥',
  addAnotherSale: 'áˆŒáˆ‹ áˆ½á‹«áŒ­ áŠ áŠ­áˆ',
  addAnotherExpense: 'áˆŒáˆ‹ á‹ˆáŒª áŠ áŠ­áˆ',
  done: 'á‰°áŒ áŠ“á‰€á‰€',
  birrSaved: 'á‰¥áˆ­ á‰°á‰€áˆáŒ§áˆ',
  howMany: 'áˆµáŠ•á‰µ?',
  direction: 'áŠ á‰…áŒ£áŒ«',
  theyOweMe: 'á‹«á‰ á‹°áˆ­áŠ©á‰µ',
  iOweThem: 'á‹¨á‰°á‰ á‹°áˆ­áŠ©á‰µ',
  owesMe: 'á‹«á‰ á‹°áˆ­áŠ©á‰µ',
  iOweLabel: 'á‹¨á‰°á‰ á‹°áˆ­áŠ©á‰µ',
  quickFill: 'áˆáŒ£áŠ• áˆ™áˆ‹',
  phoneOptional: 'áˆµáˆáŠ­ á‰áŒ¥áˆ­',
  phoneOptionalHint: '(áˆáˆ­áŒ«)',
  phonePlaceholder: 'áˆˆáˆáˆ³áˆŒ 0912345678',
  whenDue: 'áˆ˜á‰¼ á‹­áŠ¨áˆáˆ‹áˆ?',
  pickDate: 'á‰€áŠ• áˆáˆ¨áŒ¥',
  selectDueDate: 'á‹¨áŠ­áá‹« á‰€áŠ• á‹­áˆáˆ¨áŒ¡',
  advancedOptional: 'á‰°áŒ¨áˆ›áˆª (áˆáˆ­áŒ«)',
  whatDidYouPay: 'áˆˆá‹šáˆ… áˆáŠ• áŠ¨áˆáˆ‰?',
  perUnit: '(á‰ áŠ áŠ•á‹µ)',
  helpsSeeProfit: 'áˆáˆ­áŒ« â€” á‰µáŠ­áŠ­áˆˆáŠ›á‹áŠ• á‰µáˆ­á áˆˆáˆ›á‹¨á‰µ á‹­áˆ¨á‹³áˆ',
  sellingBelowCost: 'áŠ¨á‹‹áŒ‹ á‰ á‰³á‰½ áŠ¥á‹¨áˆ¸áŒ¡ áŠá‹á¢ áŠªáˆ³áˆ« áˆŠá‹°áˆ­áˆµ á‹­á‰½áˆ‹áˆá¢',
  profitOnSale: 'á‰ á‹šáˆ… áˆ½á‹«áŒ­ á‰µáˆ­á:',
  paymentType: 'á‹¨áŠ­áá‹« áŠ á‹­áŠá‰µ',
  cash: 'áŒ¥áˆ¬ áŒˆáŠ•á‹˜á‰¥',
  bank: 'á‰£áŠ•áŠ­',
  wallet: 'á‹‹áˆŒá‰µ',

  editSale: 'áˆ½á‹«áŒ­ áŠ áˆµá‰°áŠ«áŠ­áˆ',
  editExpense: 'á‹ˆáŒª áŠ áˆµá‰°áŠ«áŠ­áˆ',
  editCredit: 'á‹±á‰¤ áŠ áˆµá‰°áŠ«áŠ­áˆ',
  editEntryLabel: 'áŒá‰¤á‰µ áŠ áˆµá‰°áŠ«áŠ­áˆ',
  editedAt: 'á‰°áˆµá‰°áŠ«áŠ­áˆáˆ',
  item: 'á‹•á‰ƒ',
  quantity: 'á‰¥á‹›á‰µ',
  dueDate: 'á‹¨áŠ­áá‹« á‰€áŠ•',
  costPriceLabel: 'á‹¨á‹‹áŒ‹',
  sellingBelowCostShort: 'áŠ¨á‹‹áŒ‹ á‰ á‰³á‰½á¢',
  profitLabel: 'á‰µáˆ­á:',
  saving: 'áŠ¥á‹¨á‰°á‰€áˆ˜áŒ â€¦',

  todaysProfit: 'á‹¨á‹›áˆ¬ á‰µáˆ­á',
  estimatedProfit: 'á‹¨á‰°á‰€áˆ˜áŒ  á‰µáˆ­á',
  partialCostDisclaimer: 'áŠ áŠ•á‹³áŠ•á‹µ á‹•á‰ƒá‹Žá‰½ á‹¨á‹‹áŒ‹ áˆ˜áˆ¨áŒƒ áŒŽá‹µáˆá‰¸á‹‹áˆ â€” á‹­áˆ… áŒáˆá‰µ áŠ¨á‰µáŠ­áŠ­áˆˆáŠ›á‹ á‰µáˆ­á á‹«áŠáˆ° áˆŠáˆ†áŠ• á‹­á‰½áˆ‹áˆ',
  partialCostTip: 'á‰µáŠ­áŠ­áˆˆáŠ› á‰µáˆ­á áˆˆáˆ›á‹¨á‰µ áˆˆá‹•á‰ƒá‹Žá‰¹ á‹¨á‹‹áŒ‹ á‹«áˆµáŒˆá‰¡',
  todaysSales: 'á‹¨á‹›áˆ¬ áˆ½á‹«áŒ­',
  salesLabel: 'áˆ½á‹«áŒ­',
  expenses: 'á‹ˆáŒªá‹Žá‰½',
  costOfGoods: 'á‹¨á‹•á‰ƒ á‹‹áŒ‹',
  netProfit: 'áŠ•áŒ¹áˆ… á‰µáˆ­á',
  advancedHint: 'á‰µáŠ­áŠ­áˆˆáŠ›á‹áŠ• á‰µáˆ­á áˆˆáˆ›á‹¨á‰µ áˆ½á‹«áŒ­ áˆ²áˆ˜á‹˜áŒá‰¡ "á‰°áŒ¨áˆ›áˆª" á‰°áŒ­áŠ‘',

  tapToReveal: 'áˆˆáˆ›áˆ³á‹¨á‰µ á‰°áŒ­áŠ‘',
  tapToRevealAria: 'áˆ˜áŒ áŠ•áŠ• áˆˆáˆ›áˆ³á‹¨á‰µ á‰°áŒ­áŠ‘',
  hideAmountAria: 'áˆ˜áŒ áŠ•áŠ• á‹°á‰¥á‰…',

  byDay: 'á‰ á‰€áŠ•',
  byWeek: 'á‰ áˆ³áˆáŠ•á‰µ',
  groupBy: 'á‰¡á‹µáŠ•:',
  searchPlaceholder: 'á‰ á‹•á‰ƒ á‹ˆá‹­áˆ á‹°áŠ•á‰ áŠ› áˆáˆáŒâ€¦',
  noSearchResults: 'áˆáŠ•áˆ á‹áŒ¤á‰µ',
  noRecords: 'áŠ¥áˆµáŠ«áˆáŠ• áˆáŠ•áˆ áˆ˜á‹áŒˆá‰¥ á‹¨áˆˆáˆ',
  startRecording: 'áˆˆáˆ˜áŒ€áˆ˜áˆ­ á‹¨áˆ˜áŒ€áˆ˜áˆªá‹« áˆ½á‹«áŒ­ á‹ˆá‹­áˆ á‹ˆáŒª á‹­áˆ˜á‹áŒá‰¡',
  entries: 'áŒá‰¤á‰¶á‰½',
  revenue: 'áŒˆá‰¢',
  thisWeek: 'á‹­áˆ… áˆ³áˆáŠ•á‰µ',

  noCreditRecords: 'á‹¨á‹±á‰¤ áˆ˜á‹áŒˆá‰¥ á‹¨áˆˆáˆ',
  addCreditHint: 'á‹±á‰¤ áˆˆáˆ›áŠ­áˆ á‰ á‹›áˆ¬ áŒˆáŒ½ áˆ‹á‹­ "á‹±á‰¤" á‰°áŒ­áŠ‘',
  owedToMe: 'á‹«á‰ á‹°áˆ­áŠ©á‰µ',
  iOweAmount: 'á‹¨á‰°á‰ á‹°áˆ­áŠ©á‰µ',
  active: 'áŠ•á‰',
  paid: 'á‹¨á‰°áŠ¨áˆáˆˆ',
  activeTab: 'áŠ•á‰',
  paidTab: 'á‹¨á‰°áŠ¨áˆáˆˆ',
  noPaidRecords: 'áŠ¥áˆµáŠ«áˆáŠ• á‹¨á‰°áŠ¨áˆáˆˆ áˆ˜á‹áŒˆá‰¥ á‹¨áˆˆáˆ',
  allCaughtUp: 'áˆáˆ‰áˆ á‰°áŠ¨ááˆáˆ!',
  paidInFull: 'áˆ™áˆ‰ á‰°áŠ¨ááˆáˆ',
  paidLabel: 'á‰°áŠ¨ááˆáˆ',
  due: 'áŠ­áá‹«',
  owesMeLabel: 'á‹«á‰ á‹°áˆ­áŠ©á‰µ',
  iOweTag: 'á‹¨á‰°á‰ á‹°áˆ­áŠ©á‰µ',

  backToCredit: 'á‹ˆá‹° á‹±á‰¤ á‰°áˆ˜áˆˆáˆµ',
  originalDebt: 'á‹‹áŠ“ á‹•á‹³',
  amountPaid: 'á‹¨á‰°áŠ¨áˆáˆˆ',
  stillOwes: 'á‰€áˆª á‹•á‹³',
  progress: 'áˆ‚á‹°á‰µ',
  percentPaid: '% á‰°áŠ¨ááˆáˆ',
  paidSome: 'áŠ¨áŠáˆ áŠ­áá‹«',
  allPaid: 'áˆ™áˆ‰ á‰°áŠ¨ááˆáˆ',
  call: 'á‹°á‹áˆ',
  recordPartialPayment: 'áŠ¨áŠáˆ áŠ­áá‹« áˆ˜á‹áŒá‰¥',
  recordPayment: 'áŠ­áá‹« áˆ˜á‹áŒá‰¥',
  markFullyPaid: 'áˆ™áˆ‰ á‰°áŠ¨ááˆáˆ á‰¥áˆˆáˆ… áˆáˆáŠ­á‰µ áŠ á‹µáˆ­áŒ',
  paymentHistory: 'á‹¨áŠ­áá‹« á‰³áˆªáŠ­',
  borrowed: 'á‹¨á‰°á‰ á‹°áˆ¨',
  paidBack: 'á‹¨á‰°áˆ˜áˆˆáˆ°',
  remaining: 'á‰€áˆª',
  payMethodCash: 'áŒ¥áˆ¬ áŒˆáŠ•á‹˜á‰¥',
  payMethodBank: 'á‰£áŠ•áŠ­ á‹á‹á‹áˆ­',
  payMethodMobile: 'áˆžá‰£á‹­áˆ áŒˆáŠ•á‹˜á‰¥',
  paymentExceedsOwed: 'áˆ˜áŒ áŠ‘ áŠ¨áˆšáŒˆá‰£á‹ áˆ˜áŒ áŠ• áˆŠá‰ áˆáŒ¥ áŠ á‹­á‰½áˆáˆ',

  voiceNotSupported: 'á‹µáˆáŒ½ áŠ á‹­á‹°áŒˆááˆ â€” á‹¨á‰áˆá áˆ°áˆŒá‹³ á‹­áŒ á‰€áˆ™',
  voiceInput: 'á‹µáˆáŒ½',
  tryAgain: 'áŠ¥áŠ•á‹°áŒˆáŠ“ áˆžáŠ­áˆ­',
  voiceMicBlocked: 'áˆ›á‹­áŠ­áˆ®áŽáŠ‘ á‰³áŒá‹·áˆá¢ á‹¨áŠ áˆ³áˆ½ á‰…áŠ•á‰¥áˆ®á‰½áŠ• á‹­áˆ˜áˆáŠ¨á‰±á¢',

  close: 'á‹áŒ‹',

  todaysBreakdown: 'á‹¨á‹›áˆ¬ áˆ‚áˆ³á‰¥',
  payingVia: 'á‰ ',
  creditPhoneHint: '9 áŠ áˆƒá‹žá‰½á£ áŠ¨7 á‹ˆá‹­áˆ 9 á‹­áŒ€áˆáˆ©',
  addCustomBank: 'á‰£áŠ•áŠ­ áŠ áŠ­áˆâ€¦',
  addCustomWallet: 'á‹‹áˆŒá‰µ áŠ áŠ­áˆâ€¦',
  customProviderName: 'áˆµáˆ',
  providerEnabled: 'áŠá‰‹áˆ',
  providerDisabled: 'á‰°á‹˜áŒá‰·áˆ',

  introSlide1Title: 'á‹¨áˆ±á‰… áˆ›áˆµá‰³á‹ˆáˆ»',
  introSlide1Body: 'áˆ½á‹«áŒ­á£ á‹ˆáŒªá£ á‹±á‰¤ â€” áˆáˆ‰áˆ á‰ áˆµáˆáŠ­á¢ áˆá‹áŒˆá‰£ áŠ á‹«áˆµáˆáˆáŒáˆá¢',
  introSlide2Title: 'áŒˆáŠ•á‹˜á‰¡áŠ• áˆáŒ¥áŠ– á‹­áˆ˜áˆáŠ¨á‰±',
  introSlide2Body: 'á‹¨á‹›áˆ¬ á‰µáˆ­á áˆáˆŒ áŠ¨áˆ‹á‹­ á‹­á‰³á‹«áˆá¢ áˆáŠ”á‰³á‹ŽáŠ• á‰ áˆ°áŠ¨áŠ•á‹¶á‰½ á‹«á‹á‰á¢',
  introSlide3Title: 'áˆ¦áˆµá‰µ á‰áˆáŽá‰½ á‰¥á‰»',
  introSlide3Body: 'áˆ¸áŒ áˆá£ á‹ˆáŒªá£ á‹±á‰¤á¢ áˆ‚á‹°á‰± áˆˆ10 áˆ°áŠ®áŠ•á‹¶á‰½ á‰¥á‰» áŠá‹á¢',
  introLetsStart: 'áŒ€áˆáˆ­ ðŸš€',
  introNext: 'á‰€áŒ£á‹­ â†’',
  introSkip: 'á‹áˆˆáˆ',

  noEntriesPrompt: 'áˆˆáˆ›áˆµá‰€áˆ˜áŒ¥ áŠ¨áˆ‹á‹­ "áˆ¸áŒ áˆ" á‹­áŒ«áŠ‘',

  saleSaved: 'âœ… áˆ½á‹«áŒ¥ á‰°á‰€áˆáŒ§áˆ Â· ðŸ”¥ á‰€áŒ¥áˆáˆ',
  expenseSaved: 'á‹ˆáŒª á‰°á‰€áˆáŒ§áˆ âœ“',
  creditSaved: 'á‹±á‰¤ á‰°á‰€áˆáŒ§áˆ âœ“',
  undone: 'á‰°áˆ°áˆ­á‹Ÿáˆ âœ“',

  statusOverdue: 'á‹˜áŒá‹­á‰·áˆ',
  statusDueSoon: 'á‹­á‰ƒáˆ¨á‰£áˆ',
  statusOk: 'áŒ¥áˆ©',

  periodDay: 'á‰€áŠ•',
  periodWeek: 'áˆ³áˆáŠ•á‰µ',
  periodMonth: 'á‹ˆáˆ­',
  totalSales: 'áŒ á‰…áˆ‹áˆ‹ áˆ½á‹«áŒ­',
  totalExpenses: 'áŒ á‰…áˆ‹áˆ‹ á‹ˆáŒª',
  topProductsWeek: 'á‹¨áˆ³áˆáŠ•á‰± áˆáˆ­áŒ¥ áˆ½á‹«áŒ­',
  topProductsMonth: 'á‹¨á‹ˆáˆ© áˆáˆ­áŒ¥ áˆ½á‹«áŒ­',
  topProductsDay: 'á‹›áˆ¬ áˆáˆ­áŒ¥ áˆ½á‹«áŒ­',
  byQuantity: 'á‰ á‰¥á‹›á‰µ',
  byRevenue: 'á‰ áŒˆá‰¢',
  weekBreakdown: 'á‰ á‰€áŠ•',
  monthBreakdown: 'á‰ áˆ³áˆáŠ•á‰µ',
  weekOf: 'áˆ³áˆáŠ•á‰µ',
  noSalesThisPeriod: 'á‰ á‹šáˆ… á‹ˆá‰…á‰µ áˆ½á‹«áŒ­ á‹¨áˆˆáˆ',
  week: 'áˆ³áˆáŠ•á‰µ',

  recordByVoice: 'áˆ½á‹«áŒ­ áˆˆáˆ›áˆµá‰€áˆáŒ¥ á‹­áŠ“áŒˆáˆ©',
  recordByVoiceSubLabel: 'áˆ½á‹«áŒ¥ áˆˆáˆ›áˆµá‰€áˆáŒ¥ á‰€áˆ‹áˆ‰ áˆ˜áŠ•áŒˆá‹µ',
  typeSale: 'á‰ áŒ½áˆ‘á áˆ¸áŒ¥',
  typeSaleLabel: 'á‰ áŒ½áˆ‘á áˆ¸áŒ¥',
  voiceRecordingTitle: 'áŠ¥á‹¨á‰€á‹³â€¦',
  voiceRecordingHint: 'á‹¨áˆ½á‹«áŒ­ áˆ˜áŒ áŠ• á‹­áŠ“áŒˆáˆ©',
  voiceStop: 'áŠ á‰áˆ',
  voiceTypeInstead: 'á‰ áŒ½áˆ‘á á‹«áˆµáŒˆá‰¡',
  voiceNoInternet: 'á‹¨áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ áŒáŠ•áŠ™áŠá‰µ á‹¨áˆˆáˆ',
  voiceNoInternetHint: 'á‹¨á‹µáˆáŒ½ á‰…á‹³ áŠ¢áŠ•á‰°áˆ­áŠ”á‰µ á‹«áˆµáˆáˆáŒ‹áˆá¢ á‰ áŒ½áˆ‘á áˆ½á‹«áŒ­ áˆ›áˆµá‰€áˆ˜áŒ¥ á‹­á‰½áˆ‹áˆ‰á¢',
  voiceTypeSaleInstead: 'á‰ áŒ½áˆ‘á áˆ¸áŒ¥',
  voiceRetry: 'áŠ¥áŠ•á‹°áŒˆáŠ“ áˆžáŠ­áˆ­',
  voiceTryFinishSoon: 'âš ï¸ áˆˆáˆ˜áŒ¨áˆ¨áˆµ á‰¶áˆŽ á‹­áˆžáŠ­áˆ©',
  voiceResultTitle: 'á‹¨á‹µáˆáŒ½ á‹áŒ¤á‰µ',
  voiceTranscript: 'á‹¨á‰°áŠ“áŒˆáˆ©á‰µ',
  voiceDetectedTotal: 'á‹¨á‰°áŒˆáŠ˜ áŒ á‰…áˆ‹áˆ‹',
  voiceNoAmount: 'áˆ˜áŒ áŠ• áŠ áˆá‰°áŒˆáŠ˜áˆ',
  voiceNeedsReview: 'áŠ¨áˆ›áˆµá‰€áˆ˜áŒ¥ á‰ áŠá‰µ á‹­áˆ…áŠ• áˆ¨á‰‚á‰… á‹­áˆ˜áˆáŠ¨á‰±á¢',
  voiceParsedItems: 'á‹¨á‰°áˆˆá‹© á‹•á‰ƒá‹Žá‰½',
  voiceCustomerName: 'á‹°áŠ•á‰ áŠ›',
  voiceCustomerPlaceholder: 'áŠ¨á‰°áŒ á‰€áˆ° á‹¨á‹°áŠ•á‰ áŠ› áˆµáˆ',
  voiceIntent: 'á‹“á‹­áŠá‰µ',
  voiceIntentSale: 'áˆ½á‹«áŒ­',
  voiceIntentCredit: 'á‹±á‰¤',
  voiceIntentPayment: 'áŠ­áá‹«',
  voiceQuantity: 'á‰¥á‹›á‰µ',
  voiceUnitPrice: 'á‹¨áŠ áŠ•á‹± á‹‹áŒ‹',
  voiceAutoCalculatedTotal: 'áŒ á‰…áˆ‹áˆ‹á‹ áŠ¨á‹•á‰ƒ áˆ˜áˆµáˆ˜áˆ®á‰½ á‰ áˆ«áˆµ-áˆ°áˆ­ á‰°á‰†áŒ¥áˆ¯áˆá¢',
  voiceItemNamePlaceholder: 'á‹¨á‹•á‰ƒ áˆµáˆ',
  voiceSave: 'áˆ½á‹«áŒ­ áŠ áˆµá‰€áˆáŒ¥',
  voiceFix: 'áŠ áˆµá‰°áŠ«áŠ­áˆ',
  voiceReRecord: 'áŠ¥áŠ•á‹°áŒˆáŠ“ á‰…á‹³',
  voiceFixTitle: 'á‹¨á‹µáˆáŒ½ áˆ½á‹«áŒ­ áŠ áˆµá‰°áŠ«áŠ­áˆ',
  voiceTotalLabel: 'áŒ á‰…áˆ‹áˆ‹ áˆ˜áŒ áŠ•',
  voiceNoteLabel: 'áˆ›áˆµá‰³á‹ˆáˆ» (áˆáˆ­áŒ«)',
  voiceNotePlaceholder: 'áˆˆáˆáˆ³áˆŒ á‹³á‰¦á£ áˆµáŠ³áˆ­â€¦',
  voiceSaleSaved: 'á‹¨á‹µáˆáŒ½ áˆ½á‹«áŒ­ á‰°á‰€áˆáŒ§áˆ âœ“',
  voiceAddAnotherItem: 'áˆŒáˆ‹ á‹•á‰ƒ áŠ áŠ­áˆ',
  voiceRunningTotal: 'á‹µáˆáˆ­ áŒ á‰…áˆ‹áˆ‹',
  voiceItemsRecorded: 'á‹•á‰ƒá‹Žá‰½ á‰°á‰€áˆ­áŒ¿áˆ',
};

const EN_OVERRIDES = {
  appName: 'Gebya',
  appearance: 'Appearance',
  appearanceHint: 'Choose the look that feels easiest on your eyes.',
  lightMode: 'Light',
  darkMode: 'Dark',
  today: 'Today',
  todayLabel: 'Today',
  credit: 'Dubie',
  creditLabel: 'Dubie',
  iSold: 'Type Sale',
  iSoldLabel: 'Type Sale',
  iSpent: 'I Spent',
  iSpentLabel: 'I Spent',
  creditBtn: 'Dubie',
  creditBtnLabel: 'Dubie',
  todaysEntries: "Today's Entries",
  onboardTagline: 'Your shop notebook',
  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardDesc: 'Enter your name and start using Gebya right away.',
  onboardPromiseSimple: 'Simple notebook for sales, spending, and Dubie',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'Your records stay on this phone',
  onboardGetStarted: 'Start using Gebya',
  trustCardTitle: 'Your notebook stays on this phone',
  trustCardBody: 'Save your sales, close the app, and open again later. Your records stay here on this phone.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Close and reopen anytime. Your records stay here.',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even with weak connection, and your saved notebook stays on this phone.',
  recordByVoice: 'Speak to Record Sale',
  recordByVoiceSubLabel: 'Fastest way to save a sale',
  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',
};

const AM_OVERRIDES = {
  // Brand & navigation
  appName: 'ገበያ',
  appearance: 'መልክ',
  appearanceHint: 'ለዓይንዎ ቀላል የሚሆነውን መልክ ይምረጡ።',
  lightMode: 'ብርሃን',
  darkMode: 'ጨለማ',
  loading: 'ማስታወሻዎን በመጫን ላይ…',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ዱቤ',
  creditLabel: 'ዱቤ',
  report: 'ሪፖርት',
  settings: 'ቅንብሮች',
  close: 'ዝጋ',
  cancel: 'ሰርዝ',
  add: 'አክል',
  delete: 'ሰርዝ',
  saved: 'ተቀምጧል',
  done: 'ተጠናቀቀ',

  // Today screen totals & summary
  sales: 'ሽያጭ',
  spent: 'ወጪ',
  salesLabel: 'ሽያጭ',
  expenses: 'ወጪዎች',
  totalSales: 'ጠቅላላ ሽያጭ',
  totalExpenses: 'ጠቅላላ ወጪ',
  todaysProfit: 'የዛሬ ትርፍ',
  estimatedProfit: 'የተገመተ ትርፍ',
  todaysSales: 'የዛሬ ሽያጭ',
  todaysBreakdown: 'የዛሬ ሂሳብ',
  todaysEntries: 'የዛሬ ግቤቶች',
  netProfit: 'ንጹህ ትርፍ',
  costOfGoods: 'የእቃ ዋጋ',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  birr: 'ብር',
  birrSaved: 'ብር ተቀምጧል',
  newBestDay: 'አዲስ ምርጥ ቀን!',
  tapToReveal: 'ለማሳየት ይጫኑ',
  tapToRevealAria: 'መጠንን ለማሳየት ይጫኑ',
  hideAmountAria: 'መጠንን ደብቅ',
  totalsHidden: 'ጠቅላላዎቹ ተደብቀዋል — ለማሳየት ይጫኑ',
  totalsVisible: 'ጠቅላላዎቹ ይታያሉ — ለመደበቅ ይጫኑ',
  partialCostDisclaimer: 'አንዳንድ እቃዎች የዋጋ መረጃ ጎድሏቸዋል — ይህ ግምት ከትክክለኛው ትርፍ ያነሰ ሊሆን ይችላል',
  partialCostTip: 'ትክክለኛ ትርፍ ለማየት ለእቃዎቹ የዋጋ ያስገቡ',
  advancedHint: 'ትክክለኛውን ትርፍ ለማየት ሽያጭ ሲመዘግቡ "ተጨማሪ" ይጫኑ',
  weekTrend: 'የ7 ቀን አዝማሚያ',
  thisWeek: 'ይህ ሳምንት',
  topProducts: 'ዛሬ ምርጥ ሽያጭ',
  topProductsWeek: 'የሳምንቱ ምርጥ ሽያጭ',
  topProductsMonth: 'የወሩ ምርጥ ሽያጭ',
  topProductsDay: 'ዛሬ ምርጥ ሽያጭ',
  byQuantity: 'በብዛት',
  byRevenue: 'በገቢ',
  weekBreakdown: 'በቀን',
  monthBreakdown: 'በሳምንት',
  weekOf: 'ሳምንት',
  noSalesThisPeriod: 'በዚህ ወቅት ሽያጭ የለም',
  week: 'ሳምንት',
  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  groupBy: 'ቡድን:',
  revenue: 'ገቢ',
  entries: 'ግቤቶች',

  // Action buttons & types
  iSold: 'ሸጥ',
  iSoldLabel: 'ሸጥ',
  iSpent: 'ወጪ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ዱቤ',
  creditBtnLabel: 'ዱቤ',
  iSoldSomething: 'ሸጥኩ',
  iSpentSomething: 'ወጪ',
  recordCredit: 'ዱቤ መዝግብ',
  saleSaved: 'ሽያጭ ተቀምጧል',
  expenseSaved: 'ወጪ ተቀምጧል',
  creditSaved: 'ዱቤ ተቀምጧል',
  paymentSaved: 'ክፍያ ተቀምጧል',
  undone: 'ተመልሷል',
  saveSale: 'ሽያጭ አስቀምጥ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ዱቤ አስቀምጥ',
  addAnotherSale: 'ሌላ ሽያጭ አክል',
  addAnotherExpense: 'ሌላ ወጪ አክል',
  editSale: 'ሽያጭ አርትዕ',
  editExpense: 'ወጪ አርትዕ',
  editCredit: 'ዱቤ አርትዕ',
  editEntry: 'ግቤት አርትዕ',
  editEntryLabel: 'ግቤት አርትዕ',
  editedAt: 'ተስተካክሏል',
  deleteEntry: 'ይህንን ግቤት ይሰርዙ?',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  saving: 'እየተቀመጠ…',

  // Form labels
  whatDidYouSell: 'ምን ሸጡ?',
  sellPlaceholder: 'ለምሳሌ ዳቦ፣ ስኳር…',
  whatDidYouSpendOn: 'ምን ላይ ወጪ?',
  spendPlaceholder: 'ለምሳሌ ትራንስፖርት፣ ኪራይ…',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ…',
  howMuchTotal: 'ጠቅላላ ስንት?',
  howMany: 'ስንት?',
  direction: 'አቅጣጫ',
  theyOweMe: 'ያበደርኩት',
  iOweThem: 'የተበደርኩት',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'ፈጣን ሙላ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(አማራጭ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ይከፍላል?',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'የመክፍያ ቀን ይምረጡ',
  advancedOptional: 'ተጨማሪ (አማራጭ)',
  whatDidYouPay: 'ለዚህ ምን ከፈሉ?',
  perUnit: '(በአንድ)',
  helpsSeeProfit: 'አማራጭ — ትክክለኛውን ትርፍ ለማየት ይረዳል',
  sellingBelowCost: 'ከዋጋ በታች እየሸጡ ነው። ኪሳራ ሊደርስ ይችላል።',
  sellingBelowCostShort: 'ከዋጋ በታች።',
  profitOnSale: 'በዚህ ሽያጭ ትርፍ:',
  profitLabel: 'ትርፍ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ዋሌት',
  amount: 'መጠን',
  item: 'እቃ',
  quantity: 'ብዛት',
  dueDate: 'የመክፍያ ቀን',
  dueDateOptional: 'የመክፍያ ቀን (አማራጭ)',
  costPriceLabel: 'የዋጋ',
  noteLabel: 'ማስታወሻ',
  paymentNoteOptional: 'የክፍያ ማስታወሻ (አማራጭ)',
  itemNoteOptional: 'የተወሰደው ማስታወሻ (አማራጭ)',
  paymentNotePlaceholder: 'ስለዚህ ክፍያ ማንኛውም ማስታወሻ',
  creditItemPlaceholder: 'የወሰዱት ምንድን ነው',
  pickDateWithEthiopianHint: 'ቀን ይምረጡ፣ እንዲሁም በኢትዮጵያ ቀን መቁጠሪያ እናሳያለን።',
  ethiopianDisplay: 'በኢትዮጵያ ቀን መቁጠሪያ',
  moreOptional: 'ተጨማሪ (አማራጭ)',
  validAmountRequired: 'ትክክለኛ መጠን ያስገቡ',
  creditPhoneHint: '9 አሃዞች፣ ከ7 ወይም 9 ይጀምሩ',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: '9 አሃዞች በ7 ወይም 9 የሚጀምሩ',

  // Credit / Dubie list
  noCreditRecords: 'የዱቤ መዝገብ የለም',
  addCreditHint: 'ዱቤ ለማክል በዛሬ ገጽ ላይ "ዱቤ" ይጫኑ',
  owedToMe: 'ያበደርኩት',
  iOweAmount: 'የተበደርኩት',
  active: 'ንቁ',
  paid: 'የተከፈለ',
  activeTab: 'ንቁ',
  paidTab: 'የተከፈለ',
  noPaidRecords: 'እስካሁን የተከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተከፍሏል!',
  paidInFull: 'ሙሉ በሙሉ ተከፍሏል',
  paidLabel: 'ተከፍሏል',
  due: 'መክፍያ',
  owesMeLabel: 'ያበደርኩት',
  iOweTag: 'የተበደርኩት',
  dueLabelShort: 'መክፍያ',
  backToCredit: 'ወደ ዱቤ ተመለስ',
  originalDebt: 'ዋና ዕዳ',
  amountPaid: 'የተከፈለ',
  stillOwes: 'ቀሪ ዕዳ',
  progress: 'ሂደት',
  percentPaid: '% ተከፍሏል',
  paidSome: 'ከፊል ክፍያ',
  allPaid: 'ሙሉ ተከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  markFullyPaid: 'ሙሉ ተከፍሏል ብለህ አድርግ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'የተበደረ',
  paidBack: 'የተመለሰ',
  remaining: 'ቀሪ',
  payMethodCash: 'ጥሬ ገንዘብ',
  payMethodBank: 'ባንክ ዝውውር',
  payMethodMobile: 'ሞባይል ገንዘብ',
  paymentExceedsOwed: 'መጠኑ ከሚገባው መጠን ሊበልጥ አይችልም',
  paymentMoreThanBalance: 'ክፍያው ከአሁኑ ቀሪ ሂሳብ ይበልጣል',
  noBalanceToRecordPayment: 'ገና የሚሰበሰብ ቀሪ ሂሳብ የለም',
  balanceAfterEntry: 'ከዚህ ግቤት በኋላ ያለ ቀሪ ሂሳብ',
  savePayment: 'ክፍያ አስቀምጥ',
  currentBalance: 'አሁን ያለ ቀሪ ሂሳብ',
  previousBalance: 'ያለፈው ቀሪ ሂሳብ',
  updatedBalance: 'የተሻሻለ ቀሪ ሂሳብ',
  currentBalanceHint: 'ይህ አዲሱን ዱቤ ካስቀመጡ በኋላ የሚታየው ቀሪ ሂሳብ ነው።',
  remainingBalanceHint: 'ይህ ክፍያውን ካስቀመጡ በኋላ የሚቀረው ቀሪ ሂሳብ ነው።',

  // Status badges
  statusOverdue: 'ዘግይቷል',
  statusDueSoon: 'ይቅረባል',
  statusOk: 'ጥሩ',

  // Periods
  periodDay: 'ቀን',
  periodWeek: 'ሳምንት',
  periodMonth: 'ወር',
  daily: 'ዕለታዊ',
  weekly: 'ሳምንታዊ',
  monthly: 'ወርሃዊ',
  sun: 'እሁድ',
  mon: 'ሰኞ',
  tue: 'ማክሰ',
  wed: 'ረቡዕ',
  thu: 'ሐሙስ',
  fri: 'አርብ',
  sat: 'ቅዳሜ',

  // Customer page
  addCustomer: 'ደንበኛ ጨምር',
  saveCustomer: 'ደንበኛ አስቀምጥ',
  customerSaved: 'ደንበኛ ተቀምጧል',
  customerSaveFailed: 'ደንበኛውን ማስቀመጥ አልተቻለም። እባክዎ ድጋሜ ይሞክሩ።',
  customerHelperText: 'በኋላ የሚያስታውሱትን ማንኛውም መለያ ይጠቀሙ።',
  customerIdentifier: 'የደንበኛ መለያ',
  customerIdentifierPlaceholder: 'ስም፣ ቅጽል፣ ዝምድና፣ ቦታ ወይም ምልክት',
  customerNotePlaceholder: 'ይህንን ደንበኛ ለማስታወስ የሚረዳ ማስታወሻ',
  customerPhoneOptional: 'ስልክ (አማራጭ)',
  customerPhonePlaceholder: 'ስልክ ቁጥር',
  customerTelegramOptional: 'ቴሌግራም (አማራጭ)',
  customerTelegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  customerTotalBalance: 'ጠቅላላ ቀሪ ሂሳብ',
  customerBalance: 'ቀሪ ሂሳብ',
  searchCustomerPlaceholder: 'ደንበኛ ወይም ማስታወሻ ፈልግ…',
  customerSearchHint: 'በስም፣ በማስታወሻ፣ በስልክ ወይም በቴሌግራም ይፈልጉ።',
  customerSearchResults: 'ከ {total} ደንበኞች {shown} ታይተዋል',
  noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
  noCustomersYet: 'ገና ምንም ደንበኞች የሉም',
  noCustomerSearchResults: 'ከዚህ ፍለጋ ጋር የሚዛመዱ ደንበኞች አልተገኙም',
  backToCustomers: 'ወደ ደንበኞች ተመለስ',
  customerTransactionHistory: 'የግብይት ታሪክ',
  paymentRecordedLabel: 'ክፍያ',
  creditAddedLabel: 'ዱቤ ተጨምሯል',
  noTransactionsYet: 'እስካሁን ምንም ግብይት የለም',
  noTransactionsHint: 'ይህንን ታሪክ ለመጀመር ዱቤ ጨምር ወይም ክፍያ መዝግብ ይጠቀሙ።',
  customerNotFound: 'ደንበኛው አልተገኘም',

  // Search & filters
  searchPlaceholder: 'በእቃ ወይም ደንበኛ ፈልግ…',
  noSearchResults: 'ምንም ውጤት',
  noRecords: 'እስካሁን ምንም መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያ ሽያጭ ወይም ወጪ ይመዝግቡ',
  noEntries: 'ገና ምንም ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ይጫኑ።',
  noEntriesPrompt: 'የመጀመሪያ ሽያጭዎን ለማስቀመጥ ከላይ ያለውን ቁልፍ ይጫኑ',

  // Settings
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  privacy: 'ግላዊነት',
  hideAmounts: 'ቁጥሮችን ደብቅ',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ዋሌት',
  onlyEnabled: 'የነቁ ዘዴዎች ብቻ በቅጹ ውስጥ ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለሚያስገቡዋቸው ወጪዎች ፈጣን ቅጽ',
  addRecurring: 'ተደጋጋሚ ወጪ አክል',
  demoCardSectionLabel: 'ፈጣን ሙላ (ምሳሌዎች)',
  addRecurringPopupGuide: 'ይህን ወጪ ለሚቀጥሉ ጊዜያት አስቀምጥ',
  addAndUse: 'አስቀምጥ እና ተጠቀም',
  addRecurringHint: 'ሌሎች ተደጋጋሚ ወጪዎችን በቅንብሮች ውስጥ ማከል ይችላሉ',
  frequency: 'ድግግሞሽ',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  yourData: 'የእርስዎ ውሂብ',
  storedOnDevice: 'በዚህ ስልክ ላይ ተቀምጧል',
  exportCSV: 'CSV ወደ ውጭ ላክ',
  exportHint: 'ስፕሬድሺት ምትኬ ያውርዱ',
  clearAll: 'ሁሉንም ውሂብ አጥፋ',
  clearHint: 'ሁሉም ነገር ሙሉ በሙሉ ይሰረዛል — መጀመሪያ ይልኩ!',
  about: 'ስለ ፕሮግራሙ',
  privacyNote: 'ውሂቡ ከዚህ ስልክ አይወጣም። ምዝገባ አያስፈልግም።',
  worksOffline: 'ከኢንተርኔት ውጪም ይሰራል · ውሂቡ በስልክዎ ላይ ይቆያል · ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ተገኝቷል',
  noBadges: 'ባጆች ለማግኘት ኢላማዎችን ያሟሉ!',
  clearConfirm: 'ሁሉንም ውሂብ አጥፋ?',
  clearConfirmMsg: 'ይህ ሁሉን {count} ግቤቶችና {credits} የዱቤ መዝገቦችን ሙሉ በሙሉ ይሰርዛል። ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ፣ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂቡ ተሰርዟል',
  reloading: 'እንደገና በመጫን ላይ…',
  saveChanges: 'ለውጦችን አስቀምጥ',
  copiedToClipboard: 'ወደ ቅጂ ተገልብጧል',
  shareMyStats: 'ስታቲስቲክስን አጋራ',
  usageInsights: 'የአጠቃቀም ዝርዝር',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ጀምሮ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍለ ጊዜ',
  newBestDay: 'አዲስ ምርጥ ቀን',

  // Share
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'ዛሬን አጋራ',
  shareTitle: 'ዕለታዊ ሪፖርት አጋራ',
  shareDailyReport: 'ዕለታዊ ሪፖርት',
  shareTopItems: 'ምርጥ ሽያጭ',
  shareSentVia: 'በ ገበያ (Gebya) ተልኳል',
  shareViaDevice: 'በስልክ አጋራ',
  openTelegram: 'ቴሌግራም ክፈት',
  copyText: 'ጽሑፍ ቅዳ',

  // Telegram
  telegramLabel: 'ቴሌግራም / ግንኙነት',
  telegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  connectTelegram: 'ቴሌግራም አገናኝ',
  manageTelegram: 'ቴሌግራም አስተዳድር',
  telegramConnection: 'የቴሌግራም ግንኙነት',
  telegramConnectHint: 'አንድ ጊዜ ቴሌግራም ያገናኙ፣ ከዚያ ሲፈልጉ የቀሪ ሂሳብ ማሳወቂያ ያብሩ።',
  telegramConnectedHint: 'ይህ ደንበኛ በቴሌግራም የቀሪ ሂሳብ መልእክት ሊደርሰው ይችላል።',
  notifyOnTelegram: 'በቴሌግራም አሳውቅ',
  notifyOnTelegramHint: 'ዱቤ ወይም ክፍያ ከተመዘገበ በኋላ ቴሌግራም ራሱን ይከፍታል።',
  telegramNotifyEnabledState: 'ለዚህ ደንበኛ ራስ-ሰር የቴሌግራም መክፈት ነቅቷል።',
  telegramNotifyDisabledState: 'ቴሌግራም አማራጭ ብቻ ነው፣ ራሱን አይከፍትም።',
  telegramNeedContactHint: 'መጀመሪያ የቴሌግራም ስም ወይም ሊንክ ያስገቡ።',
  telegramFormatHint: '@username, t.me/... ወይም https://t.me/... ብቻ ይጠቀሙ።',
  telegramAutoUpdatesTitle: 'ራስ-ሰር የቀሪ ሂሳብ ማሳወቂያ',
  telegramAutoUpdatesBody: 'ከተገናኝ በኋላ የዚህ ደንበኛ ቀሪ ሂሳብ ሲቀየር በቴሌግራም መልእክት ሊደርሰው ይችላል።',
  telegramNotifyConnectFirst: 'ቴሌግራምን በመጀመሪያ ያገናኙ፣ ከዚያ ይህን ያብሩ።',
  telegramConnectFirstToast: 'ዝመና ለመላክ ቴሌግራምን በመጀመሪያ ያገናኙ።',
  qrPrimaryMethod: 'QR ኮድ',
  telegramQrHint: 'ይህንን QR ኮድ እንዲስካን አድርጉት እና የቴሌግራም ግንኙነት ሊንኩን ይክፈት።',
  shareInviteLink: 'የግብዣ ሊንክ አጋራ',
  shareInviteLinkHint: 'ይህንን ሊንክ ቅዳ እና በሚጠቀሙበት ማንኛውም መንገድ ላክ።',
  copyLink: 'ሊንክ ቅዳ',
  inviteLinkCopied: 'የግብዣ ሊንክ ተቀድቷል',
  copyFailed: 'ሊንኩን መቅዳት አልተቻለም',
  manualTelegramFallback: 'በእጅ ማስገባት',
  manualTelegramFallbackHint: 'ካስፈለገ የደንበኛውን @username ወይም t.me ሊንክ በእጅ ያስገቡ።',
  confirmConnection: 'ግንኙነቱን አረጋግጥ',
  skipForNow: 'ለአሁን ዝለል',

  // Provider chips
  todaysBreakdown: 'የዛሬ ሂሳብ',
  payingVia: 'በ',
  addCustomBank: 'ባንክ አክል…',
  addCustomWallet: 'ዋሌት አክል…',
  customProviderName: 'ስም',
  providerEnabled: 'ነቅቷል',
  providerDisabled: 'ተዘግቷል',

  // Onboarding
  onboardWelcome: 'ማስታወሻዎን ጀምር',
  onboardSubtitle: 'የሱቅ ማስታወሻ',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'ስምዎን ያስገቡና ገበያን ወዲያው ይጀምሩ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(አማራጭ)',
  onboardPhoneHelper: 'ስልክዎን በቅንብሮች ውስጥ በኋላ ማከል ይችላሉ።',
  onboardPromiseSimple: 'ለሽያጭ፣ ወጪ እና ዱቤ ቀላል ማስታወሻ',
  onboardPromiseFast: 'በስምዎ ብቻ ይጀምሩ',
  onboardPromisePrivate: 'መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ',
  onboardGetStarted: 'ገበያን ጀምር',
  onboardSettingUp: 'በማዘጋጀት ላይ…',
  onboardFooter: 'ውሂቡ በስልክዎ ላይ ይቆያል · ምዝገባ አያስፈልግም · ነፃ',

  // Trust card
  trustCardTitle: 'ማስታወሻዎ በዚህ ስልክ ላይ ይቆያል',
  trustCardBody: 'ሽያጮችዎን ያስቀምጡ፣ መተግበሪያውን ዝጉ፣ በኋላም እንደገና ይክፈቱ። መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ።',
  trustCardAction: 'የመጀመሪያ ሽያጭዎን ያስቀምጡ',
  trustLastSaved: 'የመጨረሻ ጊዜ የተቀመጠ',
  trustTodayCount: 'ዛሬ የተቀመጠ',
  trustReopenHint: 'በማንኛውም ጊዜ ዝጉና እንደገና ይክፈቱ፤ መዝገቦችዎ አይጠፉም።',

  // Offline / online
  offlineReadyTitle: 'የኦፍላይን አጠቃቀም ዝግጁ ነው',
  offlineReadyBody: 'ግንኙነት ቢደክምም ገበያን እንደገና መክፈት ይችላሉ፣ መዝገቦችዎም በዚህ ስልክ ላይ ይቆያሉ።',
  offlineNowTitle: 'አሁን ከኢንተርኔት ውጪ ነዎት',
  offlineNowBody: 'በዚህ ስልክ ላይ የተቀመጠው ማስታወሻ እንደተለመደው ይሰራል።',
  updateReadyTitle: 'አዲስ እትም ዝግጁ ነው',
  updateReadyBody: 'አዲስ የመተግበሪያ እትም አለ። አንድ ጊዜ ያድሱ።',
  refreshApp: 'መተግበሪያውን አድስ',
  notNow: 'አሁን አይደለም',

  // Calculator
  calc: 'ሂሳብ',
  calculator: 'የትርፍ ካልኩሌተር',
  calcCost: 'የዋጋ ቅናሽ',
  calcSell: 'የሽያጭ ዋጋ',
  calcProfit: 'ትርፍ',
  calcMargin: 'ትርፍ (%)',
  calcPlaceholder: 'መጠን ያስገቡ…',

  // Voice
  voiceNotSupported: 'ድምጽ አይደገፍም — የቁልፍ ሰሌዳ ይጠቀሙ',
  voiceInput: 'ድምጽ',
  tryAgain: 'እንደገና ሞክር',
  voiceMicBlocked: 'ማይክሮፎኑ ታግዷል። የአሳሽ ቅንብሮችን ይመልከቱ።',
  recordByVoice: 'ሽያጭ ለመመዝገብ ይናገሩ',
  recordByVoiceSubLabel: 'ሽያጭ ለማስቀመጥ ፈጣኑ መንገድ',
  typeSale: 'በጽሑፍ ሽያጭ',
  typeSaleLabel: 'በጽሑፍ ሽያጭ',
  voiceRecordingTitle: 'እየቀዳ…',
  voiceRecordingHint: 'የሽያጭ መጠን ይናገሩ',
  voiceStop: 'አቁም',
  voiceTypeInstead: 'በጽሑፍ ያስገቡ',
  voiceNoInternet: 'የኢንተርኔት ግንኙነት የለም',
  voiceNoInternetHint: 'የድምጽ ቅዳ ኢንተርኔት ያስፈልጋል። በጽሑፍ ሽያጭ ማስቀመጥ ይችላሉ።',
  voiceTypeSaleInstead: 'በጽሑፍ ሽያጭ',
  voiceRetry: 'እንደገና ሞክር',
  voiceTryFinishSoon: 'እባክዎ ቶሎ ያጠናቁ',
  voiceResultTitle: 'የድምጽ ውጤት',
  voiceTranscript: 'የተናገሩት',
  voiceDetectedTotal: 'የተገኘ ጠቅላላ',
  voiceNoAmount: 'መጠን አልተገኘም',
  voiceNeedsReview: 'ከማስቀመጥ በፊት ይህንን ረቂቅ ይመልከቱ።',
  voiceParsedItems: 'የተለዩ እቃዎች',
  voiceCustomerName: 'ደንበኛ',
  voiceCustomerPlaceholder: 'ከተጠቀሰ የደንበኛ ስም',
  voiceIntent: 'ዓይነት',
  voiceIntentSale: 'ሽያጭ',
  voiceIntentCredit: 'ዱቤ',
  voiceIntentPayment: 'ክፍያ',
  voiceQuantity: 'ብዛት',
  voiceUnitPrice: 'የአንዱ ዋጋ',
  voiceAutoCalculatedTotal: 'ጠቅላላው ከእቃ መስመሮች በራስ-ሰር ተቆጥሯል።',
  voiceItemNamePlaceholder: 'የእቃ ስም',
  voiceSave: 'ሽያጭ አስቀምጥ',
  voiceFix: 'አርትዕ',
  voiceReRecord: 'እንደገና ቅዳ',
  voiceFixTitle: 'የድምጽ ሽያጭ አርትዕ',
  voiceTotalLabel: 'ጠቅላላ መጠን',
  voiceNoteLabel: 'ማስታወሻ (አማራጭ)',
  voiceNotePlaceholder: 'ለምሳሌ ዳቦ፣ ስኳር…',
  voiceSaleSaved: 'የድምጽ ሽያጭ ተቀምጧል',
  voiceAddAnotherItem: 'ሌላ እቃ አክል',
  voiceRunningTotal: 'ጠቅላላ ድምር',
  voiceItemsRecorded: 'እቃዎች ተመዝግበዋል',

  // Intro slides
  introSlide1Title: 'የሱቅ ማስታወሻ',
  introSlide1Body: 'ሽያጭ፣ ወጪ እና ዱቤን በስልክዎ ላይ ቀላል ማስታወሻ ያድርጉ።',
  introSlide2Title: 'ገንዘብዎን ፈጣን ይመልከቱ',
  introSlide2Body: 'የዛሬ ሁኔታዎን በጥቂት ሰከንዶች ይረዱ።',
  introSlide3Title: 'ሶስት ቁልፎች ብቻ',
  introSlide3Body: 'ሸጥ፣ ወጪ እና ዱቤ በፍጥነት ለመመዝገብ ይጠቀሙ።',
  introLetsStart: 'እንጀምር',
  introNext: 'ቀጣይ →',
  introSkip: 'ዝለል',
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gebya_lang') || 'en');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.body.dataset.lang = lang;
    localStorage.setItem('gebya_lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'am' : 'en';
      return next;
    });
  };

  const t = lang === 'am' ? { ...AM, ...AM_OVERRIDES } : { ...EN, ...EN_OVERRIDES };

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}



