import { createContext, useContext, useEffect, useState } from 'react';
// NATIVE-SPEAKER VERIFICATION REQUIRED
// All Amharic (AM) strings below were machine-translated and have NOT been
// reviewed by a native Amharic speaker. Before public launch, every string in
// the AM object must be verified and corrected by a native speaker, especially
// financial/business terminology, verb forms, and formal/informal register.
// Do NOT ship to production without completing this review.


const EN = {
  installSectionTitle: 'Install App',
  installBannerTitle: 'Install Gebya on this phone',
  installBannerBody: 'Add Gebya to your home screen so you can open it like an app.',
  installNow: 'Install Now',
  installHowTo: 'Install',
  installGuideButton: 'How to install',
  installGuideTitle: 'Install Gebya on your phone',
  installGuideHint: 'Do this once, then open Gebya from your phone home screen.',
  installGuideDeviceTitle: 'Phone install steps',
  installAlreadyInstalled: 'Already installed',
  installStatusInstalled: 'Installed on your home screen',
  installStatusBrowser: 'Running in browser mode',
  installStatusOnline: 'Online now',
  installStatusOffline: 'Offline now',
  installChecklistOffline: 'Offline-ready notebook',
  installChecklistHomeScreen: 'Home screen install',
  installChecklistData: 'Data location',
  installChecklistReady: 'Ready',
  installChecklistInstalled: 'Installed',
  installChecklistPending: 'Not yet',
  installChecklistOnPhone: 'This phone',
  installIosStep1: 'Open Gebya in Safari.',
  installIosStep2: 'Tap Share, then tap "Add to Home Screen."',
  installIosStep3: 'Tap "Add", then open Gebya from your home screen.',
  installAndroidStep1: 'Open Gebya in Chrome.',
  installAndroidStep2: 'Open the browser menu and tap "Install app" or "Add to Home screen."',
  installAndroidStep3: 'Confirm, then open Gebya from your home screen.',
  installGenericStep1: 'Open Gebya in your phone browser.',
  installGenericStep2: 'Open the browser menu and look for "Install app" or "Add to Home Screen."',
  installGenericStep3: 'Save it, then open Gebya from your home screen.',
  updateReadyTitle: 'Fresh version ready',
  updateReadyBody: 'A newer app version is available. Refresh once to use the latest installable build.',
  refreshApp: 'Refresh App',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even when your connection is weak, and your saved notebook stays on this phone.',
  offlineNowTitle: 'You are offline',
  offlineNowBody: 'Your saved notebook on this phone still works. Features that need internet may wait until you reconnect.',
  notNow: 'Not now',
  telegramNotifyConnectFirst: 'Connect Telegram first, then turn this on.',
  telegramConnectFirstToast: 'Connect Telegram first to send updates.',
  appName: 'Gebya',
  loading: 'Loading your notebook...',
  today: 'Today',
  todayLabel: 'Today',
  credit: 'Dubie',
  creditLabel: 'Dubie',
  report: 'Report',
  settings: 'Settings',
  sales: 'Sales',
  spent: 'Spent',
  iSold: 'I Sold',
  iSoldLabel: 'Sold',
  iSpent: 'I Spent',
  iSpentLabel: 'Expense',
  creditBtn: 'Dubie',
  creditBtnLabel: 'Dubie',
  calc: 'Calc',
  todaysEntries: "Today's Entries",
  noEntries: 'No entries yet. Use the buttons above to start!',
  profit: 'profit',
  edited: 'edited',
  editEntry: 'Edit entry',
  deleteEntryLabel: 'Delete entry',
  calculator: 'Profit Calculator',
  calcCost: 'Cost Price',
  calcSell: 'Selling Price',
  calcProfit: 'Profit',
  calcMargin: 'Margin',
  calcPlaceholder: 'Enter amount',
  topProducts: 'Top Sold Today',
  weekTrend: '7-Day Trend',
  shareReport: 'Share Report',
  shareReportBtn: 'Share Today',
  shareTitle: 'Share Daily Report',
  shareDailyReport: 'Daily Report',
  shareTopItems: 'Top Items Sold',
  shareSentVia: 'Sent via Gebya',
  dubieGiven: 'Dubie Given',
  paymentsCollected: 'Payments Collected',
  netReceived: 'Net Received',
  shareViaDevice: 'Share via Device',
  openTelegram: 'Open in Telegram',
  copyText: 'Copy Text',
  usageInsights: 'Usage Insights',
  dayStreak: 'day streak',
  best: 'best',
  daysActive: 'days active',
  since: 'since',
  totalEntries: 'entries',
  sessions: 'sessions opened',
  shareMyStats: 'Share My Stats',
  copiedToClipboard: 'Copied to clipboard!',
  shopProfile: 'Profile',
  userName: 'Name',
  phoneNumber: 'Phone Number',
  phoneRequired: 'Phone number is required',
  phoneInvalid: '9 digits starting with 7 or 9',
  telegramLabel: 'Telegram / Contact',
  telegramPlaceholder: '@username, t.me/... or https://t.me/...',
  connectTelegram: 'Connect Telegram',
  manageTelegram: 'Manage Telegram',
  telegramConnection: 'Telegram connection',
  telegramConnectHint: 'Link Telegram once, then turn on balance updates when you want.',
  telegramConnectedHint: 'This customer can receive Telegram balance updates.',
  notifyOnTelegram: 'Notify on Telegram',
  notifyOnTelegramHint: 'Open Telegram automatically after saving Dubie or payment.',
  telegramNotifyEnabledState: 'Automatic Telegram opening is on for this customer.',
  telegramNotifyDisabledState: 'Telegram stays optional and will not open automatically.',
  telegramNeedContactHint: 'Add a Telegram username or link first, then turn notifications on.',
  telegramFormatHint: 'Use only @username, t.me/... or https://t.me/...',
  telegramManualDraftHint: 'Manual Telegram updates will open a drafted message after each save.',
  telegramAutoUpdatesTitle: 'Automatic balance updates',
  telegramAutoUpdatesBody: 'Once linked, this customer can receive Telegram updates whenever their balance changes.',
  telegramBorrowerUpdatesLinked: 'Borrower updates are linked to the Gebya bot.',
  telegramBorrowerLinkWaiting: 'Borrower link is waiting for the bot start.',
  telegramManualSavedNotLinked: 'Manual Telegram contact is saved, but bot updates are not linked yet.',
  telegramBorrowerNeedsBotStart: 'Borrower still needs to start the Gebya bot before updates can send.',
  telegramDraftUntilLinked: 'Updates can open as a drafted Telegram message until the borrower links the Gebya bot.',
  telegramLinkBeforeUpdates: 'Link the borrower to the Gebya bot before turning updates on.',
  telegramBorrowerNotStarted: 'Borrower has not started the bot yet.',
  qrPrimaryMethod: 'QR code',
  telegramQrHint: 'Let the customer scan this QR code to open the Telegram connection link.',
  shareInviteLink: 'Share invite link',
  shareInviteLinkHint: 'Copy this link and send it through any channel you already use.',
  copyLink: 'Copy link',
  inviteLinkCopied: 'Invite link copied',
  copyFailed: 'Could not copy link',
  manualTelegramFallback: 'Manual fallback',
  manualTelegramFallbackHint: 'If needed, enter the customer Telegram username or t.me link manually.',
  telegramGenerateBorrowerLinkFirst: 'Generate a Telegram borrower link first.',
  telegramLatestUpdateSentAgain: 'Latest borrower update sent again.',
  telegramNoUpdateReady: 'No borrower update is ready to resend yet.',
  telegramResendUpdateFailed: 'Could not resend the borrower update.',
  telegramSendFailed: 'Telegram send failed.',
  telegramManualInvalid: 'Manual Telegram contact is invalid.',
  telegramDubieSavedButFailed: 'Dubie saved. Telegram delivery failed.',
  confirmConnection: 'Confirm Connection',
  skipForNow: 'Skip for Now',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  privacy: 'Privacy',
  hideAmounts: 'Hide amounts',
  totalsHidden: 'Totals are hidden — tap to show',
  totalsVisible: 'Totals are visible — tap to hide',
  paymentMethods: 'Payment Methods',
  banks: 'Banks',
  mobileWallets: 'Mobile Wallets',
  onlyEnabled: 'Only enabled methods appear as options in the form',
  recurringExpenses: 'Recurring Expenses',
  recurringHint: 'Quick-fill shortcuts for expenses you enter often',
  addRecurring: 'Add recurring expense',
  demoCardSectionLabel: 'Quick-fill (examples)',
  recurringExampleRent: 'Rent',
  recurringExampleEqub: 'Equb',
  addRecurringPopupGuide: 'Save this as a recurring expense to reuse it anytime',
  addAndUse: 'Add & Use',
  addRecurringHint: 'You can add more recurring expenses in Settings',
  frequency: 'Frequency',
  cancel: 'Cancel',
  add: 'Add',
  yourData: 'Your Data',
  storedOnDevice: 'Stored on this device',
  exportCSV: 'Export to CSV',
  exportHint: 'Download a spreadsheet backup',
  lastBackup: 'Last backup',
  noBackupYet: 'No backup yet — export to keep your data safe',
  clearAll: 'Clear all data',
  clearHint: 'Permanently deletes everything — export first!',
  about: 'About',
  privacyNote: 'Your data never leaves this device. No account needed.',
  worksOffline: 'Works offline — Data stays on your phone — Free',
  achievementBadges: 'Achievement Badges',
  badgesEarned: 'earned',
  noBadges: 'Complete milestones to earn badges!',
  clearConfirm: 'Clear all data—',
  clearConfirmMsg: 'This will permanently delete all {count} entries and {credits} Dubie records. This cannot be undone.',
  yesDelete: 'Yes, delete everything',
  dataCleared: 'Data cleared',
  reloading: 'Reloading...',
  deleteEntry: 'Delete this entry—',
  delete: 'Delete',
  newBestDay: 'New best day!',
  birr: 'birr',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  expenseName: 'Expense name (e.g. Rent)',
  amount: 'Amount',
  sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',

  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: '— — —',
  onboardDesc: 'Start with your name, then record sales, spending, and Dubie in seconds.',
  onboardNamePlaceholder: 'e.g. Tigist',
  onboardPhoneOptional: '(optional)',
  onboardPhoneHelper: 'You can add your phone later in Settings.',
  onboardBusinessTypeLabel: 'Business type',
  onboardBusinessTypeOptional: '(optional)',
  onboardBusinessTypeHelper: 'Pick what fits best so Gebya can suggest faster later.',
  onboardBusinessTypePlaceholder: 'Or type your business',
  businessTypeShop: 'Shop',
  businessTypeWholesale: 'Wholesale',
  businessTypeDistributor: 'Distributor',
  businessTypeBoutique: 'Boutique',
  businessTypeCafe: 'Cafe',
  businessTypeService: 'Service',
  businessTypeOther: 'Other',
  onboardPromiseSimple: 'Record sales, spending, and Dubie in a few taps',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'See who owes what without hard accounting words',
  onboardGetStarted: 'Start using Gebya',
  onboardSettingUp: 'Setting up...',
  onboardFooter: 'All data stays on your phone ... No account needed ... Free',

  iSoldSomething: 'I Sold Something',
  iSpentSomething: 'I Spent Something',
  recordCredit: 'Record Dubie',
  addCredit: 'Add Dubie',
  addCustomer: 'Add Customer',
  saveCustomer: 'Save customer',
  customerSaved: 'Customer saved',
  customerSaveFailed: 'Could not save customer. Please try again.',
  customerHelperText: 'Use any label you will recognize later.',
  customerIdentifier: 'Customer identifier',
  customerIdentifierPlaceholder: 'Name, nickname, relation, place, or vehicle clue',
  customerNotePlaceholder: 'Anything that helps you recognize this customer',
  customerPhoneOptional: 'Phone (optional)',
  customerPhonePlaceholder: 'Phone number',
  customerTelegramOptional: 'Telegram (optional)',
  customerTelegramPlaceholder: '@username, t.me/... or https://t.me/...',
  customerTotalBalance: 'Total Balance',
  customerBalance: 'Balance',
  searchCustomerPlaceholder: 'Search customer or note...',
  customerSearchHint: 'Search by name, note, phone, or Telegram.',
  customerSearchResults: 'Showing {shown} of {total} customers',
  noCustomersFound: 'No customers found',
  noCustomersYet: 'No customers yet',
  noCustomerSearchResults: 'No customers match this search',
  backToCustomers: 'Back to customers',
  customerTransactionHistory: 'Transaction History',
  paymentRecordedLabel: 'Payment',
  creditAddedLabel: 'Dubie added',
  noTransactionsYet: 'No transactions yet',
  noTransactionsHint: 'Use Add Dubie or Record Payment to start this history.',
  currentBalance: 'Current Balance',
  previousBalance: 'Previous balance',
  updatedBalance: 'Updated balance',
  currentBalanceHint: 'This is the balance after saving the new Dubie.',
  remainingBalanceHint: 'This is the remaining balance after saving the payment.',
  paymentNoteOptional: 'Payment note (optional)',
  itemNoteOptional: 'Item note (optional)',
  paymentNotePlaceholder: 'Any note about this payment',
  creditItemPlaceholder: 'What they took',
  savedCatalogLabel: 'Saved item / service',
  typeManually: 'Type manually',
  typeNoteManually: 'Type note manually',
  serviceLabel: 'Service',
  itemLabel: 'Item',
  dueDateOptional: 'Due date (optional)',
  ethiopianDisplay: 'Ethiopian display',
  pickDateWithEthiopianHint: 'Choose any date below and we will also show it in Ethiopian calendar.',
  moreOptional: 'More (optional)',
  noteLabel: 'Note',
  savePayment: 'Save payment',
  customerNotFound: 'Customer not found',
  validAmountRequired: 'Enter a valid amount',
  paymentMoreThanBalance: 'Payment is more than the current balance',
  noBalanceToRecordPayment: 'No balance to collect yet',
  balanceAfterEntry: 'Balance after this entry',
  dueLabelShort: 'Due',
  whatDidYouSell: 'What did you sell—',
  sellPlaceholder: 'e.g. bread, sugar...',
  whatDidYouSpendOn: 'What did you spend on—',
  spendPlaceholder: 'e.g. transport, rent...',
  creditNameLabel: 'Name',
  creditNamePlaceholder: 'e.g. Abebe...',
  howMuchTotal: 'How much total—',
  saveSale: 'Save Sale',
  saleSettlementLabel: 'How was it paid—',
  saleSettlementPaidNow: 'Paid now',
  saleSettlementPaidNowHint: 'No balance left',
  saleSettlementPaidPartly: 'Paid partly',
  saleSettlementPaidPartlyHint: 'Some paid now',
  saleSettlementPayLater: 'Pay later',
  saleSettlementPayLaterHint: 'All stays open',
  salePaidAmountLabel: 'How much was paid now—',
  salePaidAmountHint: 'Paid amount must be more than 0 and less than the total.',
  saleCustomerRequiredHint: 'Add who should keep the remaining balance.',
  saleRemainingBalanceLabel: 'Remaining balance',
  saleRemainingBalanceHint: 'After saving, the remaining amount will be added to this customer balance.',
  saleSavedWithBalance: 'Sale saved. Remaining balance added to customer.',
  saleLinkedBalanceTitle: 'This sale has remaining customer balance.',
  saleLinkedBalanceBody: 'If you change the sale total, the linked remaining balance will update too.',
  saleRemainingHistory: 'Remaining',
  salePaidShort: 'paid',
  saleLabelShort: 'Sale',
  saveExpense: 'Save Expense',
  saveCredit: 'Save Dubie',
  addAnotherSale: 'Add another sale',
  addAnotherExpense: 'Add another expense',
  done: 'Done',
  birrSaved: 'birr saved',
  howMany: 'How many—',
  direction: 'Direction',
  theyOweMe: 'They owe me',
  iOweThem: 'I owe them',
  owesMe: 'Owes me',
  iOweLabel: 'I owe',
  quickFill: 'Quick-fill',
  phoneOptional: 'Phone number',
  phoneOptionalHint: '(optional)',
  phonePlaceholder: 'e.g. 0912345678',
  whenDue: 'When is it due—',
  pickDate: 'Pick a date',
  selectDueDate: 'Please select a due date',
  advancedOptional: 'Advanced (optional)',
  whatDidYouPay: 'What did you pay for this—',
  perUnit: '(per unit)',
  helpsSeeProfit: 'Optional ... helps you see your true profit',
  sellingBelowCost: 'You are selling below cost. You may lose money on this sale.',
  profitOnSale: 'Profit on this sale:',
  paymentType: 'Payment type',
  cash: 'Cash',
  bank: 'Bank',
  wallet: 'Wallet',

  editSale: 'Edit Sale',
  editExpense: 'Edit Expense',
  editCredit: 'Edit Dubie',
  editPayment: 'Edit Payment',
  editEntryLabel: 'Edit Entry',
  editedAt: 'Edited',
  item: 'Item',
  quantity: 'Quantity',
  dueDate: 'Due date',
  costPriceLabel: 'Cost price',
  sellingBelowCostShort: 'Selling below cost.',
  profitLabel: 'Profit:',
  saving: 'Saving...',

  todaysProfit: "Today's Profit",
  estimatedProfit: "Estimated Profit",
  partialCostDisclaimer: "Some items are missing a cost price — this estimate may be lower than your actual profit",
  partialCostTip: "Add cost prices to your items for an accurate profit figure",
  todaysSales: "Today's Sales",
  salesLabel: 'Sales',
  expenses: 'Expenses',
  costOfGoods: 'Cost of goods',
  netProfit: 'Net Profit',
  advancedHint: 'Tap "Advanced" when recording a sale to see true profit',

  tapToReveal: 'Tap to reveal',
  tapToRevealAria: 'Tap to reveal amount',
  hideAmountAria: 'Hide amount',

  byDay: 'By Day',
  byWeek: 'By Week',
  groupBy: 'Group:',
  searchPlaceholder: 'Search by item or customer...',
  noSearchResults: 'No results for',
  noRecords: 'No records yet',
  startRecording: 'Record your first sale or expense to start',
  entries: 'entries',
  revenue: 'revenue',
  thisWeek: 'This Week',

  noCreditRecords: 'No Dubie records',
  addCreditHint: 'Tap "—" on the Today tab to add one',
  owedToMe: 'Owed to me',
  iOweAmount: 'I owe',
  active: 'active',
  paid: 'paid',
  activeTab: 'Active',
  paidTab: 'Paid',
  noPaidRecords: 'No paid records yet',
  allCaughtUp: 'All caught up!',
  paidInFull: 'Paid in full',
  paidLabel: 'PAID',
  due: 'Due',
  owesMeLabel: 'Owes me',
  iOweTag: 'I owe',

  backToCredit: 'Back to —',
  originalDebt: 'Original debt',
  amountPaid: 'Amount paid',
  stillOwes: 'Still owes',
  progress: 'Progress',
  percentPaid: '% paid',
  paidSome: 'Paid Some',
  allPaid: 'All Paid',
  call: 'Call',
  recordPartialPayment: 'Record Partial Payment',
  recordPayment: 'Record Payment',
  markFullyPaid: 'Mark Fully Paid',
  paymentHistory: 'Payment history',
  borrowed: 'Borrowed',
  paidBack: 'Paid back',
  remaining: 'Remaining',
  payMethodCash: 'Cash',
  payMethodBank: 'Bank Transfer',
  payMethodMobile: 'Mobile Money',
  paymentExceedsOwed: 'Amount cannot exceed what is owed',

  voiceNotSupported: 'Voice not supported ... use keyboard',
  voiceInput: 'Voice input',
  tryAgain: 'Try again',
  voiceMicBlocked: 'Microphone is blocked. Check browser settings.',

  exportAuthRequired: 'Authentication required',
  incorrectPin: 'Incorrect PIN',
  enterPinPlaceholder: 'Enter PIN',
  enterPinToExport: 'Enter your PIN to export',
  typeDeleteConfirm: 'Type DELETE to confirm',

  close: 'Close',

  todaysBreakdown: "Today's Breakdown",
  payingVia: 'Paying via',
  creditPhoneHint: '9 digits starting with 7 or 9',
  myShop: 'My Shop',
  more: 'More',
  frequentExpenses: 'Frequent Expenses',
  language: 'Language',
  shareTodayTitle: "Share Today's Report",
  shareTodayHint: "Send today's shop summary to the owner or keep a copy.",
  addCustomBank: 'Add bank...',
  addCustomWallet: 'Add wallet...',
  customProviderName: 'Provider name',
  providerEnabled: 'Enabled',
  providerDisabled: 'Disabled',

  introSlide1Title: 'Your Business Notebook',
  introSlide1Body: 'Track sales, expenses, and Dubie ... all on your phone. No account needed.',
  introSlide2Title: 'See Your Money at a Glance',
  introSlide2Body: "Today's profit always shows at the top. Know where you stand in seconds.",
  introSlide3Title: 'Three Buttons. That\'s It.',
  introSlide3Body: 'Tap — to sell, — to spend, — for Dubie. Done in 10 seconds.',
  introLetsStart: "Let's Start —",
  introNext: 'Next —',
  introSkip: 'Skip intro',

  noEntriesPrompt: 'Tap — above to record your first sale',
  noSalesRecordedYet: 'No sales recorded yet',
  recordFirstSalePrompt: 'Tap above to record your first sale',

  saleSaved: '— Sale saved — — Keep going',
  expenseSaved: 'Expense recorded —',
  creditSaved: 'Dubie recorded —',
  paymentSaved: 'Payment recorded —',
  trustCardTitle: 'Your records are saved',
  trustCardBody: 'Close Gebya and come back later. Your sales, spending, and Dubie will still be here.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Record fast now, check it again anytime.',
  undone: 'Undone —',

  statusOverdue: 'OVERDUE',
  statusDueSoon: 'DUE SOON',
  statusOk: 'OK',

  periodDay: 'Day',
  periodWeek: 'Week',
  periodMonth: 'Month',
  totalSales: 'Total Sales',
  totalExpenses: 'Total Expenses',
  topProductsWeek: 'Top Products This Week',
  topProductsMonth: 'Top Products This Month',
  topProductsDay: 'Top Products Today',
  byQuantity: 'by qty',
  byRevenue: 'by revenue',
  weekBreakdown: 'Day-by-Day',
  monthBreakdown: 'Week-by-Week',
  weekOf: 'Week of',
  noSalesThisPeriod: 'No sales this period',
  week: 'Wk',

  recordByVoice: 'Speak to Record Sale',
  recordByVoiceSubLabel: 'Fastest way to save a sale',
  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',
  voiceRecordingTitle: 'Recording...',
  voiceRecordingHint: 'Speak your sale amount',
  voiceStop: 'Stop',
  voiceTypeInstead: 'Type instead',
  voiceNoInternet: 'No internet connection',
  voiceNoInternetHint: 'Voice transcription requires internet. You can still type your sale.',
  voiceTypeSaleInstead: 'Type Sale Instead',
  voiceRetry: 'Retry',
  voiceTryFinishSoon: '— Try to finish soon',
  voiceListeningState: 'Listening',
  voiceStoppedState: 'Stopped',
  voiceProcessingState: 'Processing',
  voiceLivePreview: 'What we hear',
  voiceLivePreviewHint: 'Your words should show here before saving.',
  voiceResultTitle: 'Voice Result',
  voiceTranscript: 'What you said',
  voiceDetectedTotal: 'Detected total',
  voiceNoAmount: 'No amount detected',
  voiceNeedsReview: 'Check this draft before saving.',
  voiceParsedItems: 'Parsed items',
  voiceCustomerName: 'Customer',
  voiceCustomerPlaceholder: 'Customer name if mentioned',
  voiceIntent: 'Intent',
  voiceIntentSale: 'Sale',
  voiceIntentCredit: 'Dubie',
  voiceIntentPayment: 'Payment',
  voiceQuantity: 'Qty',
  voiceUnitPrice: 'Unit price',
  voiceAutoCalculatedTotal: 'Total auto-calculated from line items.',
  voiceItemNamePlaceholder: 'Item name',
  voiceSave: 'Save Sale',
  voiceFix: 'Fix & Edit',
  voiceReRecord: 'Re-record',
  voiceFixTitle: 'Fix Voice Sale',
  voiceTotalLabel: 'Total amount',
  voiceNoteLabel: 'Note (optional)',
  voiceNotePlaceholder: 'e.g. bread, sugar...',
  voiceSaleSaved: 'Voice sale saved —',
  voiceAddAnotherItem: 'Add another item',
  voiceRunningTotal: 'Running Total',
  voiceItemsRecorded: 'items recorded',
  voiceSalesOnlyTitle: 'Voice is sales-only right now.',
  voiceSalesOnlyBody: 'This draft sounded like Dubie or payment. Review it carefully before saving it as a sale.',
  telegramLinkedOnTelegram: 'Borrower is linked on Telegram.',
  telegramWaitingForBorrower: 'Waiting for borrower to start the bot.',
  telegramServiceUnavailableNow: 'Telegram service is unavailable right now.',
  telegramManualStillWorks: 'Telegram service is unavailable right now. Manual contact still works.',
  telegramLinkedUpdatesReady: 'Linked borrower updates are ready.',
  telegramGenerateLinkHint: 'Generate the borrower link, then let them scan or open it in Telegram.',
  telegramOpenBot: 'Open Bot',
  telegramRefreshStatus: 'Refresh status',
  telegramBorrowerStartedAs: 'Borrower started the bot as {username}',
  telegramLinkingUnavailable: 'Automatic Telegram linking is not available right now.',
  telegramManualCanEnableLater: 'You can still save a manual Telegram contact below and enable automatic updates later.',
  telegramApiServerNeeded: 'You can still save a manual Telegram contact below. Bot linking and automatic updates need the API server to be available.',
  telegramSaveFallbackContact: 'Save fallback contact',
  telegramResending: 'Resending...',
  telegramResendLatestUpdate: 'Resend latest update',

  stepDetails: 'Details',
  stepPayment: 'Payment',
  stepReview: 'Review',
  editDetails: 'Edit Details',
  next: 'Next',
  back: 'Back',
  enterItemName: 'Enter item name',
  enterCustomerName: 'Enter customer name',
  draftSaved: 'Draft saved',
  keepDraft: 'Keep Draft',
  discardDraft: 'Discard',
  reviewSale: 'Review Sale',
  photoAttached: 'Photo attached',
  noPaymentCollected: 'No payment collected now. This sale will be added to Dubie.',
  settlementPaidNow: 'Paid now',
  settlementPaidPartly: 'Paid partly',
  settlementPayLater: 'Pay later',
  reviewTotal: 'Total',
  reviewItem: 'Item',
  reviewSettlement: 'Settlement',
  reviewProvider: 'Provider',
  reviewPaidAmount: 'Paid amount',
  reviewRemaining: 'Remaining',
  reviewCustomer: 'Customer',
  reviewReturnDate: 'Return date',

  supplierDubieSaved: 'Supplier Dubie saved',
  toCollect: 'To Collect',
  toPay: 'To Pay',
  supplierSaveFailed: 'Could not save supplier. Please try again.',
  addAmountOwed: 'Add owed',
  saveAmountOwed: 'Save',
  newBalance: 'New',

  dubieExistingCustomer: 'Existing customer',
  dubieAddTitle: 'Add Dubie',
  dubieSearchHint: 'Search or choose a recent customer',
  dubieSearchPlaceholder: 'Search customer',
  dubieNewCustomer: 'New customer',
  dubieOpenBalanceCustomers: 'Open balance customers',
  dubieRecentCustomers: 'Recent customers',
  dubieShown: 'shown',
  dubieNoCustomerFound: 'No customer found',
  dubieTryAnother: 'Try another name or add a new customer',
  dubieRemainingBalance: 'Remaining balance',

  newCustomerTitle: 'New customer',
  newCustomerHint: 'Reminders need contact info',
  customerNameLabel: 'Customer name',
  customerNamePlaceholder: 'Customer name',
  mobileNumberLabel: 'Mobile number',
  pickFromContacts: 'Pick from contacts',
  phoneMustStartWith7or9: 'Phone must start with 7 or 9 (9 digits)',
  smsRemindersHint: 'SMS reminders need a mobile number',
  telegramLaterHint: 'Bot connection can be added later',

  editAmountOwed: 'Edit amount owed',
  moreThanRemainingBalance: 'More than the remaining balance',
  whatWasPurchased: 'What was purchased',
  itemNotePlaceholder: 'What was purchased',
  saveSupplier: 'Save supplier',
  addSupplier: 'Add supplier',
  supplierName: 'Supplier name',
  supplierNamePlaceholder: 'Supplier name',
  supplierNotePlaceholder: 'Note',
  mobileNumber: 'Mobile number',
};

// My Shop keys (myShop, more, frequentExpenses, shareTodayTitle, shareTodayHint) are temporary translations
// and require native-speaker verification before pilot, alongside the broader Amharic review.
// Install-related Amharic strings below require human review before public beta:
// installSectionTitle, installBannerTitle, installBannerBody, installNow, installHowTo,
// installGuideButton, installGuideTitle, installGuideHint, installGuideDeviceTitle,
// installAlreadyInstalled, installStatusInstalled, installStatusBrowser,
// installStatusOnline, installStatusOffline, installChecklistOffline,
// installChecklistHomeScreen, installChecklistData, installChecklistReady,
// installChecklistInstalled, installChecklistPending, installChecklistOnPhone,
// installIosStep1, installIosStep2, installIosStep3, installAndroidStep1,
// installAndroidStep2, installAndroidStep3, installGenericStep1,
// installGenericStep2, installGenericStep3.
const AM = {
  installSectionTitle: 'አፕሊኬሽን ጫን',
  installBannerTitle: 'ገበያን በዚህ ስልክ ላይ ጫን',
  installBannerBody: 'ገበያን ወደ ሆም ስክሪንህ ጨምር እንደ አፕሊኬሽን እንድትከፍተው።',
  installNow: 'አሁን ጫን',
  installHowTo: 'ጫን',
  installGuideButton: 'እንዴት እንደሚጫን',
  installGuideTitle: 'ገበያን በስልክህ ላይ ጫን',
  installGuideHint: 'ይህንን አንድ ጊዜ አድርግ ከዚያ ገበያን ከስልክህ ሆም ስክሪን ክፈት።',
  installGuideDeviceTitle: 'የስልክ መጫኛ ደረጃዎች',
  installAlreadyInstalled: 'ቀድሞውኑ ተጭኗል',
  installStatusInstalled: 'በሆም ስክሪንህ ላይ ተጭኗል',
  installStatusBrowser: 'በብራውዘር ሞድ እየሰራ ነው',
  installStatusOnline: 'አሁን ኦንላይን ነው',
  installStatusOffline: 'አሁን ኦፍላይን ነው',
  installChecklistOffline: 'ለኦፍላይን ዝግጁ የሆነ ማስታወሻ ደብተር',
  installChecklistHomeScreen: 'የሆም ስክሪን መጫን',
  installChecklistData: 'የዳታ አካባቢ',
  installChecklistReady: 'ዝግጁ',
  installChecklistInstalled: 'ተጭኗል',
  installChecklistPending: 'እስካሁን አይደለም',
  installChecklistOnPhone: 'ይህ ስልክ',
  installIosStep1: 'ገበያን በ Safari ክፈት።',
  installIosStep2: 'Share ን ተጭነህ "Add to Home Screen" ን ተጭን።',
  installIosStep3: '"Add" ን ተጭነህ ገበያን ከሆም ስክሪንህ ክፈት።',
  installAndroidStep1: 'ገበያን በ Chrome ክፈት።',
  installAndroidStep2: 'የብራውዘር ምናሌን ክፈት እና "Install app" ወይም "Add to Home screen" ን ተጭን።',
  installAndroidStep3: 'አረጋግጥ ከዚያ ገበያን ከሆም ስክሪንህ ክፈት።',
  installGenericStep1: 'ገበያን በስልክ ብራውዘርህ ክፈት።',
  installGenericStep2: 'የብራውዘር ምናሌን ክፈት እና "Install app" ወይም "Add to Home Screen" ን ፈልግ።',
  installGenericStep3: 'አስቀምጠው ከዚያ ገበያን ከሆም ስክሪንህ ክፈት።',
  updateReadyTitle: 'አዲስ ስሪት ዝግጁ ነው',
  updateReadyBody: 'አዲስ የአፕሊኬሽን ስሪት አለ። የመጨረሻውን ስሪት ለመጠቀም አንድ ጊዜ አድስ።',
  refreshApp: 'አፕሊኬሽን አድስ',
  offlineReadyTitle: 'ኦፍላይን ሞድ ዝግጁ ነው',
  offlineReadyBody: 'ገበያ ግንኙነትህ ደካማ ሲሆን እንደገና ሊከፈት ይችላል እና የተቀመጠው ማስታወሻ ደብተርህ በዚህ ስልክ ላይ ይቆያል።',
  offlineNowTitle: 'ኦፍላይን ነህ',
  offlineNowBody: 'በዚህ ስልክ ላይ የተቀመጠው ማስታወሻ ደብተርህ አሁንም ይሰራል። ኢንተርኔት የሚፈልጉ ባህሪያት እንደገና እስክትገናኙ ሊጠብቁ ይችላሉ።',
  notNow: 'አሁን አይደለም',
  telegramNotifyConnectFirst: 'መጀመሪያ Telegram ን አገናኝ ከዚያ ይህንን አብራ።',
  telegramConnectFirstToast: 'ማስታወሻ ለመላክ መጀመሪያ Telegram ን አገናኝ።',
  appName: 'ገበያ',
  loading: 'ማስታወሻ ደብተርህን በመጫን ላይ...',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ዱቤ',
  creditLabel: 'ዱቤ',
  report: 'ሪፖርት',
  settings: 'ቅንብሮች',
  sales: 'ሽያጮች',
  spent: 'ወጪ',
  iSold: 'ሸጫለሁ',
  iSoldLabel: 'ሽያጭ',
  iSpent: 'ወጪ አድርጌያለሁ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ዱቤ',
  creditBtnLabel: 'ዱቤ',
  calc: 'ማስያ',
  todaysEntries: 'የዛሬ ግቤቶች',
  noEntries: 'እስካሁን ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ተጠቀም!',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  editEntry: 'ግቤት አስተካክል',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  calculator: 'የትርፍ ማስያ',
  calcCost: 'የዋጋ ዋጋ',
  calcSell: 'የሽያጭ ዋጋ',
  calcProfit: 'ትርፍ',
  calcMargin: 'ማርጂን',
  calcPlaceholder: 'መጠን አስገባ',
  topProducts: 'ዛሬ ከፍተኛ ሽያጭ',
  weekTrend: 'የ7-ቀን ዝንባሌ',
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'የዛሬን አጋራ',
  shareTitle: 'የዕለቱን ሪፖርት አጋራ',
  shareDailyReport: 'የዕለቱ ሪፖርት',
  shareTopItems: 'ከፍተኛ ሽያጭ ዕቃዎች',
  shareSentVia: 'በገበያ (Gebya) ተልኳል',
  dubieGiven: 'የተሰጠ ዱቤ',
  paymentsCollected: 'የተሰበሰቡ ክፍያዎች',
  netReceived: 'የተጣራ ተቀባይነት',
  shareViaDevice: 'በመሣሪያ አጋራ',
  openTelegram: 'በ Telegram ክፈት',
  copyText: 'ጽሑፍ ኮፒ',
  usageInsights: 'የአጠቃቀም ግንዛቤዎች',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ከ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍት ክፍለ ጊዜዎች',
  shareMyStats: 'ስታትስቲክሴን አጋራ',
  copiedToClipboard: 'ወደ ክሊፕቦርድ ተቀድቷል!',
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: 'በ7 ወይም 9 የሚጀምር 9 አሃዞች',
  telegramLabel: 'Telegram / እውቂያ',
  telegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  connectTelegram: 'Telegram አገናኝ',
  manageTelegram: 'Telegram አስተዳድር',
  telegramConnection: 'የ Telegram ግንኙነት',
  telegramConnectHint: 'Telegram ን አንድ ጊዜ አገናኝ ከዚያ ሚዛን ማስታወሻዎችን ስትፈልግ አብራ።',
  telegramConnectedHint: 'ይህ ደንበኛ የ Telegram ሚዛን ማስታወሻዎችን ሊቀበል ይችላል።',
  notifyOnTelegram: 'በ Telegram ለማስታወቅ',
  notifyOnTelegramHint: 'ዱቤ ወይም ክፍያ ካስቀመጥህ በኋላ Telegram በራስ-ሰር ክፈት።',
  telegramNotifyEnabledState: 'ለዚህ ደንበኛ የራስ-ሰር Telegram መክፈቻ ተበርቷል።',
  telegramNotifyDisabledState: 'Telegram ምርጫ ሆኖ ይቆያል በራስ-ሰር አይከፈትም።',
  telegramNeedContactHint: 'መጀመሪያ የ Telegram ተጠቃሚ ስም ወይም አገናኝ ጨምር ከዚያ ማስታወሻዎችን አብራ።',
  telegramFormatHint: '@username, t.me/... ወይም https://t.me/... ብቻ ተጠቀም።',
  telegramManualDraftHint: 'የእጅ Telegram ማስታወሻዎች ከእያንዳንዱ ቁጠባ በኋላ ክፍት መልእክት ይከፍታሉ።',
  telegramAutoUpdatesTitle: 'የራስ-ሰር ሚዛን ማስታወሻዎች',
  telegramAutoUpdatesBody: 'አንዴ ከተገናኘ በኋላ ይህ ደንበኛ ሚዛኑ ሲቀየር የ Telegram ማስታወሻዎችን ሊቀበል ይችላል።',
  telegramBorrowerUpdatesLinked: 'የበዳሪ ማስታወሻዎች ከ Gebya ቦት ጋር ተገናኝተዋል።',
  telegramBorrowerLinkWaiting: 'የበዳሪ አገናኝ ቦቱ እስኪጀምር ይጠብቃል።',
  telegramManualSavedNotLinked: 'የእጅ Telegram እውቂያ ተቀምጧል ነገር ግን የቦት ማስታወሻዎች እስካሁን አልተገናኙም።',
  telegramBorrowerNeedsBotStart: 'በዳሪ ማስታወሻዎች ከመላካቸው በፊት የ Gebya ቦት መጀመር አለበት።',
  telegramDraftUntilLinked: 'በዳሪው Gebya ቦት እስኪገናኝ ድረስ ማስታወሻዎች እንደ ክፍት Telegram መልእክት ሊከፈቱ ይችላሉ።',
  telegramLinkBeforeUpdates: 'ማስታወሻዎችን ከማብራትህ በፊት በዳሪውን ከ Gebya ቦት ጋር አገናኝ።',
  telegramBorrowerNotStarted: 'በዳሪው እስካሁን ቦቱን አልጀመረም።',
  qrPrimaryMethod: 'QR ኮድ',
  telegramQrHint: 'ደንበኛው ይህንን QR ኮድ ስካን እንዲያደርግ ፍቀድ የ Telegram ግንኙነት አገናኝ ለመክፈት።',
  shareInviteLink: 'የግብዣት አገናኝ አጋራ',
  shareInviteLinkHint: 'ይህንን አገናኝ ኮፒ አድርግ እና ቀድሞውኑ በምትጠቀመው ማንኛውም ቻናል ላክ።',
  copyLink: 'አገናኝ ኮፒ',
  inviteLinkCopied: 'የግብዣት አገናኝ ተቀድቷል',
  copyFailed: 'አገናኝ ኮፒ ማድረግ አልተቻለም',
  manualTelegramFallback: 'የእጅ ተተኪ',
  manualTelegramFallbackHint: 'ከተፈለገ የደንበኛውን Telegram ተጠቃሚ ስም ወይም t.me አገናኝ በእጅ አስገባ።',
  telegramGenerateBorrowerLinkFirst: 'መጀመሪያ የ Telegram በዳሪ አገናኝ ፍጠር።',
  telegramLatestUpdateSentAgain: 'የበዳሪ የመጨረሻ ማስታወሻ እንደገና ተልኳል።',
  telegramNoUpdateReady: 'እስካሁን ለመላክ ዝግጁ የሆነ የበዳሪ ማስታወሻ የለም።',
  telegramResendUpdateFailed: 'የበዳሪ ማስታወሻ እንደገና መላክ አልተቻለም።',
  telegramSendFailed: 'Telegram መላክ ወድቋል።',
  telegramManualInvalid: 'የእጅ Telegram እውቂያ ትክክል አይደለም።',
  telegramDubieSavedButFailed: 'ዱቤ ተቀምጧል። Telegram ማስረከብ ወድቋል።',
  confirmConnection: 'ግንኙነት አረጋግጥ',
  skipForNow: 'ለአሁን ዝለል',
  saveChanges: 'ለውጦች አስቀምጥ',
  saved: 'ተቀምጧል!',
  privacy: 'ግላዊነት',
  hideAmounts: 'መጠኖች ደብቅ',
  totalsHidden: 'ድምር ተደብቋል — ለማሳየት ተጭን',
  totalsVisible: 'ድምር ይታያል — ለመደበቅ ተጭን',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ኪስ',
  onlyEnabled: 'የተበሩ ዘዴዎች ብቻ በቅጹ ውስጥ እንደ አማራጮች ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለምታስገቡ ወጪዎች ፈጣን ማስገቢያ አቋራጮች',
  addRecurring: 'ተደጋጋሚ ወጪ ጨምር',
  demoCardSectionLabel: 'ፈጣን ማስገቢያ (ምሳሌዎች)',
  recurringExampleRent: 'ኪራይ',
  recurringExampleEqub: 'እቁብ',
  addRecurringPopupGuide: 'ይህንን እንደ ተደጋጋሚ ወጪ አስቀምጥ ማንኛውም ጊዜ እንደገና ለመጠቀም',
  addAndUse: 'ጨምር እና ተጠቀም',
  addRecurringHint: 'በቅንብሮች ውስጥ ተጨማሪ ተደጋጋሚ ወጪዎችን ማከል ትችላለህ',
  frequency: 'ድግግሞሽ',
  cancel: 'ሰርዝ',
  add: 'ጨምር',
  yourData: 'ውሂብህ',
  storedOnDevice: 'በዚህ መሣሪያ ላይ ተቀምጧል',
  exportCSV: 'ወደ CSV ላክ',
  exportHint: 'የስፕሬድሺት ባክአፕ አውርድ',
  lastBackup: 'የመጨረሻ ባክአፕ',
  noBackupYet: 'እስካሁን ባክአፕ የለም — ውሂብህን ደህና ለማቆየት ላክ',
  clearAll: 'ሁሉንም ውሂብ አጽዳ',
  clearHint: 'ሁሉንም በቋሚነት ይሰርዛል — መጀመሪያ ላክ!',
  about: 'ስለ',
  privacyNote: 'ውሂብህ ከዚህ መሣሪት ውጭ አይሄድም። ሂሳብ አያስፈልግም።',
  worksOffline: 'ያለ ኢንተርኔት ይሰራል — ውሂብ በስልክህ ላይ ይቆያል — ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ያገኘ',
  noBadges: 'ባጆች ለማግኘት ምልክቶችን ጨርስ!',
  clearConfirm: 'ሁሉንም ውሂብ ማጽዳት—',
  clearConfirmMsg: 'ይህ ሁሉንም {count} ግቤቶች እና {credits} ዱቤ መዝገቦች በቋሚነት ይሰርዛል። ይህ ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂብ ተጽዷል',
  reloading: 'እንደገና በመጫን ላይ...',
  deleteEntry: 'ይህንን ግቤት መሰረዝ—',
  delete: 'ሰርዝ',
  newBestDay: 'አዲስ ምርጥ ቀን!',
  birr: 'ብር',
  daily: 'የዕለት',
  weekly: 'የሳምንት',
  monthly: 'የወር',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  amount: 'መጠን',
  sun: 'እሑድ', mon: 'ሰኞ', tue: 'ማክሰ', wed: 'ረቡዕ', thu: 'ሐሙስ', fri: 'ዓርብ', sat: 'ቅዳሜ',
  onboardWelcome: 'ማስታወሻ ደብተርህን ጀምር',
  onboardSubtitle: 'የንግድ ማስታወሻ ደብተርህ',
  onboardTagline: 'ሽያጭ ወጪ እና ዱቤ ተከታተል',
  onboardDesc: 'በስምህ ጀምር ከዚያ ሽያጭ ወጪ እና ዱቤ በሰከንዶች መዝግብ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(ምርጫ)',
  onboardPhoneHelper: 'ስልክህን በኋላ በቅንብሮች ውስጥ ማከል ትችላለህ።',
  onboardBusinessTypeLabel: 'የንግድ አይነት',
  onboardBusinessTypeOptional: '(ምርጫ)',
  onboardBusinessTypeHelper: 'በኋላ ገበያ ፈጣን ማቅረቢያ እንዲያደርግ በጣም የሚስማማውን ምረጥ።',
  onboardBusinessTypePlaceholder: 'ወይም የንግድህን ስም ጻፍ',
  businessTypeShop: 'ሱቅ',
  businessTypeWholesale: 'ሲጥ',
  businessTypeDistributor: 'አከፋፋይ',
  businessTypeBoutique: 'ቡቲክ',
  businessTypeCafe: 'ቡና ቤት',
  businessTypeService: 'አገልግሎት',
  businessTypeOther: 'ሌላ',
  onboardPromiseSimple: 'ሽያጭ ወጪ እና ዱቤ በጥቂት ጥቅቅቅ መዝግብ',
  onboardPromiseFast: 'በስምህ ብቻ ጀምር',
  onboardPromisePrivate: 'ያለ ከባድ የሂሳብ ቃላት ማን ምን እንደሚያዝ ማየት',
  onboardGetStarted: 'ገበያን መጠቀም ጀምር',
  onboardSettingUp: 'በማዋቀር ላይ...',
  onboardFooter: 'ሁሉም ውሂብ በስልክህ ላይ ይቆያል — ሂሳብ አያስፈልግም — ነፃ',
  iSoldSomething: 'ሸጫለሁ',
  iSpentSomething: 'ወጪ አድርጌያለሁ',
  recordCredit: 'ዱቤ መዝግብ',
  addCredit: 'ተጨማሪ ዱቤ',
  addCustomer: 'ደንበኛ ጨምር',
  saveCustomer: 'ደንበኛ አስቀምጥ',
  customerSaved: 'ደንበኛ ተቀምጧል',
  customerSaveFailed: 'ደንበኛ ማስቀመጥ አልተቻለም። እባክህ እንደገና ሞክር።',
  customerHelperText: 'በኋላ የምታውቀውን ማንኛውም መለያ ተጠቀም።',
  customerIdentifier: 'የደንበኛ መለያ',
  customerIdentifierPlaceholder: 'ስም ቅጽል ግንኙነት ቦታ ወይም የመኪና ፍንጭ',
  customerNotePlaceholder: 'ይህንን ደንበኛ ለመለየት የሚረዳ ማንኛውም ነገር',
  customerPhoneOptional: 'ስልክ (ምርጫ)',
  customerPhonePlaceholder: 'ስልክ ቁጥር',
  customerTelegramOptional: 'Telegram (ምርጫ)',
  customerTelegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  customerTotalBalance: 'ጠቅላላ ሚዛን',
  customerBalance: 'ሚዛን',
  searchCustomerPlaceholder: 'ደንበኛ ወይም ማስታወሻ ፈልግ...',
  customerSearchHint: 'በስም ማስታወሻ ስልክ ወይም Telegram ፈልግ።',
  customerSearchResults: '{shown} ከ {total} ደንበኞች ማሳየት',
  noCustomersFound: 'ደንበኞች አልተገኙም',
  noCustomersYet: 'እስካሁን ደንበኞች የሉም',
  noCustomerSearchResults: 'ይህንን ፍለጋ የሚስማሙ ደንበኞች የሉም',
  backToCustomers: 'ወደ ደንበኞች ተመለስ',
  customerTransactionHistory: 'የግብይት ታሪክ',
  paymentRecordedLabel: 'ክፍያ',
  creditAddedLabel: 'ዱቤ ተጨምሯል',
  noTransactionsYet: 'እስካሁን ግብይት የለም',
  noTransactionsHint: 'ይህንን ታሪክ ለመጀመር ዱቤ ጨምር ወይም ክፍያ መዝግብ ተጠቀም።',
  currentBalance: 'የአሁን ሚዛን',
  previousBalance: 'ቀድሞ የነበረ ሚዛን',
  updatedBalance: 'የተዘመነ ሚዛን',
  currentBalanceHint: 'ይህ አዲሱን ዱቤ ካስቀመጥህ በኋላ ያለው ሚዛን ነው።',
  remainingBalanceHint: 'ይህ ክፍያውን ካስቀመጥህ በኋላ ያለው የቀረ ሚዛን ነው።',
  paymentNoteOptional: 'የክፍያ ማስታወሻ (ምርጫ)',
  itemNoteOptional: 'የዕቃ ማስታወሻ (ምርጫ)',
  paymentNotePlaceholder: 'ስለዚህ ክፍያ ማንኛውም ማስታወሻ',
  creditItemPlaceholder: 'የወሰዱት',
  savedCatalogLabel: 'የተቀመጠ ዕቃ / አገልግሎት',
  typeManually: 'በእጅ ጻፍ',
  typeNoteManually: 'ማስታወሻ በእጅ ጻፍ',
  serviceLabel: 'አገልግሎት',
  itemLabel: 'ዕቃ',
  dueDateOptional: 'የመጨረሻ ቀን (ምርጫ)',
  ethiopianDisplay: 'የኢትዮጵያ ማሳያ',
  pickDateWithEthiopianHint: 'ከታች ማንኛውንም ቀን ምረጥ እና በኢትዮጵያ ካሌንደርም እናሳያለን።',
  moreOptional: 'ተጨማሪ (ምርጫ)',
  noteLabel: 'ማስታወሻ',
  savePayment: 'ክፍያ አስቀምጥ',
  customerNotFound: 'ደንበኛ አልተገኘም',
  validAmountRequired: 'ትክክለኛ መጠን አስገባ',
  paymentMoreThanBalance: 'ክፍያው ከአሁኑ ሚዛን በላይ ነው',
  noBalanceToRecordPayment: 'እስካሁን ለመሰብሰብ ሚዛን የለም',
  balanceAfterEntry: 'ከዚህ ግቤት በኋላ ሚዛን',
  dueLabelShort: 'ጊዜ',
  whatDidYouSell: 'ምን ሸጥህ—',
  sellPlaceholder: 'ለምሳሌ ዳቦ ስኳር...',
  whatDidYouSpendOn: 'በምን ወጪ አደረግህ—',
  spendPlaceholder: 'ለምሳሌ ትራንስፖርት ኪራይ...',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ...',
  howMuchTotal: 'ጠቅላላ ሂሳብ',
  saveSale: 'ሽያጭ አስቀምጥ',
  saleSettlementLabel: 'በምን ተከፈለ',
  saleSettlementPaidNow: 'አሁን ከፍሏል',
  saleSettlementPaidNowHint: 'የቀረ ሚዛን የለም',
  saleSettlementPaidPartly: 'በከፊል ከፍሏል',
  saleSettlementPaidPartlyHint: 'አንዳንዱ አሁን ከፍሏል',
  saleSettlementPayLater: 'በኋላ ይከፍላል',
  saleSettlementPayLaterHint: 'ሁሉም ክፍት ይቆያል',
  salePaidAmountLabel: 'አሁን ስንት ከፍሏል—',
  salePaidAmountHint: 'የተከፈለ መጠን ከ0 በላይ እና ከጠቅላላው በታች መሆን አለበት።',
  saleCustomerRequiredHint: 'የቀረውን ሚዛን ማን መያዝ እንዳለበት ጨምር።',
  saleRemainingBalanceLabel: 'የቀረ ሂሳብ',
  saleRemainingBalanceHint: 'ካስቀመጥህ በኋላ የቀረው መጠን ለዚህ ደንበኛ ሚዛን ይጨመራል።',
  saleSavedWithBalance: 'ሽያጭ ተቀምጧል። የቀረ ሚዛን ለደንበኛ ይጨመራል።',
  saleLinkedBalanceTitle: 'ይህ ሽያጭ የደንበኛ ሚዛን ቀሪ አለው።',
  saleLinkedBalanceBody: 'የሽያጭ ጠቅላላ ስትቀይር የተገናኘው የቀረ ሚዛንም ይዘምናል።',
  saleRemainingHistory: 'ቀሪ',
  salePaidShort: 'ከፍሏል',
  saleLabelShort: 'ሽያጭ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ዱቤ አስቀምጥ',
  addAnotherSale: 'ተጨማሪ ሽያጭ ጨምር',
  addAnotherExpense: 'ተጨማሪ ወጪ ጨምር',
  done: 'ተጠናቋል',
  birrSaved: 'ብር ተቀምጧል',
  howMany: 'ስንት—',
  direction: 'አቅጣጫ',
  theyOweMe: 'እነሱ ይከፍሉኛል',
  iOweThem: 'እኔ እከፍላለሁ',
  owesMe: 'ይከፍሉኛል',
  iOweLabel: 'እከፍላለሁ',
  quickFill: 'ፈጣን ማስገቢያ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(ምርጫ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ነው የሚጠናቀቀው—',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'እባክህ የመጨረሻ ቀን ምረጥ',
  advancedOptional: 'የላቀ (ምርጫ)',
  whatDidYouPay: 'ለዚህ ስንት ከፈልክ—',
  perUnit: '(ለአንድ)',
  helpsSeeProfit: 'ምርጫ — እውነተኛ ትርፍህን ለማየት ይረዳል',
  sellingBelowCost: 'ከወጪ በታች እየሸጥህ ነው። በዚህ ሽያጭ ገንዘብ ልታጣ ትችላለህ።',
  profitOnSale: 'ትርፍ በዚህ ሽያጭ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ኪስ',
  editSale: 'ሽያጭ አስተካክል',
  editExpense: 'ወጪ አስተካክል',
  editCredit: 'ዱቤ አስተካክል',
  editPayment: 'ክፍያ አስተካክል',
  editEntryLabel: 'ግቤት አስተካክል',
  editedAt: 'ተስተካክሏል',
  item: 'ዕቃ',
  quantity: 'ብዛት',
  dueDate: 'የመጨረሻ ቀን',
  costPriceLabel: 'የዋጋ ዋጋ',
  sellingBelowCostShort: 'ከወጪ በታች መሸጥ።',
  profitLabel: 'ትርፍ:',
  saving: 'በማስቀመጥ ላይ...',
  todaysProfit: 'የዛሬ ትርፍ',
  estimatedProfit: 'ግምታዊ ትርፍ',
  partialCostDisclaimer: 'የጠቅላላ ወጪ ለሁሉም ዕቃዎች አልተሟላም — ትርፍ ግምታዊ ሊሆን ይችላል',
  partialCostTip: 'እውነተኛ ትርፍ ለማየት ለሁሉም ዕቃዎች የዋጋ ዋጋ አስገባ',
  todaysSales: 'የዛሬ ሽያጭ',
  salesLabel: 'ሽያጮች',
  expenses: 'ወጪዎች',
  costOfGoods: 'የዕቃዎች ወጪ',
  netProfit: 'የተጣራ ትርፍ',
  advancedHint: 'እውነተኛ ትርፍ ለማየት ሽያጭ ስትመዘግብ "የላቀ" ን ተጭን',
  tapToReveal: 'ለመግለጥ ተጭን',
  tapToRevealAria: 'መጠን ለመግለጥ ተጭን',
  hideAmountAria: 'መጠን ደብቅ',
  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  groupBy: 'ቡድን:',
  searchPlaceholder: 'በዕቃ ወይም ደንበኛ ፈልግ...',
  noSearchResults: 'ለ ውጤት የለም',
  noRecords: 'እስካሁን መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያህን ሽያጭ ወይም ወጪ መዝግብ',
  entries: 'ግቤቶች',
  revenue: 'ገቢ',
  thisWeek: 'ይህ ሳምንት',
  noCreditRecords: 'የዱቤ መዝገብ የለም',
  addCreditHint: 'አንድ ለመጨመር በዛሬ ትር ላይ "ዱቤ" ን ተጭን',
  owedToMe: 'የሚከፍለኝ',
  iOweAmount: 'የምከፍለው',
  active: 'ንቁ',
  paid: 'ከፍሏል',
  activeTab: 'ንቁ',
  paidTab: 'ከፍሏል',
  noPaidRecords: 'እስካሁን የከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተይዟል!',
  paidInFull: 'ሙሉ ከፍሏል',
  paidLabel: 'ከፍሏል',
  due: 'ጊዜ',
  owesMeLabel: 'ይከፍሉኛል',
  iOweTag: 'እኔ እከፍላለሁ',
  backToCredit: 'ወደ ዱቤ ተመለስ',
  originalDebt: 'የመጀመሪያ ጥያቄ',
  amountPaid: 'የተከፈለ መጠን',
  stillOwes: 'አሁንም ይከፍላል',
  progress: 'ሂደት',
  percentPaid: '% ከፍሏል',
  paidSome: 'አንዳንዱ ከፍሏል',
  allPaid: 'ሁሉም ከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  markFullyPaid: 'ሙሉ ከፍሏል ምልክት አድርግ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'ተበድሯል',
  paidBack: 'ተከፍሏል',
  remaining: 'ቀሪ',
  payMethodCash: 'ጥሬ ገንዘብ',
  payMethodBank: 'የባንክ ዝውውር',
  payMethodMobile: 'ሞባይል ገንዘብ',
  paymentExceedsOwed: 'መጠኑ ከሚከፍለው በላይ ሊሆን አይችልም',
  voiceNotSupported: 'ድምጽ አይደገፍም — ቁልፍ ሰሌዳ ተጠቀም',
  voiceInput: 'የድምጽ ግቤት',
  tryAgain: 'እንደገና ሞክር',
  voiceMicBlocked: 'ማይክሮፎን ታግዷል። የብራውዘር ቅንብሮችን ፈትሽ።',
  close: 'ዝጋ',
  todaysBreakdown: 'የዛሬ ዝርዝር',
  payingVia: 'በ',
  creditPhoneHint: 'በ7 ወይም 9 የሚጀምር 9 አሃዞች',
  myShop: 'ሱቄ',
  more: 'ተጨማሪ',
  frequentExpenses: 'ብዙ ጊዜ ወጪዎች',
  language: 'ቋንቋ',
  shareTodayTitle: 'የዛሬን ሪፖርት አጋራ',
  shareTodayHint: 'የዛሬን ሽያጭ ወጪ እና ዱቤ ማጠቃለያ አጋራ',
  addCustomBank: 'ባንክ ጨምር...',
  addCustomWallet: 'ኪስ ጨምር...',
  customProviderName: 'የአቅራቢ ስም',
  providerEnabled: 'ተበርቷል',
  providerDisabled: 'ጠፍቷል',
  introSlide1Title: 'የንግድ ማስታወሻ ደብተርህ',
  introSlide1Body: 'ሽያጭ ወጪ እና ዱቤ ተከታተል — ሁሉም በስልክህ ላይ። ሂሳብ አያስፈልግም።',
  introSlide2Title: 'ገንዘብህን በአንድ እይታ ማየት',
  introSlide2Body: 'ዛሬ ስንት ሸጥህ ስንት ወጪ ማን ይከፍልሃል ማየት።',
  introSlide3Title: 'ሶስት ቁልፎች። በስ',
  introSlide3Body: 'ለመሸጥ — ለወጪ — ለዱቤ — ተጭን። በ10 ሰከንድ ተጠናቋል።',
  introLetsStart: 'እንጀምር',
  introNext: 'ቀጣይ —',
  introSkip: 'ማስተዋወቅ ዝለል',
  noEntriesPrompt: 'የመጀመሪያህን ሽያጭ ለመመዝገብ ከላይ — ተጭን',
  noSalesRecordedYet: 'እስካሁን ሽያጭ አልተመዘገበም',
  recordFirstSalePrompt: 'የመጀመሪያህን ሽያጭ ለመመዝገብ ከላይ ተጭን',
  saleSaved: '— ሽያጭ ተቀምጧል — — ቀጥል',
  expenseSaved: 'ወጪ ተመዝግቧል —',
  creditSaved: 'ዱቤ ተመዝግቧል —',
  paymentSaved: 'ክፍያ ተመዝግቧል —',
  trustCardTitle: 'መዝገቦችህ ተቀምጠዋል',
  trustCardBody: 'ገበያን ዝጋ እና በኋላ ተመለስ። ሽያጭ ወጪ እና ዱቤህ አሁንም እዚያ ይሆናል።',
  trustCardAction: 'የመጀመሪያህን ሽያጭ መዝግብ',
  trustLastSaved: 'የመጨረሻ ቁጠባ',
  trustTodayCount: 'ዛሬ ተቀምጧል',
  trustReopenHint: 'አሁን ፈጣን መዝግብ እና ማንኛውም ጊዜ እንደገና ፈትሽ።',
  undone: 'ተመልሷል —',
  statusOverdue: 'ያለፈበት',
  statusDueSoon: 'በቅርቡ',
  statusOk: 'OK',
  periodDay: 'ቀን',
  periodWeek: 'ሳምንት',
  periodMonth: 'ወር',
  totalSales: 'ጠቅላላ ሽያጮች',
  totalExpenses: 'ጠቅላላ ወጪዎች',
  topProductsWeek: 'ከፍተኛ ዕቃዎች ይህ ሳምንት',
  topProductsMonth: 'ከፍተኛ ዕቃዎች ይህ ወር',
  topProductsDay: 'ከፍተኛ ዕቃዎች ዛሬ',
  byQuantity: 'በብዛት',
  byRevenue: 'በገቢ',
  weekBreakdown: 'ቀን በቀን',
  monthBreakdown: 'ሳምንት በሳምንት',
  weekOf: 'ሳምንት',
  noSalesThisPeriod: 'በዚህ ጊዜ ሽያጭ የለም',
  week: 'ሳም',
  recordByVoice: 'ሽያጭ ለመመዝገብ ተናገር',
  recordByVoiceSubLabel: 'ሽያጭ ለመመዝገብ ፈጣኑ መንገድ',
  typeSale: 'ሽያጭ ጻፍ',
  typeSaleLabel: 'ሽያጭ ጻፍ',
  voiceRecordingTitle: 'በመቅረጽ ላይ...',
  voiceRecordingHint: 'የሽያጭ መጠንህን ተናገር',
  voiceStop: 'ቁም',
  voiceTypeInstead: 'ደግሞ ጻፍ',
  voiceNoInternet: 'ኢንተርኔት ግንኙነት የለም',
  voiceNoInternetHint: 'የድምጽ ቅጂ ኢንተርኔት ይፈልጋል። ሽያጭህን ማስገባት ትችላለህ።',
  voiceTypeSaleInstead: 'ሽያጭ ጻፍ',
  voiceRetry: 'እንደገና ሞክር',
  voiceTryFinishSoon: '— በቅርቡ ለማጠናቀቅ ሞክር',
  voiceListeningState: 'በማዳመጥ ላይ',
  voiceStoppedState: 'ቆሟል',
  voiceProcessingState: 'በማቀነባበር ላይ',
  voiceLivePreview: 'የምንሰማው',
  voiceLivePreviewHint: 'ቃላትህ ከመቀመጥህ በፊት እዚህ ማሳየት አለባቸው።',
  voiceResultTitle: 'የድምጽ ውጤት',
  voiceTranscript: 'የምልክት',
  voiceDetectedTotal: 'የተገኘ ጠቅላላ',
  voiceNoAmount: 'መጠን አልተገኘም',
  voiceNeedsReview: 'ከመቀመጥህ በፊት ይህንን ክፍያ ፈትሽ።',
  voiceParsedItems: 'የተተረጎሙ ዕቃዎች',
  voiceCustomerName: 'ደንበኛ',
  voiceCustomerPlaceholder: 'ከተጠቀሰ የደንበኛ ስም',
  voiceIntent: 'ዓላማ',
  voiceIntentSale: 'ሽያጭ',
  voiceIntentCredit: 'ዱቤ',
  voiceIntentPayment: 'ክፍያ',
  voiceQuantity: 'ብዛት',
  voiceUnitPrice: 'የአሃድ ዋጋ',
  voiceAutoCalculatedTotal: 'ጠቅላላ በራስ-ሰር ከዕቃ ዝርዝር ተሰልቷል።',
  voiceItemNamePlaceholder: 'የዕቃ ስም',
  voiceSave: 'ሽያጭ አስቀምጥ',
  voiceFix: 'አስተካክል እና አርትዕ',
  voiceReRecord: 'እንደገና ቅረጽ',
  voiceFixTitle: 'የድምጽ ሽያጭ አስተካክል',
  voiceTotalLabel: 'ጠቅላላ መጠን',
  voiceNoteLabel: 'ማስታወሻ (ምርጫ)',
  voiceNotePlaceholder: 'ለምሳሌ ዳቦ ስኳር...',
  voiceSaleSaved: 'የድምጽ ሽያጭ ተቀምጧል —',
  voiceAddAnotherItem: 'ተጨማሪ ዕቃ ጨምር',
  voiceRunningTotal: 'የሂደት ጠቅላላ',
  voiceItemsRecorded: 'ዕቃዎች ተመዝግበዋል',
  voiceSalesOnlyTitle: 'ድምጭ አሁን ለሽያጭ ብቻ ነው።',
  voiceSalesOnlyBody: 'ይህ ክፍያ እንደ ዱቤ ወይም ክፍ ይመስላል። ከመቀመጥህ በፊት ጥንቃቄ አድርግ።',
  telegramLinkedOnTelegram: 'በዳሪ በ Telegram ተገናኝቷል።',
  telegramWaitingForBorrower: 'በዳሪ ቦቱን እስኪጀምር ይጠብቃል።',
  telegramServiceUnavailableNow: 'የ Telegram አገልግሎት አሁን አይገኝም።',
  telegramManualStillWorks: 'የ Telegram አገልግሎት አሁን አይገኝም። የእጅ እውቂያ አሁንም ይሰራል።',
  telegramLinkedUpdatesReady: 'የተገናኘ በዳሪ ማስታወሻዎች ዝግጁ ናቸው።',
  telegramGenerateLinkHint: 'የበዳሪ አገናኝ ፍጠር ከዚያ በ Telegram ውስጥ ስካን ወይም ክፈት ይበሉት።',
  telegramOpenBot: 'ቦት ክፈት',
  telegramRefreshStatus: 'ሁኔታ አድስ',
  telegramBorrowerStartedAs: 'በዳሪ ቦቱን እንደ {username} ጀምሯል',
  telegramLinkingUnavailable: 'የራስ-ሰር የ Telegram ማገናኘት አሁን አይገኝም።',
  telegramManualCanEnableLater: 'አሁንም ከታች የእጅ Telegram እውቂያ ማስቀመጥ ትችላለህ እና የራስ-ሰር ማስታወሻዎችን በኋላ ማብራት ትችላለህ።',
  telegramApiServerNeeded: 'አሁንም ከታች የእጅ Telegram እውቂያ ማስቀመጥ ትችላለህ። የቦት ማገናኘት እና የራስ-ሰር ማስታወሻዎች API አገልግሎት ያስፈልጋቸዋል።',
  telegramSaveFallbackContact: 'የተተኪ እውቂያ አስቀምጥ',
  telegramResending: 'እንደገና በመላክ ላይ...',
  telegramResendLatestUpdate: 'የመጨረሻ ማስታወሻ እንደገና ላክ',
  stepDetails: 'ዝርዝሮች',
  stepPayment: 'ክፍያ',
  stepReview: 'ግምገማ',
  stepDetailsAm: 'ዝርዝሮች',
  stepPaymentAm: 'ክፍያ',
  stepReviewAm: 'ግምገማ',
  editDetails: 'ዝርዝሮች አርትዕ',
  next: 'ቀጣይ',
  back: 'ተመለስ',
  enterItemName: 'የዕቃ ስም አስገባ',
  enterCustomerName: 'የደንበኛ ስም አስገባ',
  draftSaved: 'ክፍያ ተቀምጧል',
  keepDraft: 'ክፍያ አቆይ',
  discardDraft: 'ወገድ',
  reviewSale: 'ሽያጭ ግምገማ',
  photoAttached: 'ፎቶ ተገጥሟል',
  noPaymentCollected: 'አሁን ምንም ክፍያ አልተሰበሰበም። ይህ ሽያጭ ወደ ዱቤ ይጨመራል።',
  settlementPaidNow: 'አሁን ከፍሏል',
  settlementPaidPartly: 'በከፊል ከፍሏል',
  settlementPayLater: 'በኋላ ይከፍላል',
  reviewTotal: 'ጠቅላላ',
  reviewItem: 'ዕቃ',
  reviewSettlement: 'ሂሳብ',
  reviewProvider: 'አቅራቢ',
  reviewPaidAmount: 'የተከፈለ መጠን',
  reviewRemaining: 'ቀሪ',
  reviewCustomer: 'ደንበኛ',
  reviewReturnDate: 'የመመለሻ ቀን',

  supplierDubieSaved: 'የአቅራቢ ዱቤ ተመዝግቧል',
  toCollect: 'የምሰበስብ',
  toPay: 'የምከፍል',
  supplierSaveFailed: 'አቅራቢ ማስቀመጥ አልተሳካም። እባክህ እንደገና ሞክር',
  addAmountOwed: 'ዕዳ ጨምር',
  saveAmountOwed: 'አስቀምጥ',
  newBalance: 'አዲስ',

  dubieExistingCustomer: 'ያለ ደንበኛ',
  dubieAddTitle: 'ዱቤ ጨምር',
  dubieSearchHint: 'ደንበኛ ፈልግ ወይም የቅርብ ጊዜ ደንበኛ ምረጥ',
  dubieSearchPlaceholder: 'ደንበኛ ፈልግ',
  dubieNewCustomer: 'አዲስ ደንበኛ',
  dubieOpenBalanceCustomers: 'ቀሪ ያለባቸው ደንበኞች',
  dubieRecentCustomers: 'የቅርብ ጊዜ ደንበኞች',
  dubieShown: 'የሚታዩ',
  dubieNoCustomerFound: 'ደንበኛ አልተገኘም',
  dubieTryAnother: 'ሌላ ስም ሞክር ወይም አዲስ ደንበኛ ጨምር',
  dubieRemainingBalance: 'ቀሪ ሚዛን',

  newCustomerTitle: 'አዲስ ደንበኛ',
  newCustomerHint: 'ማስታወሻ ለመላክ የመገናኛ መረጃ ያስፈልጋል',
  customerNameLabel: 'የደንበኛ ስም',
  customerNamePlaceholder: 'የደንበኛ ስም',
  mobileNumberLabel: 'ስልክ ቁጥር',
  pickFromContacts: 'ካነጋገርኩት ምረጥ',
  phoneMustStartWith7or9: 'ስልክ በ 7 ወይም 9 መጀመር አለበት (9 አሃዞች)',
  smsRemindersHint: 'የSMS ማስታወሻ ስልክ ቁጥር ያስፈልጋል',
  telegramLaterHint: 'የቦት ግንኙነት በኋላ ሊጨመር ይችላል',

  editAmountOwed: 'ዕዳ አርትዕ',
  moreThanRemainingBalance: 'ከቀሪ ሚዛን በላይ ነው',
  whatWasPurchased: 'የተገዛ ነገር',
  itemNotePlaceholder: 'የተገዛ ነገር',
  saveSupplier: 'አቅራቢ አስቀምጥ',
  addSupplier: 'አቅራቢ ጨምር',
  supplierName: 'የአቅራቢ ስም',
  supplierNamePlaceholder: 'የአቅራቢ ስም',
  supplierNotePlaceholder: 'ማስታወሻ',
  mobileNumber: 'ስልክ ቁጥር',
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gebya_lang') || 'en');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.body.dataset.lang = lang;
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'am' : 'en';
      localStorage.setItem('gebya_lang', next);
      return next;
    });
  };

  const t = lang === 'am' ? AM : EN;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
