import { createContext, useContext, useEffect, useState } from 'react';
// NATIVE-SPEAKER VERIFICATION REQUIRED
// All Amharic (AM) strings below were machine-translated and have NOT been
// reviewed by a native Amharic speaker. Before public launch, every string in
// the AM object must be verified and corrected by a native speaker, especially
// financial/business terminology, verb forms, and formal/informal register.
// Do NOT ship to production without completing this review.


const EN = {
  installSectionTitle: 'Install App',
  installBannerTitle: 'Install Gebya on this phone',
  installBannerBody: 'Add Gebya to your home screen so you can open it like an app.',
  installNow: 'Install Now',
  installHowTo: 'Install',
  installGuideButton: 'How to install',
  installGuideTitle: 'Install Gebya on your phone',
  installGuideHint: 'Do this once, then open Gebya from your phone home screen.',
  installGuideDeviceTitle: 'Phone install steps',
  installAlreadyInstalled: 'Already installed',
  installStatusInstalled: 'Installed on your home screen',
  installStatusBrowser: 'Running in browser mode',
  installStatusOnline: 'Online now',
  installStatusOffline: 'Offline now',
  installChecklistOffline: 'Offline-ready notebook',
  installChecklistHomeScreen: 'Home screen install',
  installChecklistData: 'Data location',
  installChecklistReady: 'Ready',
  installChecklistInstalled: 'Installed',
  installChecklistPending: 'Not yet',
  installChecklistOnPhone: 'This phone',
  installIosStep1: 'Open Gebya in Safari.',
  installIosStep2: 'Tap Share, then tap "Add to Home Screen."',
  installIosStep3: 'Tap "Add", then open Gebya from your home screen.',
  installAndroidStep1: 'Open Gebya in Chrome.',
  installAndroidStep2: 'Open the browser menu and tap "Install app" or "Add to Home screen."',
  installAndroidStep3: 'Confirm, then open Gebya from your home screen.',
  installGenericStep1: 'Open Gebya in your phone browser.',
  installGenericStep2: 'Open the browser menu and look for "Install app" or "Add to Home Screen."',
  installGenericStep3: 'Save it, then open Gebya from your home screen.',
  updateReadyTitle: 'Fresh version ready',
  updateReadyBody: 'A newer app version is available. Refresh once to use the latest installable build.',
  refreshApp: 'Refresh App',
  offlineReadyTitle: 'Offline mode is ready',
  offlineReadyBody: 'Gebya can reopen even when your connection is weak, and your saved notebook stays on this phone.',
  offlineNowTitle: 'You are offline',
  offlineNowBody: 'Your saved notebook on this phone still works. Features that need internet may wait until you reconnect.',
  notNow: 'Not now',
  telegramNotifyConnectFirst: 'Connect Telegram first, then turn this on.',
  telegramConnectFirstToast: 'Connect Telegram first to send updates.',
  appName: 'ገበያ',
  loading: 'Loading your notebook…',
  today: 'Today',
  todayLabel: 'ዛሬ',
  credit: 'Dubie',
  creditLabel: 'ዱቤ',
  report: 'Report',
  settings: 'Settings',
  sales: 'Sales',
  spent: 'Spent',
  iSold: 'I Sold',
  iSoldLabel: 'ሸጠሁ',
  iSpent: 'I Spent',
  iSpentLabel: 'ወጪ',
  creditBtn: 'Dubie',
  creditBtnLabel: 'ዱቤ',
  calc: 'Calc',
  todaysEntries: "Today's Entries",
  noEntries: 'No entries yet. Use the buttons above to start!',
  profit: 'profit',
  edited: 'edited',
  editEntry: 'Edit entry',
  deleteEntryLabel: 'Delete entry',
  calculator: 'Profit Calculator',
  calcCost: 'Cost Price',
  calcSell: 'Selling Price',
  calcProfit: 'Profit',
  calcMargin: 'Margin',
  calcPlaceholder: 'Enter amount…',
  topProducts: 'Top Sold Today',
  weekTrend: '7-Day Trend',
  shareReport: 'Share Report',
  shareReportBtn: 'Share Today',
  shareTitle: 'Share Daily Report',
  shareDailyReport: 'Daily Report',
  shareTopItems: 'Top Items Sold',
  shareSentVia: 'Sent via ገበያ (Gebya)',
  dubieGiven: 'Dubie Given',
  paymentsCollected: 'Payments Collected',
  netReceived: 'Net Received',
  shareViaDevice: 'Share via Device',
  openTelegram: 'Open in Telegram',
  copyText: 'Copy Text',
  usageInsights: 'Usage Insights',
  dayStreak: 'day streak',
  best: 'best',
  daysActive: 'days active',
  since: 'since',
  totalEntries: 'entries',
  sessions: 'sessions opened',
  shareMyStats: 'Share My Stats ??',
  copiedToClipboard: 'Copied to clipboard!',
  shopProfile: 'Profile',
  userName: 'Name',
  phoneNumber: 'Phone Number',
  phoneRequired: 'Phone number is required',
  phoneInvalid: '9 digits starting with 7 or 9',
  telegramLabel: 'Telegram / Contact',
  telegramPlaceholder: '@username, t.me/... or https://t.me/...',
  connectTelegram: 'Connect Telegram',
  manageTelegram: 'Manage Telegram',
  telegramConnection: 'Telegram connection',
  telegramConnectHint: 'Link Telegram once, then turn on balance updates when you want.',
  telegramConnectedHint: 'This customer can receive Telegram balance updates.',
  notifyOnTelegram: 'Notify on Telegram',
  notifyOnTelegramHint: 'Open Telegram automatically after saving Dubie or payment.',
  telegramNotifyEnabledState: 'Automatic Telegram opening is on for this customer.',
  telegramNotifyDisabledState: 'Telegram stays optional and will not open automatically.',
  telegramNeedContactHint: 'Add a Telegram username or link first, then turn notifications on.',
  telegramFormatHint: 'Use only @username, t.me/... or https://t.me/...',
  telegramManualDraftHint: 'Manual Telegram updates will open a drafted message after each save.',
  telegramAutoUpdatesTitle: 'Automatic balance updates',
  telegramAutoUpdatesBody: 'Once linked, this customer can receive Telegram updates whenever their balance changes.',
  telegramBorrowerUpdatesLinked: 'Borrower updates are linked to the Gebya bot.',
  telegramBorrowerLinkWaiting: 'Borrower link is waiting for the bot start.',
  telegramManualSavedNotLinked: 'Manual Telegram contact is saved, but bot updates are not linked yet.',
  telegramBorrowerNeedsBotStart: 'Borrower still needs to start the Gebya bot before updates can send.',
  telegramDraftUntilLinked: 'Updates can open as a drafted Telegram message until the borrower links the Gebya bot.',
  telegramLinkBeforeUpdates: 'Link the borrower to the Gebya bot before turning updates on.',
  telegramBorrowerNotStarted: 'Borrower has not started the bot yet.',
  qrPrimaryMethod: 'QR code',
  telegramQrHint: 'Let the customer scan this QR code to open the Telegram connection link.',
  shareInviteLink: 'Share invite link',
  shareInviteLinkHint: 'Copy this link and send it through any channel you already use.',
  copyLink: 'Copy link',
  inviteLinkCopied: 'Invite link copied',
  copyFailed: 'Could not copy link',
  manualTelegramFallback: 'Manual fallback',
  manualTelegramFallbackHint: 'If needed, enter the customer Telegram username or t.me link manually.',
  telegramGenerateBorrowerLinkFirst: 'Generate a Telegram borrower link first.',
  telegramLatestUpdateSentAgain: 'Latest borrower update sent again.',
  telegramNoUpdateReady: 'No borrower update is ready to resend yet.',
  telegramResendUpdateFailed: 'Could not resend the borrower update.',
  telegramSendFailed: 'Telegram send failed.',
  telegramManualInvalid: 'Manual Telegram contact is invalid.',
  telegramDubieSavedButFailed: 'Dubie saved. Telegram delivery failed.',
  confirmConnection: 'Confirm Connection',
  skipForNow: 'Skip for Now',
  saveChanges: 'Save Changes',
  saved: 'Saved!',
  privacy: 'Privacy',
  hideAmounts: 'Hide amounts',
  totalsHidden: 'Totals are hidden — tap to show',
  totalsVisible: 'Totals are visible — tap to hide',
  paymentMethods: 'Payment Methods',
  banks: 'Banks',
  mobileWallets: 'Mobile Wallets',
  onlyEnabled: 'Only enabled methods appear as options in the form',
  recurringExpenses: 'Recurring Expenses',
  recurringHint: 'Quick-fill shortcuts for expenses you enter often',
  addRecurring: 'Add recurring expense',
  demoCardSectionLabel: 'Quick-fill (examples)',
  recurringExampleRent: 'Rent',
  recurringExampleEqub: 'Equb',
  addRecurringPopupGuide: 'Save this as a recurring expense to reuse it anytime',
  addAndUse: 'Add & Use',
  addRecurringHint: 'You can add more recurring expenses in Settings',
  frequency: 'Frequency',
  cancel: 'Cancel',
  add: 'Add',
  yourData: 'Your Data',
  storedOnDevice: 'Stored on this device',
  exportCSV: 'Export to CSV',
  exportHint: 'Download a spreadsheet backup',
  clearAll: 'Clear all data',
  clearHint: 'Permanently deletes everything — export first!',
  about: 'About',
  privacyNote: 'Your data never leaves this device. No account needed.',
  worksOffline: 'Works offline · Data stays on your phone · Free',
  achievementBadges: 'Achievement Badges',
  badgesEarned: 'earned',
  noBadges: 'Complete milestones to earn badges!',
  clearConfirm: 'Clear all data?',
  clearConfirmMsg: 'This will permanently delete all {count} entries and {credits} Dubie records. This cannot be undone.',
  yesDelete: 'Yes, delete everything',
  dataCleared: 'Data cleared',
  reloading: 'Reloading…',
  deleteEntry: 'Delete this entry?',
  delete: 'Delete',
  newBestDay: '?? New best day!',
  birr: 'birr',
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  expenseName: 'Expense name (e.g. Rent)',
  amount: 'Amount',
  sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',

  onboardWelcome: 'Start your notebook',
  onboardSubtitle: 'Your business notebook',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'Start with your name, then record sales, spending, and Dubie in seconds.',
  onboardNamePlaceholder: 'e.g. Tigist',
  onboardPhoneOptional: '(optional)',
  onboardPhoneHelper: 'You can add your phone later in Settings.',
  onboardBusinessTypeLabel: 'Business type',
  onboardBusinessTypeOptional: '(optional)',
  onboardBusinessTypeHelper: 'Pick what fits best so Gebya can suggest faster later.',
  onboardBusinessTypePlaceholder: 'Or type your business',
  businessTypeShop: 'Shop',
  businessTypeWholesale: 'Wholesale',
  businessTypeDistributor: 'Distributor',
  businessTypeBoutique: 'Boutique',
  businessTypeCafe: 'Cafe',
  businessTypeService: 'Service',
  businessTypeOther: 'Other',
  onboardPromiseSimple: 'Record sales, spending, and Dubie in a few taps',
  onboardPromiseFast: 'Start with your name only',
  onboardPromisePrivate: 'See who owes what without hard accounting words',
  onboardGetStarted: 'Start using Gebya',
  onboardSettingUp: 'Setting up…',
  onboardFooter: 'All data stays on your phone · No account needed · Free',

  iSoldSomething: 'I Sold Something',
  iSpentSomething: 'I Spent Something',
  recordCredit: 'Record Dubie',
  addCredit: 'Add Dubie',
  addCustomer: 'Add Customer',
  saveCustomer: 'Save customer',
  customerSaved: 'Customer saved',
  customerSaveFailed: 'Could not save customer. Please try again.',
  customerHelperText: 'Use any label you will recognize later.',
  customerIdentifier: 'Customer identifier',
  customerIdentifierPlaceholder: 'Name, nickname, relation, place, or vehicle clue',
  customerNotePlaceholder: 'Anything that helps you recognize this customer',
  customerPhoneOptional: 'Phone (optional)',
  customerPhonePlaceholder: 'Phone number',
  customerTelegramOptional: 'Telegram (optional)',
  customerTelegramPlaceholder: '@username, t.me/... or https://t.me/...',
  customerTotalBalance: 'Total Balance',
  customerBalance: 'Balance',
  searchCustomerPlaceholder: 'Search customer or note...',
  customerSearchHint: 'Search by name, note, phone, or Telegram.',
  customerSearchResults: 'Showing {shown} of {total} customers',
  noCustomersFound: 'No customers found',
  noCustomersYet: 'No customers yet',
  noCustomerSearchResults: 'No customers match this search',
  backToCustomers: 'Back to customers',
  customerTransactionHistory: 'Transaction History',
  paymentRecordedLabel: 'Payment',
  creditAddedLabel: 'Dubie added',
  noTransactionsYet: 'No transactions yet',
  noTransactionsHint: 'Use Add Dubie or Record Payment to start this history.',
  currentBalance: 'Current Balance',
  previousBalance: 'Previous balance',
  updatedBalance: 'Updated balance',
  currentBalanceHint: 'This is the balance after saving the new Dubie.',
  remainingBalanceHint: 'This is the remaining balance after saving the payment.',
  paymentNoteOptional: 'Payment note (optional)',
  itemNoteOptional: 'Item note (optional)',
  paymentNotePlaceholder: 'Any note about this payment',
  creditItemPlaceholder: 'What they took',
  savedCatalogLabel: 'Saved item / service',
  typeManually: 'Type manually',
  typeNoteManually: 'Type note manually',
  serviceLabel: 'Service',
  itemLabel: 'Item',
  dueDateOptional: 'Due date (optional)',
  ethiopianDisplay: 'Ethiopian display',
  pickDateWithEthiopianHint: 'Choose any date below and we will also show it in Ethiopian calendar.',
  moreOptional: 'More (optional)',
  noteLabel: 'Note',
  savePayment: 'Save payment',
  customerNotFound: 'Customer not found',
  validAmountRequired: 'Enter a valid amount',
  paymentMoreThanBalance: 'Payment is more than the current balance',
  noBalanceToRecordPayment: 'No balance to collect yet',
  balanceAfterEntry: 'Balance after this entry',
  dueLabelShort: 'Due',
  whatDidYouSell: 'What did you sell?',
  sellPlaceholder: 'e.g. bread, sugar…',
  whatDidYouSpendOn: 'What did you spend on?',
  spendPlaceholder: 'e.g. transport, rent…',
  creditNameLabel: 'Name',
  creditNamePlaceholder: 'e.g. Abebe…',
  howMuchTotal: 'How much total?',
  saveSale: 'Save Sale',
  saleSettlementLabel: 'How was it paid?',
  saleSettlementPaidNow: 'Paid now',
  saleSettlementPaidNowHint: 'No balance left',
  saleSettlementPaidPartly: 'Paid partly',
  saleSettlementPaidPartlyHint: 'Some paid now',
  saleSettlementPayLater: 'Pay later',
  saleSettlementPayLaterHint: 'All stays open',
  salePaidAmountLabel: 'How much was paid now?',
  salePaidAmountHint: 'Paid amount must be more than 0 and less than the total.',
  saleCustomerRequiredHint: 'Add who should keep the remaining balance.',
  saleRemainingBalanceLabel: 'Remaining balance',
  saleRemainingBalanceHint: 'After saving, the remaining amount will be added to this customer balance.',
  saleSavedWithBalance: 'Sale saved. Remaining balance added to customer.',
  saleLinkedBalanceTitle: 'This sale has remaining customer balance.',
  saleLinkedBalanceBody: 'If you change the sale total, the linked remaining balance will update too.',
  saleRemainingHistory: 'Remaining',
  salePaidShort: 'paid',
  saleLabelShort: 'Sale',
  saveExpense: 'Save Expense',
  saveCredit: 'Save Dubie',
  addAnotherSale: 'Add another sale',
  addAnotherExpense: 'Add another expense',
  done: 'Done',
  birrSaved: 'birr saved',
  howMany: 'How many?',
  direction: 'Direction',
  theyOweMe: 'They owe me',
  iOweThem: 'I owe them',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'Quick-fill',
  phoneOptional: 'Phone number',
  phoneOptionalHint: '(optional)',
  phonePlaceholder: 'e.g. 0912345678',
  whenDue: 'When is it due?',
  pickDate: 'Pick a date',
  selectDueDate: 'Please select a due date',
  advancedOptional: 'Advanced (optional)',
  whatDidYouPay: 'What did you pay for this?',
  perUnit: '(per unit)',
  helpsSeeProfit: 'Optional — helps you see your true profit',
  sellingBelowCost: 'You are selling below cost. You may lose money on this sale.',
  profitOnSale: 'Profit on this sale:',
  paymentType: 'Payment type',
  cash: 'Cash',
  bank: 'Bank',
  wallet: 'Wallet',

  editSale: 'Edit Sale',
  editExpense: 'Edit Expense',
  editCredit: 'Edit Dubie',
  editPayment: 'Edit Payment',
  editEntryLabel: 'Edit Entry',
  editedAt: 'Edited',
  item: 'Item',
  quantity: 'Quantity',
  dueDate: 'Due date',
  costPriceLabel: 'Cost price',
  sellingBelowCostShort: 'Selling below cost.',
  profitLabel: 'Profit:',
  saving: 'Saving…',

  todaysProfit: "Today's Profit",
  estimatedProfit: "Estimated Profit",
  partialCostDisclaimer: "Some items are missing a cost price ? this estimate may be lower than your actual profit",
  partialCostTip: "Add cost prices to your items for an accurate profit figure",
  todaysSales: "Today's Sales",
  salesLabel: 'Sales',
  expenses: 'Expenses',
  costOfGoods: 'Cost of goods',
  netProfit: 'Net Profit',
  advancedHint: 'Tap "Advanced" when recording a sale to see true profit',

  tapToReveal: 'Tap to reveal',
  tapToRevealAria: 'Tap to reveal amount',
  hideAmountAria: 'Hide amount',

  byDay: 'By Day',
  byWeek: 'By Week',
  groupBy: 'Group:',
  searchPlaceholder: 'Search by item or customer…',
  noSearchResults: 'No results for',
  noRecords: 'No records yet',
  startRecording: 'Record your first sale or expense to start',
  entries: 'entries',
  revenue: 'revenue',
  thisWeek: 'This Week',

  noCreditRecords: 'No Dubie records',
  addCreditHint: 'Tap "ዱቤ" on the Today tab to add one',
  owedToMe: 'Owed to me',
  iOweAmount: 'I owe',
  active: 'active',
  paid: 'paid',
  activeTab: 'Active',
  paidTab: 'Paid',
  noPaidRecords: 'No paid records yet',
  allCaughtUp: 'All caught up!',
  paidInFull: 'Paid in full',
  paidLabel: 'PAID',
  due: 'Due',
  owesMeLabel: 'Owes me',
  iOweTag: 'I owe',

  backToCredit: 'Back to ዱቤ',
  originalDebt: 'Original debt',
  amountPaid: 'Amount paid',
  stillOwes: 'Still owes',
  progress: 'Progress',
  percentPaid: '% paid',
  paidSome: 'Paid Some',
  allPaid: 'All Paid',
  call: 'Call',
  recordPartialPayment: 'Record Partial Payment',
  recordPayment: 'Record Payment',
  markFullyPaid: 'Mark Fully Paid',
  paymentHistory: 'Payment history',
  borrowed: 'Borrowed',
  paidBack: 'Paid back',
  remaining: 'Remaining',
  payMethodCash: 'Cash',
  payMethodBank: 'Bank Transfer',
  payMethodMobile: 'Mobile Money',
  paymentExceedsOwed: 'Amount cannot exceed what is owed',

  voiceNotSupported: 'Voice not supported — use keyboard',
  voiceInput: 'Voice input',
  tryAgain: 'Try again',
  voiceMicBlocked: 'Microphone is blocked. Check browser settings.',

  exportAuthRequired: 'Authentication required',
   incorrectPin: 'Incorrect PIN',
   enterPinPlaceholder: 'Enter PIN',
   enterPinToExport: 'Enter your PIN to export',
   typeDeleteConfirm: 'Type DELETE to confirm',
   yesDelete: 'Yes, delete everything',

   close: 'Close',

  todaysBreakdown: "Today's Breakdown",
  payingVia: 'Paying via',
  creditPhoneHint: '9 digits starting with 7 or 9',
  myShop: 'My Shop',
  more: 'More',
  frequentExpenses: 'Frequent Expenses',
  shareTodayTitle: "Share Today's Report",
  shareTodayHint: "Send today's shop summary to the owner or keep a copy.",
  addCustomBank: 'Add bank…',
  addCustomWallet: 'Add wallet…',
  customProviderName: 'Provider name',
  providerEnabled: 'Enabled',
  providerDisabled: 'Disabled',

  introSlide1Title: 'Your Business Notebook',
  introSlide1Body: 'Track sales, expenses, and Dubie — all on your phone. No account needed.',
  introSlide2Title: 'See Your Money at a Glance',
  introSlide2Body: "Today's profit always shows at the top. Know where you stand in seconds.",
  introSlide3Title: 'Three Buttons. That\'s It.',
  introSlide3Body: 'Tap ሸጠሁ to sell, ወጪ to spend, ዱቤ for Dubie. Done in 10 seconds.',
  introLetsStart: "Let's Start 🚀",
  introNext: 'Next ?',
  introSkip: 'Skip intro',

  noEntriesPrompt: 'Tap ሸጠሁ above to record your first sale',
  noSalesRecordedYet: 'No sales recorded yet',
  recordFirstSalePrompt: 'Tap above to record your first sale',

  saleSaved: '? Sale saved ? ?? Keep going',
  expenseSaved: 'Expense recorded ?',
  creditSaved: 'Dubie recorded ?',
  paymentSaved: 'Payment recorded ?',
  trustCardTitle: 'Your records are saved',
  trustCardBody: 'Close Gebya and come back later. Your sales, spending, and Dubie will still be here.',
  trustCardAction: 'Record your first sale',
  trustLastSaved: 'Last saved',
  trustTodayCount: 'saved today',
  trustReopenHint: 'Record fast now, check it again anytime.',
  undone: 'Undone ?',

  statusOverdue: 'OVERDUE',
  statusDueSoon: 'DUE SOON',
  statusOk: 'OK',

  periodDay: 'Day',
  periodWeek: 'Week',
  periodMonth: 'Month',
  totalSales: 'Total Sales',
  totalExpenses: 'Total Expenses',
  topProductsWeek: 'Top Products This Week',
  topProductsMonth: 'Top Products This Month',
  topProductsDay: 'Top Products Today',
  byQuantity: 'by qty',
  byRevenue: 'by revenue',
  weekBreakdown: 'Day-by-Day',
  monthBreakdown: 'Week-by-Week',
  weekOf: 'Week of',
  noSalesThisPeriod: 'No sales this period',
  week: 'Wk',

  recordByVoice: 'Speak to Record Sale',
  recordByVoiceSubLabel: 'Fastest way to save a sale',
  typeSale: 'Type Sale',
  typeSaleLabel: 'Type Sale',
  voiceRecordingTitle: 'Recording…',
  voiceRecordingHint: 'Speak your sale amount',
  voiceStop: 'Stop',
  voiceTypeInstead: 'Type instead',
  voiceNoInternet: 'No internet connection',
  voiceNoInternetHint: 'Voice transcription requires internet. You can still type your sale.',
  voiceTypeSaleInstead: 'Type Sale Instead',
  voiceRetry: 'Retry',
  voiceTryFinishSoon: '?? Try to finish soon',
  voiceListeningState: 'Listening',
  voiceStoppedState: 'Stopped',
  voiceProcessingState: 'Processing',
  voiceLivePreview: 'What we hear',
  voiceLivePreviewHint: 'Your words should show here before saving.',
  voiceResultTitle: 'Voice Result',
  voiceTranscript: 'What you said',
  voiceDetectedTotal: 'Detected total',
  voiceNoAmount: 'No amount detected',
  voiceNeedsReview: 'Check this draft before saving.',
  voiceParsedItems: 'Parsed items',
  voiceCustomerName: 'Customer',
  voiceCustomerPlaceholder: 'Customer name if mentioned',
  voiceIntent: 'Intent',
  voiceIntentSale: 'Sale',
  voiceIntentCredit: 'Dubie',
  voiceIntentPayment: 'Payment',
  voiceQuantity: 'Qty',
  voiceUnitPrice: 'Unit price',
  voiceAutoCalculatedTotal: 'Total auto-calculated from line items.',
  voiceItemNamePlaceholder: 'Item name',
  voiceSave: 'Save Sale',
  voiceFix: 'Fix & Edit',
  voiceReRecord: 'Re-record',
  voiceFixTitle: 'Fix Voice Sale',
  voiceTotalLabel: 'Total amount',
  voiceNoteLabel: 'Note (optional)',
  voiceNotePlaceholder: 'e.g. bread, sugar…',
  voiceSaleSaved: 'Voice sale saved ?',
  voiceAddAnotherItem: 'Add another item',
  voiceRunningTotal: 'Running Total',
  voiceItemsRecorded: 'items recorded',
  voiceSalesOnlyTitle: 'Voice is sales-only right now.',
  voiceSalesOnlyBody: 'This draft sounded like Dubie or payment. Review it carefully before saving it as a sale.',
  telegramLinkedOnTelegram: 'Borrower is linked on Telegram.',
  telegramWaitingForBorrower: 'Waiting for borrower to start the bot.',
  telegramServiceUnavailableNow: 'Telegram service is unavailable right now.',
  telegramManualStillWorks: 'Telegram service is unavailable right now. Manual contact still works.',
  telegramLinkedUpdatesReady: 'Linked borrower updates are ready.',
  telegramGenerateLinkHint: 'Generate the borrower link, then let them scan or open it in Telegram.',
  telegramOpenBot: 'Open Bot',
  telegramRefreshStatus: 'Refresh status',
  telegramBorrowerStartedAs: 'Borrower started the bot as {username}',
  telegramLinkingUnavailable: 'Automatic Telegram linking is not available right now.',
  telegramManualCanEnableLater: 'You can still save a manual Telegram contact below and enable automatic updates later.',
  telegramApiServerNeeded: 'You can still save a manual Telegram contact below. Bot linking and automatic updates need the API server to be available.',
  telegramSaveFallbackContact: 'Save fallback contact',
  telegramResending: 'Resending...',
  telegramResendLatestUpdate: 'Resend latest update',

  stepDetails: 'Details',
  stepPayment: 'Payment',
  stepReview: 'Review',
  editDetails: 'Edit Details',
  next: 'Next',
  back: 'Back',
  enterItemName: 'Enter item name',
  enterCustomerName: 'Enter customer name',
  draftSaved: 'Draft saved',
  keepDraft: 'Keep Draft',
  discardDraft: 'Discard',
  reviewSale: 'Review Sale',
  photoAttached: 'Photo attached',
  noPaymentCollected: 'No payment collected now. This sale will be added to Dubie.',
  settlementPaidNow: 'Paid now',
  settlementPaidPartly: 'Paid partly',
  settlementPayLater: 'Pay later',
  reviewTotal: 'Total',
  reviewItem: 'Item',
  reviewSettlement: 'Settlement',
  reviewProvider: 'Provider',
  reviewPaidAmount: 'Paid amount',
  reviewRemaining: 'Remaining',
  reviewCustomer: 'Customer',
  reviewReturnDate: 'Return date',
};

// My Shop keys (myShop, more, frequentExpenses, shareTodayTitle, shareTodayHint) are temporary translations
// and require native-speaker verification before pilot, alongside the broader Amharic review.
// Install-related Amharic strings below require human review before public beta:
// installSectionTitle, installBannerTitle, installBannerBody, installNow, installHowTo,
// installGuideButton, installGuideTitle, installGuideHint, installGuideDeviceTitle,
// installAlreadyInstalled, installStatusInstalled, installStatusBrowser,
// installStatusOnline, installStatusOffline, installChecklistOffline,
// installChecklistHomeScreen, installChecklistData, installChecklistReady,
// installChecklistInstalled, installChecklistPending, installChecklistOnPhone,
// installIosStep1, installIosStep2, installIosStep3, installAndroidStep1,
// installAndroidStep2, installAndroidStep3, installGenericStep1,
// installGenericStep2, installGenericStep3.
const AM = {
  installSectionTitle: 'መተግበሪያ ጫን',
  installBannerTitle: 'ገበያን በዚህ ስልክ ላይ ጫን',
  installBannerBody: 'ገበያን ወደ መነሻ ገጽ ያስቀምጡት እና እንደ ሞባይል መተግበሪያ ይክፈቱት።',
  installNow: 'አሁን ጫን',
  installHowTo: 'ጫን',
  installGuideButton: 'እንዴት እንደሚጫን',
  installGuideTitle: 'ገበያን በስልክዎ ላይ ጫን',
  installGuideHint: 'አንድ ጊዜ ጫን ካደረጉ በኋላ ገበያ እንደ ሞባይል መተግበሪያ ይሰማል።',
  installGuideDeviceTitle: 'የስልክ ጫን እርምጃዎች',
  installAlreadyInstalled: 'አስቀድሞ ተጭኗል',
  installStatusInstalled: 'በመነሻ ገጽ ላይ ተጭኗል',
  installStatusBrowser: 'በብራውዘር ውስጥ እየሰራ ነው',
  installStatusOnline: 'አሁን ኢንተርኔት አለ',
  installStatusOffline: 'አሁን ከኢንተርኔት ውጪ ነው',
  installChecklistOffline: 'ከኢንተርኔት ውጪ የሚሰራ ማስታወሻ',
  installChecklistHomeScreen: 'የመነሻ ገጽ ጫን',
  installChecklistData: 'የውሂብ ቦታ',
  installChecklistReady: 'ዝግጁ',
  installChecklistInstalled: 'ተጭኗል',
  installChecklistPending: 'ገና አይደለም',
  installChecklistOnPhone: 'በዚህ ስልክ',
  installIosStep1: 'ገበያን በ iPhone Safari ውስጥ ይክፈቱት።',
  installIosStep2: 'የማጋራት ቁልፉን ይጫኑና "Add to Home Screen" ይምረጡ።',
  installIosStep3: '"Add" ይጫኑ እና ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installAndroidStep1: 'ገበያን በ Android Chrome ውስጥ ይክፈቱት።',
  installAndroidStep2: 'የብራውዘር ምናሌ ይጫኑና "Install app" ወይም "Add to Home screen" ይምረጡ።',
  installAndroidStep3: 'ጫኑን ያረጋግጡና ገበያን ከመነሻ ገጽ ይክፈቱት።',
  installGenericStep1: 'ገበያን በስልክዎ ብራውዘር ውስጥ ይክፈቱት።',
  installGenericStep2: 'በብራውዘር ምናሌ "Install app" ወይም "Add to Home Screen" ይፈልጉ።',
  installGenericStep3: 'ያስቀምጡትና ገበያን ከመነሻ ገጽ ይክፈቱት።',
  updateReadyTitle: 'አዲስ እትም ዝግጁ ነው',
  updateReadyBody: 'አዲስ የመተግበሪያ እትም አለ። አንድ ጊዜ ያድሱ።',
  refreshApp: 'መተግበሪያውን አድስ',
  offlineReadyTitle: 'ከኢንተርኔት ውጪ ሁኔታ ዝግጁ ነው',
  offlineReadyBody: 'ገበያ ግንኙነት ደካማ ቢሆንም እንደገና ሊከፈት ይችላል፣ የተቀመጠውም ማስታወሻ በዚህ ስልክ ላይ ይቆያል።',
  offlineNowTitle: 'አሁን ከኢንተርኔት ውጪ ነው',
  offlineNowBody: 'በዚህ ስልክ ላይ የተቀመጠው ማስታወሻ እንደሚሰራ ይቀጥላል። ኢንተርኔት የሚፈልጉ ባህሪያት ግን እስከሚመለሱ ድረስ ሊጠብቁ ይችላሉ።',
  notNow: 'አሁን አይደለም',
  telegramNotifyConnectFirst: 'ቴሌግራምን በመጀመሪያ ያገናኙ፣ ከዚያ ይህን ያብሩ።',
  telegramConnectFirstToast: 'ዝመና ለመላክ ቴሌግራምን በመጀመሪያ ያገናኙ።',
  appName: 'ገበያ',
  loading: 'ማስታወሻ እየጫነ…',
  today: 'ዛሬ',
  todayLabel: 'ዛሬ',
  credit: 'ዱቤ',
  creditLabel: 'ዱቤ',
  report: 'ሪፖርት',
  settings: 'ቅንብሮች',
  sales: 'ሽያጭ',
  spent: 'ወጪ',
  iSold: 'ሸጠሁ',
  iSoldLabel: 'ሸጠሁ',
  iSpent: 'ወጪ',
  iSpentLabel: 'ወጪ',
  creditBtn: 'ዱቤ',
  creditBtnLabel: 'ዱቤ',
  calc: 'ሒሳብ',
  todaysEntries: 'የዛሬ ግቤቶች',
  noEntries: 'እስካሁን ምንም ግቤት የለም። ለመጀመር ከላይ ያሉትን ቁልፎች ይጠቀሙ!',
  profit: 'ትርፍ',
  edited: 'ተስተካክሏል',
  editEntry: 'ግቤት አስተካክል',
  deleteEntryLabel: 'ግቤት ሰርዝ',
  calculator: 'የትርፍ ካልኩሌተር',
  calcCost: 'የዋጋ ቅናሽ',
  calcSell: 'የሽያጭ ዋጋ',
  calcProfit: 'ትርፍ',
  calcMargin: 'ትርፍ (%)',
  calcPlaceholder: 'መጠን ያስገቡ…',
  topProducts: 'ዛሬ ምርጥ ሽያጭ',
  weekTrend: 'የ7 ቀን አዝማሚያ',
  shareReport: 'ሪፖርት አጋራ',
  shareReportBtn: 'ዛሬን አጋራ',
  shareTitle: 'ዕለታዊ ሪፖርት አጋራ',
  shareDailyReport: 'ዕለታዊ ሪፖርት',
  shareTopItems: 'ምርጥ ሽያጭ',
  shareSentVia: 'በ ገበያ (Gebya) ተልኳል',
  dubieGiven: 'በዕዳ የተሰጠ',
  paymentsCollected: 'የተሰበሰበ ክፍያ',
  netReceived: 'የተገኘ ገንዘብ',
  shareViaDevice: 'በስልክ አጋራ',
  openTelegram: 'ቴሌግራም ክፈት',
  copyText: 'ጽሑፍ ቅዳ',
  usageInsights: 'የአጠቃቀም ዝርዝር',
  dayStreak: 'ቀን ተከታታይ',
  best: 'ምርጥ',
  daysActive: 'ንቁ ቀናት',
  since: 'ጀምሮ',
  totalEntries: 'ግቤቶች',
  sessions: 'ክፍለ ጊዜ',
  shareMyStats: 'ስታቲስቲክሴን አጋራ 📤',
  copiedToClipboard: 'ተቀድቷል!',
  shopProfile: 'መገለጫ',
  userName: 'ስም',
  phoneNumber: 'ስልክ ቁጥር',
  phoneRequired: 'ስልክ ቁጥር ያስፈልጋል',
  phoneInvalid: '9 አሃዞች በ7 ወይም 9 የሚጀምሩ',
  telegramLabel: 'ቴሌግራም / ግንኙነት',
  telegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  connectTelegram: 'ቴሌግራም አገናኝ',
  manageTelegram: 'ቴሌግራም አስተዳድር',
  telegramConnection: 'የቴሌግራም ግንኙነት',
  telegramConnectHint: 'አንድ ጊዜ ቴሌግራም ያገናኙ፣ ከዚያ ሲፈልጉ የቀሪ ሂሳብ ማሳወቂያ ያብሩ።',
  telegramConnectedHint: 'ይህ ደንበኛ በቴሌግራም የቀሪ ሂሳብ መልእክት ሊደርሰው ይችላል።',
  notifyOnTelegram: 'በቴሌግራም አሳውቅ',
  notifyOnTelegramHint: 'ዱቤ ወይም ክፍያ ከተመዘገበ በኋላ ቴሌግራም ራሱን ይከፍታል።',
  telegramNotifyEnabledState: 'ለዚህ ደንበኛ ራስ-ሰር የቴሌግራም መክፈት ነቅቷል።',
  telegramNotifyDisabledState: 'ቴሌግራም አማራጭ ብቻ ነው፣ ራሱን አይከፍትም።',
  telegramNeedContactHint: 'መጀመሪያ የቴሌግራም ስም ወይም ሊንክ ያስገቡ፣ ከዚያ ማሳወቂያውን ያብሩ።',
  telegramFormatHint: '@username, t.me/... ወይም https://t.me/... ብቻ ይጠቀሙ።',
  telegramManualDraftHint: 'በእጅ የሚላኩ የቴሌግራም ዝመናዎች ከእያንዳንዱ ማስቀመጥ በኋላ እንደ ረቂቅ መልእክት ይከፈታሉ።',
  telegramAutoUpdatesTitle: 'ራስ-ሰር የቀሪ ሂሳብ ማሳወቂያ',
  telegramAutoUpdatesBody: 'ከተገናኘ በኋላ የዚህ ደንበኛ ቀሪ ሂሳብ ሲቀየር በቴሌግራም መልእክት ሊደርስለት ይችላል።',
  telegramBorrowerUpdatesLinked: 'የተበዳሪው ዝመናዎች ከGebya ቦት ጋር ተገናኝተዋል።',
  telegramBorrowerLinkWaiting: 'የተበዳሪው ሊንክ ቦቱን እስኪጀምር በመጠባበቅ ላይ ነው።',
  telegramManualSavedNotLinked: 'በእጅ የተቀመጠ የቴሌግራም መለያ አለ፣ ነገር ግን የቦት ዝመናዎች ገና አልተገናኙም።',
  telegramBorrowerNeedsBotStart: 'ዝመናዎች እንዲላኩ ተበዳሪው መጀመሪያ Gebya ቦቱን ማስጀመር አለበት።',
  telegramDraftUntilLinked: 'ተበዳሪው Gebya ቦቱን እስኪያገናኝ ድረስ ዝመናዎች እንደ ረቂቅ የቴሌግራም መልእክት ሊከፈቱ ይችላሉ።',
  telegramLinkBeforeUpdates: 'ዝመናዎችን ከማብራትዎ በፊት ተበዳሪውን ከGebya ቦት ጋር ያገናኙ።',
  telegramBorrowerNotStarted: 'ተበዳሪው ገና ቦቱን አልጀመረም።',
  qrPrimaryMethod: 'QR ኮድ',
  telegramQrHint: 'ይህን QR ኮድ እንዲስካን አድርጉት እና የቴሌግራም ግንኙነት ሊንኩን ይክፈት።',
  shareInviteLink: 'የግብዣ ሊንክ አጋራ',
  shareInviteLinkHint: 'ይህን ሊንክ ቅዳ እና በሚጠቀሙበት ማንኛውም መንገድ ላክ።',
  copyLink: 'ሊንክ ቅዳ',
  inviteLinkCopied: 'የግብዣ ሊንክ ተቀድቷል',
  copyFailed: 'ሊንኩን መቅዳት አልተቻለም',
  manualTelegramFallback: 'በእጅ ማስገባት',
  manualTelegramFallbackHint: 'ካስፈለገ የደንበኛውን @username ወይም t.me ሊንክ በእጅ ያስገቡ።',
  telegramGenerateBorrowerLinkFirst: 'በመጀመሪያ የተበዳሪ ቴሌግራም ሊንክ ያዘጋጁ።',
  telegramLatestUpdateSentAgain: 'የመጨረሻው የተበዳሪ ዝመና እንደገና ተልኳል።',
  telegramNoUpdateReady: 'ዳግመኛ ለመላክ ዝግጁ የሆነ የተበዳሪ ዝመና የለም።',
  telegramResendUpdateFailed: 'የተበዳሪውን ዝመና እንደገና መላክ አልተቻለም።',
  telegramSendFailed: 'የቴሌግራም መላክ አልተሳካም።',
  telegramManualInvalid: 'በእጅ የተገባው የቴሌግራም መለያ ልክ አይደለም።',
  telegramDubieSavedButFailed: 'ዱቤው ተቀምጧል። የቴሌግራም ማድረስ አልተሳካም።',
  confirmConnection: 'ግንኙነቱን አረጋግጥ',
  skipForNow: 'ለአሁን ዝለል',
  saveChanges: 'ለውጦችን አስቀምጥ',
  saved: 'ተቀምጧል!',
  privacy: 'ግላዊነት',
  hideAmounts: 'ቁጥሮችን ደብቅ',
  totalsHidden: 'ጠቅላላዎቹ ተደብቀዋል — ለማሳየት ተጭኑ',
  totalsVisible: 'ጠቅላላዎቹ ይታያሉ — ለመደበቅ ተጭኑ',
  paymentMethods: 'የክፍያ ዘዴዎች',
  banks: 'ባንኮች',
  mobileWallets: 'ሞባይል ዋሌት',
  onlyEnabled: 'የነቁ ዘዴዎች ብቻ በቅጹ ውስጥ ይታያሉ',
  recurringExpenses: 'ተደጋጋሚ ወጪዎች',
  recurringHint: 'ብዙ ጊዜ ለሚያስገቡዋቸው ወጪዎች ፈጣን ቅጽ',
  addRecurring: 'ተደጋጋሚ ወጪ አክል',
  demoCardSectionLabel: 'ፈጣን ሙላ (ምሳሌዎች)',
  recurringExampleRent: 'ኪራይ',
  recurringExampleEqub: 'እቁብ',
  addRecurringPopupGuide: 'ይህን ወጪ ለሚቀጥሉ ጊዜያት አስቀምጥ',
  addAndUse: 'አስቀምጥ & ተጠቀም',
  addRecurringHint: 'ሌሎች ተደጋጋሚ ወጪዎችን በቅንብሮች ውስጥ ማከል ይችላሉ',
  frequency: 'ድግግሞሽ',
  cancel: 'ሰርዝ',
  add: 'አክል',
  yourData: 'ያንዎ ውሂብ',
  storedOnDevice: 'በዚህ ስልክ ላይ ተቀምጧል',
  exportCSV: 'CSV ወደ ውጭ ላክ',
  exportHint: 'ሰነድ ምትኬ ያውርዱ',
  clearAll: 'ሁሉንም ውሂብ አጥፋ',
  clearHint: 'ሁሉም ነገር ሙሉ በሙሉ ይሰረዛል — መጀመሪያ ይልኩ!',
  about: 'ስለ ፕሮግራሙ',
  privacyNote: 'ውሂቡ ከዚህ ስልክ አይወጣም። ምዝገባ አያስፈልግም።',
  worksOffline: 'ያለ ኢንተርኔት ይሰራል · ውሂቡ በስልክዎ ላይ ይቆያል · ነፃ',
  achievementBadges: 'የስኬት ባጆች',
  badgesEarned: 'ተገኝቷል',
  noBadges: 'ባጆች ለማግኘት ኢላማዎቹን ያሟሉ!',
  clearConfirm: 'ሁሉንም ውሂብ አጥፋ?',
  clearConfirmMsg: 'ይህ ሁሉን {count} ግቤቶችና {credits} የዱቤ መዝገቦችን ሙሉ በሙሉ ይሰርዛል። ሊቀለበስ አይችልም።',
  yesDelete: 'አዎ፣ ሁሉንም ሰርዝ',
  dataCleared: 'ውሂቡ ተሰርዟል',
  reloading: 'እንደገና እየጫነ…',
  deleteEntry: 'ይህን ግቤት ትሰርዛለህ?',
  delete: 'ሰርዝ',
  newBestDay: '🏆 አዲስ ምርጥ ቀን!',
  birr: 'ብር',
  daily: 'ዕለታዊ',
  weekly: 'ሳምንታዊ',
  monthly: 'ወርሃዊ',
  expenseName: 'የወጪ ስም (ለምሳሌ ኪራይ)',
  amount: 'መጠን',
  sun: 'እሁድ', mon: 'ሰኞ', tue: 'ማክሰ', wed: 'ረቡዕ', thu: 'ሐሙስ', fri: 'ዓርብ', sat: 'ቅዳሜ',

  onboardWelcome: 'ማስታወሻዎን ጀምር',
  onboardSubtitle: 'የንግድ ማስታወሻዎ',
  onboardTagline: 'የሱቅ ማስታወሻ ደብተር',
  onboardDesc: 'በስምዎ ይጀምሩ፤ ሽያጭ፣ ወጪ እና ዱቤን በጥቂት መንካት ይመዝግቡ።',
  onboardNamePlaceholder: 'ለምሳሌ ትግስት',
  onboardPhoneOptional: '(አማራጭ)',
  onboardPhoneHelper: 'ስልክዎን በቅንብሮች ውስጥ በኋላ ማከል ይችላሉ።',
  onboardBusinessTypeLabel: 'የንግድ ዓይነት',
  onboardBusinessTypeOptional: '(አማራጭ)',
  onboardBusinessTypeHelper: 'የሚስማማውን ይምረጡ ወይም ይጻፉ፤ ገበያ በኋላ ፈጣን ጥቆማ ለመስጠት ይረዳል።',
  onboardBusinessTypePlaceholder: 'ወይም የንግድዎን ዓይነት ይጻፉ',
  businessTypeShop: 'ሱቅ',
  businessTypeWholesale: 'ጅምላ',
  businessTypeDistributor: 'ዲስትሪቢዩተር',
  businessTypeBoutique: 'ቡቲክ',
  businessTypeCafe: 'ካፌ',
  businessTypeService: 'አገልግሎት',
  businessTypeOther: 'ሌላ',
  onboardPromiseSimple: 'ለሽያጭ፣ ወጪ እና ዱቤ ቀላል ማስታወሻ',
  onboardPromiseFast: 'በስምዎ ብቻ ይጀምሩ',
  onboardPromisePrivate: 'መዝገቦችዎ በዚህ ስልክ ላይ ይቆያሉ',
  onboardGetStarted: 'ገበያን ጀምር',
  onboardSettingUp: 'በማዘጋጀት ላይ…',
  onboardFooter: 'ውሂቡ በስልክዎ ላይ ይቆያል · ምዝገባ አያስፈልግም · ነፃ',

  iSoldSomething: 'ሸጠሁ',
  iSpentSomething: 'ወጪ',
  recordCredit: 'ዱቤ መዝግብ',
  addCredit: 'ዱቤ ጨምር',
  addCustomer: 'ደንበኛ ጨምር',
  saveCustomer: 'ደንበኛ አስቀምጥ',
  customerSaved: 'ደንበኛ ተቀምጧል',
  customerSaveFailed: 'ደንበኛውን ማስቀመጥ አልተቻለም። እባክዎ ደግመው ይሞክሩ።',
  customerHelperText: 'በኋላ በቀላሉ የሚያስታውሱትን መለያ ይጠቀሙ።',
  customerIdentifier: 'የደንበኛ መለያ',
  customerIdentifierPlaceholder: 'ስም፣ ቅጽል፣ ዝምድና፣ ቦታ ወይም የመኪና ምልክት',
  customerNotePlaceholder: 'ይህን ደንበኛ ለማስታወስ የሚረዳ ማንኛውም ማስታወሻ',
  customerPhoneOptional: 'ስልክ (አማራጭ)',
  customerPhonePlaceholder: 'ስልክ ቁጥር',
  customerTelegramOptional: 'ቴሌግራም (አማራጭ)',
  customerTelegramPlaceholder: '@username, t.me/... ወይም https://t.me/...',
  customerTotalBalance: 'ጠቅላላ ቀሪ ሂሳብ',
  customerBalance: 'ቀሪ ሂሳብ',
  searchCustomerPlaceholder: 'ደንበኛ ወይም ማስታወሻ ፈልግ...',
  customerSearchHint: 'በስም፣ በማስታወሻ፣ በስልክ ወይም በቴሌግራም ፈልጉ።',
  customerSearchResults: 'ከ {total} ደንበኞች ውስጥ {shown} ታይተዋል',
  noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
  noCustomersYet: 'ገና ምንም ደንበኞች የሉም',
  noCustomerSearchResults: 'ከዚህ ፍለጋ ጋር የሚዛመዱ ደንበኞች አልተገኙም',
  backToCustomers: 'ወደ ደንበኞች ተመለስ',
  customerTransactionHistory: 'የግብይት ታሪክ',
  paymentRecordedLabel: 'ክፍያ',
  creditAddedLabel: 'ዱቤ ተጨምሯል',
  noTransactionsYet: 'እስካሁን ምንም ግብይት የለም',
  noTransactionsHint: 'ይህን ታሪክ ለመጀመር ዱቤ ጨምር ወይም ክፍያ መዝግብ ይጠቀሙ።',
  currentBalance: 'አሁን ያለ ቀሪ ሂሳብ',
  previousBalance: 'ያለፈው ቀሪ ሂሳብ',
  updatedBalance: 'የተሻሻለ ቀሪ ሂሳብ',
  currentBalanceHint: 'ይህ አዲሱን ዱቤ ካስቀመጡ በኋላ የሚታየው ቀሪ ሂሳብ ነው።',
  remainingBalanceHint: 'ይህ ክፍያውን ካስቀመጡ በኋላ የሚቀረው ቀሪ ሂሳብ ነው።',
  paymentNoteOptional: 'የክፍያ ማስታወሻ (አማራጭ)',
  itemNoteOptional: 'የተወሰደው ማስታወሻ (አማራጭ)',
  paymentNotePlaceholder: 'ስለዚህ ክፍያ ማንኛውም ማስታወሻ',
  creditItemPlaceholder: 'የወሰዱት ምንድን ነው',
  savedCatalogLabel: 'የተቀመጠ ዕቃ / አገልግሎት',
  typeManually: 'በእጅ ይጻፉ',
  typeNoteManually: 'ማስታወሻ በእጅ ይጻፉ',
  serviceLabel: 'አገልግሎት',
  itemLabel: 'ዕቃ',
  dueDateOptional: 'የመክፈያ ቀን (አማራጭ)',
  ethiopianDisplay: 'በኢትዮጵያ ቀን መቁጠሪያ',
  pickDateWithEthiopianHint: 'ቀን ይምረጡ፣ እኛም በኢትዮጵያ ቀን መቁጠሪያ እናሳያለን።',
  moreOptional: 'ተጨማሪ (አማራጭ)',
  noteLabel: 'ማስታወሻ',
  savePayment: 'ክፍያ አስቀምጥ',
  customerNotFound: 'ደንበኛው አልተገኘም',
  validAmountRequired: 'ትክክለኛ መጠን ያስገቡ',
  paymentMoreThanBalance: 'ክፍያው ካለው ቀሪ ሂሳብ ይበልጣል',
  noBalanceToRecordPayment: 'ገና የሚሰበሰብ ቀሪ ሂሳብ የለም',
  balanceAfterEntry: 'ከዚህ ግቤት በኋላ ያለ ቀሪ ሂሳብ',
  dueLabelShort: 'መክፈያ',
  whatDidYouSell: 'ምን ሸጡ?',
  sellPlaceholder: 'ለምሳሌ ዳቦ፣ ስኳር…',
  whatDidYouSpendOn: 'ወጪው ለምን ነው?',
  spendPlaceholder: 'ለምሳሌ ትራንስፖርት፣ ኪራይ…',
  creditNameLabel: 'ስም',
  creditNamePlaceholder: 'ለምሳሌ አበበ…',
  howMuchTotal: 'ጠቅላላ ስንት ነው?',
  saveSale: 'ሽያጭ አስቀምጥ',
  saleSettlementLabel: 'እንዴት ተከፈለ?',
  saleSettlementPaidNow: 'አሁን ተከፍሏል',
  saleSettlementPaidNowHint: 'ቀሪ የለም',
  saleSettlementPaidPartly: 'በከፊል ተከፍሏል',
  saleSettlementPaidPartlyHint: 'ከፊሉ አሁን ተከፍሏል',
  saleSettlementPayLater: 'በኋላ ይከፈላል',
  saleSettlementPayLaterHint: 'ሙሉው ክፍት ይቀራል',
  salePaidAmountLabel: 'አሁን ስንት ተከፈለ?',
  salePaidAmountHint: 'የተከፈለው መጠን ከ0 በላይ እና ከጠቅላላው ያነሰ መሆን አለበት።',
  saleCustomerRequiredHint: 'ቀሪውን የሚይዘውን ደንበኛ ያስገቡ።',
  saleRemainingBalanceLabel: 'ቀሪ ሂሳብ',
  saleRemainingBalanceHint: 'ካስቀመጡ በኋላ ቀሪው መጠን ወደ ዚህ ደንበኛ ሂሳብ ይጨመራል።',
  saleSavedWithBalance: 'ሽያጩ ተቀምጧል። ቀሪው ወደ ደንበኛው ሂሳብ ተጨምሯል።',
  saleLinkedBalanceTitle: 'ይህ ሽያጭ ቀሪ የደንበኛ ሂሳብ አለው።',
  saleLinkedBalanceBody: 'የሽያጩን ጠቅላላ ከቀየሩ የተገናኘው ቀሪ ሂሳብ እንዲሁ ይቀየራል።',
  saleRemainingHistory: 'ቀሪ',
  salePaidShort: 'ተከፍሏል',
  saleLabelShort: 'ሽያጭ',
  saveExpense: 'ወጪ አስቀምጥ',
  saveCredit: 'ዱቤ አስቀምጥ',
  addAnotherSale: 'ሌላ ሽያጭ አክል',
  addAnotherExpense: 'ሌላ ወጪ አክል',
  done: 'ተጠናቀቀ',
  birrSaved: 'ብር ተቀምጧል',
  howMany: 'ስንት?',
  direction: 'አቅጣጫ',
  theyOweMe: 'ያበደርኩት',
  iOweThem: 'የተበደርኩት',
  owesMe: 'ያበደርኩት',
  iOweLabel: 'የተበደርኩት',
  quickFill: 'ፈጣን ሙላ',
  phoneOptional: 'ስልክ ቁጥር',
  phoneOptionalHint: '(ምርጫ)',
  phonePlaceholder: 'ለምሳሌ 0912345678',
  whenDue: 'መቼ ይከፈላል?',
  pickDate: 'ቀን ምረጥ',
  selectDueDate: 'የክፍያ ቀን ይምረጡ',
  advancedOptional: 'ተጨማሪ (ምርጫ)',
  whatDidYouPay: 'ይህ ክፍያ ለምንድን ነው?',
  perUnit: '(በአንድ)',
  helpsSeeProfit: 'ምርጫ — ትክክለኛውን ትርፍ ለማየት ይረዳል',
  sellingBelowCost: 'ከዋጋ በታች እየሸጡ ነው። ኪሳራ ሊደርስ ይችላል።',
  profitOnSale: 'በዚህ ሽያጭ ትርፍ:',
  paymentType: 'የክፍያ አይነት',
  cash: 'ጥሬ ገንዘብ',
  bank: 'ባንክ',
  wallet: 'ዋሌት',

  editSale: 'ሽያጭ አስተካክል',
  editExpense: 'ወጪ አስተካክል',
  editCredit: 'ዱቤ አስተካክል',
  editEntryLabel: 'ግቤት አስተካክል',
  editedAt: 'ተስተካክሏል',
  item: 'ዕቃ',
  quantity: 'ብዛት',
  dueDate: 'የክፍያ ቀን',
  costPriceLabel: 'የመግዣ ዋጋ',
  sellingBelowCostShort: 'ከዋጋ በታች።',
  profitLabel: 'ትርፍ:',
  saving: 'እየተቀመጠ…',

  todaysProfit: 'የዛሬ ትርፍ',
  estimatedProfit: 'ግምታዊ ትርፍ',
  partialCostDisclaimer: 'አንዳንድ ዕቃዎች የዋጋ መረጃ ጎድሏቸዋል — ይህ ግምት ከትክክለኛው ትርፍ ያነሰ ሊሆን ይችላል',
  partialCostTip: 'ትክክለኛ ትርፍ ለማየት የመግዣ ዋጋ ያስገቡ',
  todaysSales: 'የዛሬ ሽያጭ',
  salesLabel: 'ሽያጭ',
  expenses: 'ወጪዎች',
  costOfGoods: 'የዕቃ ዋጋ',
  netProfit: 'ንጹህ ትርፍ',
  advancedHint: 'ትክክለኛውን ትርፍ ለማየት ሽያጭ ሲመዘግቡ "ተጨማሪ" ተጭኑ',

  tapToReveal: 'ለማሳየት ተጭኑ',
  tapToRevealAria: 'መጠንን ለማሳየት ተጭኑ',
  hideAmountAria: 'መጠንን ደብቅ',

  byDay: 'በቀን',
  byWeek: 'በሳምንት',
  groupBy: 'ቡድን:',
  searchPlaceholder: 'በዕቃ ወይም ደንበኛ ፈልግ…',
  noSearchResults: 'ምንም ውጤት',
  noRecords: 'እስካሁን ምንም መዝገብ የለም',
  startRecording: 'ለመጀመር የመጀመሪያ ሽያጭ ወይም ወጪ ይመዝግቡ',
  entries: 'ግቤቶች',
  revenue: 'ገቢ',
  thisWeek: 'ይህ ሳምንት',

  noCreditRecords: 'የዱቤ መዝገብ የለም',
  addCreditHint: 'ዱቤ ለማክል በዛሬ ገጽ ላይ "ዱቤ" ተጭኑ',
  owedToMe: 'ያበደርኩት',
  iOweAmount: 'የተበደርኩት',
  active: 'ንቁ',
  paid: 'የተከፈለ',
  activeTab: 'ንቁ',
  paidTab: 'የተከፈለ',
  noPaidRecords: 'እስካሁን የተከፈለ መዝገብ የለም',
  allCaughtUp: 'ሁሉም ተከፍሏል!',
  paidInFull: 'ሙሉ ተከፍሏል',
  paidLabel: 'ተከፍሏል',
  due: 'ክፍያ',
  owesMeLabel: 'ያበደርኩት',
  iOweTag: 'የተበደርኩት',

  backToCredit: 'ወደ ዱቤ ተመለስ',
  originalDebt: 'ዋና ዕዳ',
  amountPaid: 'የተከፈለ',
  stillOwes: 'ቀሪ ዕዳ',
  progress: 'ሂደት',
  percentPaid: '% ተከፍሏል',
  paidSome: 'ከፊል ክፍያ',
  allPaid: 'ሙሉ ተከፍሏል',
  call: 'ደውል',
  recordPartialPayment: 'ከፊል ክፍያ መዝግብ',
  recordPayment: 'ክፍያ መዝግብ',
  markFullyPaid: 'ሙሉ ተከፍሏል ብለህ ምልክት አድርግ',
  paymentHistory: 'የክፍያ ታሪክ',
  borrowed: 'የተበደረ',
  paidBack: 'የተመለሰ',
  remaining: 'ቀሪ',
  payMethodCash: 'ጥሬ ገንዘብ',
  payMethodBank: 'ባንክ ዝውውር',
  payMethodMobile: 'ሞባይል ገንዘብ',
  paymentExceedsOwed: 'መጠኑ ከሚገባው መጠን ሊበልጥ አይችልም',

  voiceNotSupported: 'ድምጽ አይደገፍም — የቁልፍ ሰሌዳ ይጠቀሙ',
  voiceInput: 'ድምጽ',
  tryAgain: 'እንደገና ሞክር',
  voiceMicBlocked: 'ማይክሮፎኑ ታግዷል። የአሳሽ ቅንብሮችን ይመልከቱ።',

  close: 'ዝጋ',

  todaysBreakdown: 'የዛሬ ሂሳብ',
  payingVia: 'በ',
  creditPhoneHint: '9 አሃዞች፣ ከ7 ወይም 9 ይጀምሩ',
  // TEMPORARY: Amharic translations for new My Shop keys need native review before pilot
  myShop: 'የእኔ ሱቅ',
  more: 'ተጨማሪ',
  frequentExpenses: 'ተደጋጋሚ ወጪዎች',
  shareTodayTitle: 'የዛሬን ሪፖርት አጋራ',
  shareTodayHint: 'የዛሬን የሱቅ ማጠቃለያ ለባለቤቱ ይላኩ ወይም ቅጂ ያስቀምጡ።',
  addCustomBank: 'ባንክ አክል…',
  addCustomWallet: 'ዋሌት አክል…',
  customProviderName: 'ስም',
  providerEnabled: 'ነቋል',
  providerDisabled: 'ተዘግቷል',

  introSlide1Title: 'የሱቅ ማስታወሻ',
  introSlide1Body: 'ሽያጭ፣ ወጪ፣ ዱቤ — ሁሉም በስልክ። ምዝገባ አያስፈልግም።',
  introSlide2Title: 'ገንዘቡን ፈጥኖ ይመልከቱ',
  introSlide2Body: 'የዛሬ ትርፍ ሁሌ ከላይ ይታያል። ሁኔታዎን በሰከንዶች ያውቁ።',
  introSlide3Title: 'ሦስት ቁልፎች ብቻ',
  introSlide3Body: 'ሸጠሁ፣ ወጪ፣ ዱቤ። ሂደቱ ለ10 ሰኮንዶች ብቻ ነው።',
  introLetsStart: 'ጀምር 🚀',
  introNext: 'ቀጣይ →',
  introSkip: 'ዝለል',

  noEntriesPrompt: 'ለማስቀመጥ ከላይ "ሸጠሁ" ይጫኑ',
  noSalesRecordedYet: 'ገና ሽያጭ አልተመዘገበም',
  recordFirstSalePrompt: 'የመጀመሪያ ሽያጭዎን ለመመዝገብ ከላይ ይጫኑ',

  saleSaved: '✅ ሽያጭ ተቀምጧል · 🔥 ቀጥሉ',
  expenseSaved: 'ወጪ ተቀምጧል ✓',
  creditSaved: 'ዱቤ ተቀምጧል ✓',
  undone: 'ተሰርዟል ✓',

  statusOverdue: 'ዘግይቷል',
  statusDueSoon: 'ይቃረባል',
  statusOk: 'ጥሩ',

  periodDay: 'ቀን',
  periodWeek: 'ሳምንት',
  periodMonth: 'ወር',
  totalSales: 'ጠቅላላ ሽያጭ',
  totalExpenses: 'ጠቅላላ ወጪ',
  topProductsWeek: 'የሳምንቱ ምርጥ ሽያጭ',
  topProductsMonth: 'የወሩ ምርጥ ሽያጭ',
  topProductsDay: 'ዛሬ ምርጥ ሽያጭ',
  byQuantity: 'በብዛት',
  byRevenue: 'በገቢ',
  weekBreakdown: 'በቀን',
  monthBreakdown: 'በሳምንት',
  weekOf: 'ሳምንት',
  noSalesThisPeriod: 'በዚህ ወቅት ሽያጭ የለም',
  week: 'ሳምንት',

  recordByVoice: 'ሽያጭ ለማስቀምጥ ይናገሩ',
  recordByVoiceSubLabel: 'ሽያጥ ለማስቀምጥ ቀላሉ መንገድ',
  typeSale: 'በጽሑፍ ሸጥ',
  typeSaleLabel: 'በጽሑፍ ሸጥ',
  voiceRecordingTitle: 'እየቀዳ…',
  voiceRecordingHint: 'የሽያጭ መጠን ይናገሩ',
  voiceStop: 'አቁም',
  voiceTypeInstead: 'በጽሑፍ ያስገቡ',
  voiceNoInternet: 'የኢንተርኔት ግንኙነት የለም',
  voiceNoInternetHint: 'የድምጽ ቅዳ ኢንተርኔት ያስፈልጋል። በጽሑፍ ሽያጭ ማስቀመጥ ይችላሉ።',
  voiceTypeSaleInstead: 'በጽሑፍ ሸጥ',
  voiceRetry: 'እንደገና ሞክር',
  voiceTryFinishSoon: '⚠️ ለመጨረስ ቶሎ ይሞክሩ',
  voiceListeningState: 'እየሰማ',
  voiceStoppedState: 'ቆሟል',
  voiceProcessingState: 'በማቀናበር ላይ',
  voiceLivePreview: 'የሰማው',
  voiceLivePreviewHint: 'ከማስቀመጥ በፊት የተሰሙ ቃላት እዚህ ይታያሉ።',
  voiceResultTitle: 'የድምጽ ውጤት',
  voiceTranscript: 'የተናገሩት',
  voiceDetectedTotal: 'የተገኘ ጠቅላላ',
  voiceNoAmount: 'መጠን አልተገኘም',
  voiceNeedsReview: 'ከማስቀመጥ በፊት ይህን ረቂቅ ይመልከቱ።',
  voiceParsedItems: 'የተለዩ ዕቃዎች',
  voiceCustomerName: 'ደንበኛ',
  voiceCustomerPlaceholder: 'ከተጠቀሰ የደንበኛ ስም',
  voiceIntent: 'ዓይነት',
  voiceIntentSale: 'ሽያጭ',
  voiceIntentCredit: 'ዱቤ',
  voiceIntentPayment: 'ክፍያ',
  voiceQuantity: 'ብዛት',
  voiceUnitPrice: 'የአንዱ ዋጋ',
  voiceAutoCalculatedTotal: 'ጠቅላላው ከዕቃ መስመሮች በራስ-ሰር ተቆጥሯል።',
  voiceItemNamePlaceholder: 'የዕቃ ስም',
  voiceSave: 'ሽያጭ አስቀምጥ',
  voiceFix: 'አስተካክል',
  voiceReRecord: 'እንደገና ቅዳ',
  voiceFixTitle: 'የድምጽ ሽያጭ አስተካክል',
  voiceTotalLabel: 'ጠቅላላ መጠን',
  voiceNoteLabel: 'ማስታወሻ (ምርጫ)',
  voiceNotePlaceholder: 'ለምሳሌ ዳቦ፣ ስኳር…',
  voiceSaleSaved: 'የድምጽ ሽያጭ ተቀምጧል ✓',
  voiceAddAnotherItem: 'ሌላ ዕቃ አክል',
  voiceRunningTotal: 'ድምር ጠቅላላ',
  voiceItemsRecorded: 'ዕቃዎች ተመዝግበዋል',
  voiceSalesOnlyTitle: 'በድምጽ ማስገባት አሁን ለሽያጭ ብቻ ነው።',
  voiceSalesOnlyBody: 'ይህ ረቂቅ ዱቤ ወይም ክፍያ የሚመስል ነው። እንደ ሽያጭ ከማስቀመጥ በፊት በጥንቃቄ ይመልከቱት።',
  telegramLinkedOnTelegram: 'ተበዳሪው በቴሌግራም ተገናኝቷል።',
  telegramWaitingForBorrower: 'ተበዳሪው ቦቱን እስኪጀምር በመጠባበቅ ላይ ነው።',
  telegramServiceUnavailableNow: 'የቴሌግራም አገልግሎት አሁን አይገኝም።',
  telegramManualStillWorks: 'የቴሌግራም አገልግሎት አሁን አይገኝም። በእጅ የተቀመጠ መለያ ግን ይሰራል።',
  telegramLinkedUpdatesReady: 'የተገናኙ የተበዳሪ ዝመናዎች ዝግጁ ናቸው።',
  telegramGenerateLinkHint: 'የተበዳሪውን ሊንክ ያዘጋጁ፣ ከዚያ እሱ እንዲስካን ወይም በቴሌግራም እንዲከፍተው ይፍቀዱለት።',
  telegramOpenBot: 'ቦቱን ክፈት',
  telegramRefreshStatus: 'ሁኔታ አድስ',
  telegramBorrowerStartedAs: 'ተበዳሪው ቦቱን እንደ {username} ጀምሯል።',
  telegramLinkingUnavailable: 'በራስ-ሰር የቴሌግራም ማገናኘት አሁን አይገኝም።',
  telegramManualCanEnableLater: 'ከታች በእጅ የቴሌግራም መለያ ማስቀመጥ ይችላሉ፣ ራስ-ሰር ዝመናዎችንም በኋላ ማብራት ይችላሉ።',
  telegramApiServerNeeded: 'ከታች በእጅ የቴሌግራም መለያ ማስቀመጥ ይችላሉ። የቦት ማገናኘትና ራስ-ሰር ዝመናዎች የAPI ሰርቨሩን ይፈልጋሉ።',
  telegramSaveFallbackContact: 'የአማራጭ መለያ አስቀምጥ',
  telegramResending: 'እንደገና በመላክ ላይ...',
  telegramResendLatestUpdate: 'የመጨረሻውን ዝመና እንደገና ላክ',

  stepDetails: 'ዝርዝር',
  stepPayment: 'ክፍያ',
  stepReview: 'መልስ',
  stepDetailsAm: 'ዝርዝር',
  stepPaymentAm: 'ክፍያ',
  stepReviewAm: 'መልስ',
  editDetails: 'ዝርዝር አስተካክል',
  editPayment: 'ክፍያ አስተካክል',
  next: 'ቀጣይ',
  back: 'ተመለስ',
  enterItemName: 'የዕቃ ስም ያስገቡ',
  enterCustomerName: 'የደንበኛ ስም ያስገቡ',
  draftSaved: 'ረቂቅ ተቀምጧል',
  keepDraft: 'ረቂቅ ለዋል',
  discardDraft: 'አስይዝ',
  reviewSale: 'ሽያጭ ይመልከቱ',
  photoAttached: 'ፎቶ ተቀምጧል',
  noPaymentCollected: 'አሁን ክፍያ አልተሰበሰበም። ይህ ሽያጭ ወደ ዱቤ ይጨመራል።',
  settlementPaidNow: 'አሁን ተከፈለ',
  settlementPaidPartly: 'በከፊል ተከፈለ',
  settlementPayLater: 'በኋላ ይከፈላል',
  reviewTotal: 'ጠቅላላ',
  reviewItem: 'ዕቃ',
  reviewSettlement: 'ክፍያ',
  reviewProvider: 'አቅራቢ',
  reviewPaidAmount: 'የተከፈለ',
  reviewRemaining: 'ቀሪ',
  reviewCustomer: 'ደንበኛ',
  reviewReturnDate: 'የመለስ ቀን',
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gebya_lang') || 'en');

  useEffect(() => {
    document.documentElement.lang = lang;
    document.body.dataset.lang = lang;
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'am' : 'en';
      localStorage.setItem('gebya_lang', next);
      return next;
    });
  };

  const t = lang === 'am' ? AM : EN;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
